/*
Part of the EDG Compiler Project, under the Apache License v2.0 with LLVM
Exceptions.
See https://edgcpp.org/LICENSE.txt for license information.
SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
*/

/*

floating.h -- Definitions related to floating-point conversions.

*/

#ifndef FLOATING_H
#define FLOATING_H

#if !USE_HOST_FP_CONVERSION_ROUTINES || \
    (USE_FLOAT128_FOR_HOST_FP_VALUE && !USE_QUADMATH_LIBRARY)

/* Conditionally open the "edg" namespace. */
BEGIN_EDG_NAMESPACE

/*
The value of the macro FP_USE_EMULATION determines whether the conversion code
uses native floating-point math (when FP_USE_EMULATION is FALSE) or emulated
floating-point math (when FP_USE_EMULATION is TRUE).  These host floating-
point operations are used only when determining approximate results for
floating-point conversion; integer math is used in all cases to do any
final adjustment needed to obtain a correct result.  Using native floating-
point math gives better performance (though floating-point conversion is
not typically a bottleneck for most programs), but some floating-point
differences can be seen (i.e., on a 64-bit Intel processor, one-bit errors
can be seen when using 64-bit mode due to differences between the SSE2
and x87 instructions used).  Defaults to TRUE (since that's most portable
and most likely to yield correct results).
*/
#ifndef FP_USE_EMULATION
#define FP_USE_EMULATION TRUE
#endif /* ifndef FP_USE_EMULATION */

/*
The value of the macro JAVA_STYLE_SHORTEST determines whether the conversion
code requires the shortest sequence of digits generated by the conversion code
to have at least two digits.  A value of FALSE allows 1-digit sequences; a
value of TRUE requires at least two digits.
*/
#ifndef JAVA_STYLE_SHORTEST
#define JAVA_STYLE_SHORTEST TRUE
#endif /* ifndef JAVA_STYLE_SHORTEST */

/*
As part of the underlying mechanism used during floating-point conversion,
it is necessary to store very large integer values (much larger than can
be stored in a single host integer type).  Internally, the a_bigint structure
is used for this task; it contains an array of unsigned integers
to hold components of the integer value.  The types described here, namely,
FP_BIGINT_WORD_UNSIGNED_TYPE, FP_BIGINT_INTEGER_UNSIGNED_TYPE, and
FP_BIGINT_INTEGER_SIGNED_TYPE are used to implement the a_bigint type and
operations on a_bigint and are subject to the following restrictions.

FP_BIGINT_INTEGER_UNSIGNED_TYPE (used to perform arithmetic on the components
of the large integer) should specify the largest host unsigned integer type
available.  FP_BIGINT_INTEGER_SIGNED_TYPE should be the host signed integer
version of FP_BIGINT_INTEGER_UNSIGNED_TYPE.

FP_BIGINT_WORD_UNSIGNED_TYPE (used to store components of the large integer)
should specify a host unsigned integer type whose size is exactly half that
of FP_BIGINT_INTEGER_UNSIGNED_TYPE.  If no such type exists, then
FP_BIGINT_WORD_UNSIGNED_TYPE can be set to a larger host unsigned integer
type, however, in this case BIGINT_WORD_BYTES must be set to a value that
represents half of the size of the FP_BIGINT_INTEGER_UNSIGNED_TYPE type.
*/

#ifndef FP_BIGINT_INTEGER_UNSIGNED_TYPE
#define FP_BIGINT_INTEGER_UNSIGNED_TYPE unsigned long long
#endif /* ifndef FP_BIGINT_INTEGER_UNSIGNED_TYPE */

#ifndef FP_BIGINT_INTEGER_SIGNED_TYPE
#define FP_BIGINT_INTEGER_SIGNED_TYPE long long
#endif /* ifndef FP_BIGINT_INTEGER_SIGNED_TYPE */

#ifndef FP_BIGINT_WORD_UNSIGNED_TYPE
#define FP_BIGINT_WORD_UNSIGNED_TYPE unsigned int
#endif /* ifndef FP_BIGINT_WORD_UNSIGNED_TYPE */

#ifndef BIGINT_WORD_BYTES
#define BIGINT_WORD_BYTES sizeof(FP_BIGINT_WORD_UNSIGNED_TYPE)
#endif /* ifndef BIGINT_WORD_BYTES */

typedef FP_BIGINT_WORD_UNSIGNED_TYPE a_bigint_word;
typedef FP_BIGINT_INTEGER_UNSIGNED_TYPE a_bigint_uint;
typedef FP_BIGINT_INTEGER_SIGNED_TYPE a_bigint_int;

/* Type used for internal unsigned integer values (must be larger than
   FP_BIGINT_WORD_UNSIGNED_TYPE). */
typedef FP_BIGINT_INTEGER_UNSIGNED_TYPE an_fp_uint;

/*
Most targets have IEEE 754-2008 binary32 (float) and binary64 (double) support,
but there is wide variation in long double floating-point formats among target
processors.  The long double type can be configured by using one of these
high-level configuration macros:

FP_LONG_DOUBLE_IS_BINARY64: IEEE 754-2008 binary64 (i.e., same as "double" --
                            used by the Microsoft compiler)
FP_LONG_DOUBLE_IS_BINARY128: IEEE 754-2008 binary128 (typically for SPARC
                             processors), or
FP_LONG_DOUBLE_IS_80BIT_EXTENDED: IEEE 754-2008 80-bit extended (typically for
                                  Intel processors).

Alternatively, the long double type can be specified using the
lower-level FPT_LONG_DOUBLE_VALUE_BITS, FPT_LONG_DOUBLE_HAS_HIDDEN, and
FPT_LONG_DOUBLE_PRECISION macros (see float_type.h for an explanation).
*/

#if FP_HAS_LONG_DOUBLE && \
    !defined(FP_LONG_DOUBLE_IS_BINARY64) && \
    !defined(FP_LONG_DOUBLE_IS_BINARY128) && \
    !defined(FP_LONG_DOUBLE_IS_80BIT_EXTENDED) && \
    !defined(FPT_LONG_DOUBLE_VALUE_BITS) && \
    !defined(FPT_LONG_DOUBLE_HAS_HIDDEN) && \
    !defined(FPT_LONG_DOUBLE_PRECISION)
#if USE_HOST_FP_CONVERSION_ROUTINES
/* We only need the internal routines described in this header because
   USE_FLOAT128_FOR_HOST_FP_VALUE is TRUE and USE_QUADMATH_LIBRARY is
   FALSE, i.e., we won't be using this code for anything other than to
   provide support for the float128 type.  Consequently, having an accurate
   configuration for long double is unnecessary and we arbitrarily
   designate binary128 as the representation. */
#define FP_LONG_DOUBLE_IS_BINARY128 TRUE
#else /* !USE_HOST_FP_CONVERSION_ROUTINES */
#error Type "long double" is configured but un-specified.
#endif /* USE_HOST_FP_CONVERSION_ROUTINES */
#endif /* !defined(FP_LONG_DOUBLE_IS_BINARY128) && ... */

#ifndef FP_LONG_DOUBLE_IS_BINARY64
#define FP_LONG_DOUBLE_IS_BINARY64 FALSE
#endif /* ifndef FP_LONG_DOUBLE_IS_BINARY64 */

#ifndef FP_LONG_DOUBLE_IS_BINARY128
#define FP_LONG_DOUBLE_IS_BINARY128 FALSE
#endif /* ifndef FP_LONG_DOUBLE_IS_BINARY128 */

#ifndef FP_LONG_DOUBLE_IS_80BIT_EXTENDED
#define FP_LONG_DOUBLE_IS_80BIT_EXTENDED FALSE
#endif /* ifndef FP_LONG_DOUBLE_IS_80BIT_EXTENDED */

#if FP_LONG_DOUBLE_IS_BINARY64 + \
    FP_LONG_DOUBLE_IS_BINARY128 + \
    FP_LONG_DOUBLE_IS_80BIT_EXTENDED > 1
#error More than one of FP_LONG_DOUBLE_IS_BINARY64 and \
      FP_LONG_DOUBLE_IS_BINARY128 and FP_LONG_DOUBLE_IS_80BIT_EXTENDED is TRUE.
#endif /* FP_LONG_DOUBLE_IS_BINARY64 + FP_LONG_DOUBLE_IS_BINARY128 + ... */

/*
Definitions of fundamental properties for IEEE 754-2008 floating-point types.
The default values for the FPT_FLOAT_* macros reflect the IEEE 754-2008
"binary32" type (aka IEEE 754-1985 "single" format); FPT_DOUBLE_* macros
reflect the IEEE 754-2008 "binary64" type (aka IEEE 754-1985 "double" format).
The FPT_LONG_DOUBLE_* macros can vary widely by target machine, and as
explained above, two popular formats are pre-configured, but additional
formats can also be specified.  Here's a list of the properties of
pre-configured types:

  Property       binary32  binary64    binary128  80-bit extended
  --------       --------  --------    ---------  ---------------
  type              float    double  long double      long double
  nominal size         32        64          128               80
  precision bits       24        53          113               64
  has hidden bit        1         1            1                0

FPT_FLOAT80_* explicitly refers to the 80-bit extended format (which may
or may not correspond to a builtin type).  Likewise FPT_FLOAT128_* explicitly
refers to the binary128 format.
*/

/*
FPT_*_VALUE_BITS is the number of bits in the representation of the
floating-point value.
*/
#ifndef FPT_FLOAT_VALUE_BITS
#define FPT_FLOAT_VALUE_BITS 32 /* IEEE 754-2008 "binary32" format. */
#endif /* ifndef FPT_FLOAT_VALUE_BITS */

#if defined(TARG_SIZEOF_FLOAT)
#if TARG_SIZEOF_FLOAT * CHAR_BIT != FPT_FLOAT_VALUE_BITS
#error float type is mis-configured.
#endif /* TARG_SIZEOF_FLOAT * CHAR_BIT != FPT_FLOAT_VALUE_BITS */
#endif /* defined(TARG_SIZEOF_FLOAT) */

#ifndef FPT_DOUBLE_VALUE_BITS
#define FPT_DOUBLE_VALUE_BITS 64 /* IEEE 754-2008 "binary64" format. */
#endif /* ifndef FPT_DOUBLE_VALUE_BITS */

#if defined(TARG_SIZEOF_DOUBLE)
#if TARG_SIZEOF_DOUBLE * CHAR_BIT != FPT_DOUBLE_VALUE_BITS
#error double type is mis-configured.
#endif /* TARG_SIZEOF_DOUBLE * CHAR_BIT != FPT_DOUBLE_VALUE_BITS */
#endif /* defined(TARG_SIZEOF_DOUBLE) */

#if FP_HAS_LONG_DOUBLE
#ifndef FPT_LONG_DOUBLE_VALUE_BITS
#if FP_LONG_DOUBLE_IS_BINARY64
#define FPT_LONG_DOUBLE_VALUE_BITS 64  /* IEEE 754-2008 "binary64" format. */
#endif  /* FP_LONG_DOUBLE_IS_BINARY64 */
#if FP_LONG_DOUBLE_IS_80BIT_EXTENDED
#define FPT_LONG_DOUBLE_VALUE_BITS 80  /* IEEE 754-2008 80-bit extended. */
#endif /* FP_LONG_DOUBLE_IS_80BIT_EXTENDED */
#if FP_LONG_DOUBLE_IS_BINARY128
#define FPT_LONG_DOUBLE_VALUE_BITS 128  /* IEEE 754-2008 "binary128" format. */
#endif /* FP_LONG_DOUBLE_IS_BINARY128 */
#endif /* ifndef FPT_LONG_DOUBLE_VALUE_BITS */

#if defined(TARG_SIZEOF_LONG_DOUBLE)
#if TARG_SIZEOF_LONG_DOUBLE * CHAR_BIT < FPT_LONG_DOUBLE_VALUE_BITS
#error long double type is mis-configured.
#endif /* TARG_SIZEOF_LONG_DOUBLE * CHAR_BIT < FPT_LONG_DOUBLE_VALUE_BITS */
#endif /* FP_HAS_LONG_DOUBLE */
#endif /* defined(TARG_SIZEOF_LONG_DOUBLE) */

#if FLOAT80_ENABLING_POSSIBLE
#define FPT_FLOAT80_VALUE_BITS 80  /* IEEE 754-2008 80-bit extended. */
#endif /* FLOAT80_ENABLING_POSSIBLE */

#if FLOAT128_ENABLING_POSSIBLE
#define FPT_FLOAT128_VALUE_BITS 128  /* IEEE 754-2008 "binary128" format. */
#endif /* FLOAT128_ENABLING_POSSIBLE */

/*
FPT_*_PRECISION is the number of bits in the fraction of the floating-point
value.
*/
#ifndef FPT_FLOAT_PRECISION
#define FPT_FLOAT_PRECISION 24 /* IEEE 754-2008 "binary32" format. */
#endif /* ifndef FPT_FLOAT_PRECISION */

#ifndef FPT_DOUBLE_PRECISION
#define FPT_DOUBLE_PRECISION 53 /* IEEE 754-2008 "binary64" format. */
#endif /* ifndef FPT_DOUBLE_PRECISION */

#if FP_HAS_LONG_DOUBLE
#ifndef FPT_LONG_DOUBLE_PRECISION
#if FP_LONG_DOUBLE_IS_BINARY64
#define FPT_LONG_DOUBLE_PRECISION 53 /* IEEE 754-2008 "binary64" format. */
#endif /* FP_LONG_DOUBLE_IS_BINARY64 */
#if FP_LONG_DOUBLE_IS_80BIT_EXTENDED
#define FPT_LONG_DOUBLE_PRECISION 64 /* IEEE 754-2008 80-bit extended. */
#endif /* FP_LONG_DOUBLE_IS_80BIT_EXTENDED */
#if FP_LONG_DOUBLE_IS_BINARY128
#define FPT_LONG_DOUBLE_PRECISION 113 /* IEEE 754-2008 "binary128" format. */
#endif /* FP_LONG_DOUBLE_IS_BINARY128 */
#endif /* ifndef FPT_LONG_DOUBLE_PRECISION */
#endif /* FP_HAS_LONG_DOUBLE */

#if FLOAT80_ENABLING_POSSIBLE
#define FPT_FLOAT80_PRECISION 64 /* IEEE 754-2008 80-bit extended. */
#endif /* FLOAT80_ENABLING_POSSIBLE */

#if FLOAT128_ENABLING_POSSIBLE
#define FPT_FLOAT128_PRECISION 113 /* IEEE 754-2008 "binary128" format. */
#endif /* FLOAT128_ENABLING_POSSIBLE */

/*
FPT_*_HAS_HIDDEN is TRUE if the fraction has an implicit 1-bit at the top,
otherwise FALSE.
*/
#ifndef FPT_FLOAT_HAS_HIDDEN
#define FPT_FLOAT_HAS_HIDDEN TRUE
#endif /* ifndef FPT_FLOAT_HAS_HIDDEN */

#ifndef FPT_DOUBLE_HAS_HIDDEN
#define FPT_DOUBLE_HAS_HIDDEN TRUE
#endif /* ifndef FPT_DOUBLE_HAS_HIDDEN */

#if FP_HAS_LONG_DOUBLE
#ifndef FPT_LONG_DOUBLE_HAS_HIDDEN
#if FP_LONG_DOUBLE_IS_BINARY64
#define FPT_LONG_DOUBLE_HAS_HIDDEN TRUE
#endif /* FP_LONG_DOUBLE_IS_BINARY64 */
#if FP_LONG_DOUBLE_IS_80BIT_EXTENDED
#define FPT_LONG_DOUBLE_HAS_HIDDEN FALSE
#endif /* FP_LONG_DOUBLE_IS_80BIT_EXTENDED */
#if FP_LONG_DOUBLE_IS_BINARY128
#define FPT_LONG_DOUBLE_HAS_HIDDEN TRUE
#endif /* FP_LONG_DOUBLE_IS_BINARY128 */
#endif /* ifndef FPT_LONG_DOUBLE_HAS_HIDDEN */

#if !defined(FPT_LONG_DOUBLE_VALUE_BITS) || \
    !defined(FPT_LONG_DOUBLE_HAS_HIDDEN) || \
    !defined(FPT_LONG_DOUBLE_PRECISION)
#error long double floating-point configured incorrectly.
#endif /* !defined(FPT_LONG_DOUBLE_VALUE_BITS) || ... */
#endif /* FP_HAS_LONG_DOUBLE */

#if FLOAT80_ENABLING_POSSIBLE
#define FPT_FLOAT80_HAS_HIDDEN FALSE
#endif /* FLOAT80_ENABLING_POSSIBLE */

#if FLOAT128_ENABLING_POSSIBLE
#define FPT_FLOAT128_HAS_HIDDEN TRUE
#endif /* FLOAT128_ENABLING_POSSIBLE */

/*
The following definitions capture the characteristics of the largest
floating-point type.
*/

#if FLOAT128_ENABLING_POSSIBLE
#define FPT_LARGEST_VALUE_BITS FPT_FLOAT128_VALUE_BITS
#define FPT_LARGEST_PRECISION FPT_FLOAT128_PRECISION
#define FPT_LARGEST_HAS_HIDDEN FPT_FLOAT128_HAS_HIDDEN
#else /* !FLOAT128_ENABLING_POSSIBLE */
#if FP_HAS_LONG_DOUBLE
#define FPT_LARGEST_VALUE_BITS FPT_LONG_DOUBLE_VALUE_BITS
#define FPT_LARGEST_PRECISION FPT_LONG_DOUBLE_PRECISION
#define FPT_LARGEST_HAS_HIDDEN FPT_LONG_DOUBLE_HAS_HIDDEN
#else /* !FP_HAS_LONG_DOUBLE */
#define FPT_LARGEST_VALUE_BITS FPT_DOUBLE_VALUE_BITS
#define FPT_LARGEST_PRECISION FPT_DOUBLE_PRECISION
#define FPT_LARGEST_HAS_HIDDEN FPT_DOUBLE_HAS_HIDDEN
#endif /* FP_HAS_LONG_DOUBLE */
#endif /* FLOAT128_ENABLING_POSSIBLE */

#if FPT_LARGEST_VALUE_BITS < FPT_FLOAT_VALUE_BITS || \
    FPT_LARGEST_VALUE_BITS < FPT_DOUBLE_VALUE_BITS || \
    (FP_HAS_LONG_DOUBLE && \
     (FPT_LARGEST_VALUE_BITS < FPT_LONG_DOUBLE_VALUE_BITS))
#error FPT_LARGEST_VALUE_BITS must reflect size of largest floating-point type.
#endif /* FPT_LARGEST_VALUE_BITS < FPT_FLOAT_VALUE_BITS || ... */

/*
The bigint implementation uses a cache to hold previously computed values of
5^2^n.  The size of this cache is set by the value of the macro
FIVE_TWO_CACHE_SIZE.  Its size should be roughly log2(exp), where exp is the
largest possible exponent of the largest floating-point type.  Making the cache
too large wastes space; making it too small slows down conversions for values
with large exponents.

By default the value of FIVE_TWO_CACHE_SIZE is 12.  That's sufficient for all
three Intel floating-point types.  For larger floating-point types the value
should be increased.

FIVE_TWO_CACHE_SIZE is the size of the cache used by bigint_5_2_n to store
previous results.  Making this value larger makes bigint_pow5 faster, up to
around log2 of the absolute value of the largest exponent to be processed.
The value must be at least 1.
*/

#ifndef FIVE_TWO_CACHE_SIZE
#define FIVE_TWO_CACHE_SIZE 12
#endif /* ifndef FIVE_TWO_CACHE_SIZE */
#if FIVE_TWO_CACHE_SIZE < 1
#error FIVE_TWO_CACHE_SIZE must be at least 1.
#endif /* FIVE_TWO_CACHE_SIZE < 1 */

/*
Macros for bit twiddling.
*/
#define BYTE_SIZE CHAR_BIT
#define BYTE_MAX UCHAR_MAX

#define LAST_BITS(bits) (/*lint --e(506)*/(bits) % BYTE_SIZE ? \
                                                         (bits) % BYTE_SIZE : \
                                                         BYTE_SIZE)
#define MASK_BITS(bits) ((1u << (bits)) - 1)
#define MASK_BIT(pos)   (1u << (pos))
#define BYTE_MASK       MASK_BITS(BYTE_SIZE)

#define HIGH_BYTE_BIT_COUNT(width) \
  /*lint --e(506)*/(width % BYTE_SIZE ? (width % BYTE_SIZE) : BYTE_SIZE)
#define BYTE_COUNT(width) ((width + BYTE_SIZE - 1) / BYTE_SIZE)

#if CHECKING
#define HIGH_BYTE_BITS(width) (unsigned char) \
  (check_assertion(HIGH_BYTE_BIT_COUNT(width) >= 0), \
   /*lint --e(648)*/(~((unsigned)(-1) << HIGH_BYTE_BIT_COUNT(width))))
#define HIGH_BIT(width) \
  (check_assertion(HIGH_BYTE_BIT_COUNT(width) >= 1), \
   (1u << (HIGH_BYTE_BIT_COUNT(width) - 1)))
#else /* !CHECKING */
#define HIGH_BYTE_BITS(width) (unsigned char) \
  /*lint --e(648)*/(~((unsigned)(-1) << HIGH_BYTE_BIT_COUNT(width)))
#define HIGH_BIT(width) (1u << (HIGH_BYTE_BIT_COUNT(width) - 1))
#endif /* CHECKING */

#define BIT_MASK(n) (1u << ((n) % BYTE_SIZE))
#define BIT_AT(base, size, offset) \
  ((size) <= (offset) ? 0 : \
        (*((base) + /*lint --e(835)*/(offset) / BYTE_SIZE) & BIT_MASK(offset)))

/* Compute floor(log10(2^x)) for non-negative x. */
#define PFLOG10_2times(x) (((30103L * (x))) / 100000L)

/* Compute ceil(log10(2^x)) for non-negative x. */
#define PCLOG10_2times(x) (((30103L * (x)) + 100000L - 1) / 100000L)

/* Compute floor(log10(2^x)). */
#define FLOG10_2times(x) (/*lint --e(506)*/((x) < 0) ? \
                                      (-PCLOG10_2times(-(x))) : \
                                       PFLOG10_2times(x))

/* Compute ceil(log10(2^x)). */
#define CLOG10_2times(x) (/*lint --e(506)*/((x) < 0) ? \
                                      (-PFLOG10_2times(-(x))) : \
                                       PCLOG10_2times(x))
/*
log10(2) * x.  Approximation is sufficient, since this is used only to
compute floor(log10(2) * exponent) and exponent is limited to 5 digits or so.
*/
#define LOG10_2times(x) ((30103L * x) / 100000L)


#define FPT_LARGEST_DIGITS      FLOG10_2times(FPT_LARGEST_PRECISION - 1)
#define FPT_LARGEST_MANT_DIG    FPT_LARGEST_PRECISION
#define FPT_LARGEST_EXP_BITS \
  (FPT_LARGEST_VALUE_BITS - FPT_LARGEST_PRECISION - 1 + \
   /*lint --e(835)*/FPT_LARGEST_HAS_HIDDEN - 1)
#define FPT_LARGEST_MAX_EXP     (1 << FPT_LARGEST_EXP_BITS)

/*
MAX_DIGITS is the maximum number of digits that the algorithm will generate.
*/
#define MAX_DIGITS (FPT_LARGEST_DIGITS + 5)

/*
MAX_FRAC_BYTES is the number of bytes needed to hold a copy of the mantissa
of the largest supported floating-point type.
*/
#define MAX_FRAC_BYTES ((FPT_LARGEST_MANT_DIG + CHAR_BIT - 1) / CHAR_BIT)

/*
Flags for special values of floating-point numbers.
*/
enum an_fp_type {
  fpt_invalid,
  fpt_approx,  /* for fast_dec2bin_xxx */
  fpt_number,
  fpt_nan,
  fpt_infinity,
  fpt_overflow,
  fpt_zero,
  fpt_underflow
};

/*
Internally the floating-point software works primarily with broken-down
floating-point and decimal values rather than binary floating-point values and
raw text.  These broken-down values are structs whose fields represent the sign
of the value, the exponent (binary or decimal), the mantissa (binary or text),
and the precision.

There are three different representations for broken-down values:
an_fp_binary, an_fp_decimal, and an_fp_decimal_input.
*/

/*
an_fp_binary objects hold broken-down binary floating-point values.
*/
typedef struct an_fp_binary {
  an_fp_type    type;   /* The type of the stored value. */
  a_boolean     is_negative;
                        /* TRUE for negative values, FALSE for non-negative
                           values. */
  int           exponent;
                        /* Base 2 exponent, with the binary point at the left
                           of frac. */
  unsigned char frac[MAX_FRAC_BYTES + 1];
                        /* The binary mantissa, left justified in a field
                           whose width in bytes is equal to precision.  The
                           array contains one extra byte for the
                           fp_emul_div algorithm that would otherwise
                           exceed the array bound. */
  int           precision;
                        /* Number of bits in the mantissa.  This is determined
                           by the floating-point type itself, which lets us
                           use the same code for float, double, and long
                           double. */
} an_fp_binary;


/*
an_fp_decimal objects hold converted decimal floating-point values.
*/
typedef struct an_fp_decimal {
  a_boolean     is_negative;
                        /* TRUE for negative values, FALSE for non-negative
                           values. */
  int           exponent;
                        /* Base 10 exponent, with the decimal point at the left
                           of digits. */
  char          digits[MAX_DIGITS + 1];
                        /* The decimal mantissa, represented as a
                           null-terminated string of characters '0'-'9'. */
  int           ndigits;
                        /* Number of characters in the digits array. */
} an_fp_decimal;


/*
an_fp_decimal_input objects hold decimal floating-point values split from
input strings.
*/
typedef struct an_fp_decimal_input {
  an_fp_type    type;   /* The type of the stored value. */
  a_boolean     is_negative;
                        /* TRUE for negative values, FALSE for non-negative
                           values. */
  int           exponent;
                        /* Base 10 exponent, with the decimal point at the left
                           of digits. */
  a_const_char  *first_int;
  a_const_char  *last_int;
                        /* [first_int, last_int) designates the sequence of
                           digit characters to the left of the decimal point in
                           the input text, with leading zeros suppressed. */
  a_const_char  *first_frac;
  a_const_char  *last_frac;
                        /* [first_frac, last_frac) designates the sequence of
                           digit characters to the right of the decimal point
                           in the input text, with trailing zeros suppressed,
                           and, if there are no non-zero characters to the left
                           of the decimal point, with leading zeros
                           suppressed. */
  int           precision;
                        /* The number of digit characters to the left and the
                           right of the decimal point in the input sequence,
                           with leading and trailing zeros suppressed, i.e.,
                           (last_int - first_int) + (last_frac - first_frac) */
} an_fp_decimal_input;

/*
Return codes for conversion functions.  Negative codes indicate an error
condition, zero or positive returns indicate success (with non-zero positive
returns indicating some unusual condition).
*/
enum an_fp_return_type {
  fp_ret_invalid = -3,
  fp_ret_too_small = -2,
  fp_ret_not_formatted = -1,  /* Used internally. */
  fp_ret_valid = 0,
  fp_ret_nan = 1,
  fp_ret_pos_infinity = 2,
  fp_ret_neg_infinity = 3,
  fp_ret_overflow = 4,
  fp_ret_underflow = 5
};

/*
Macros to test the return value of the read/write routines.  fp_is_error
indicates an error in input; fp_is_unusual indicates that the conversion
succeeded, but the result may be unexpected (i.e., a NaN, infinity,
overflow, or underflow).
*/
#define fp_is_error(ret) ((ret) < fp_ret_valid)
#define fp_is_unusual(ret) ((ret) > fp_ret_valid)

/*
External conversion functions.
*/

extern void floating_one_time_init(void);

extern an_fp_return_type write_bfloat16(char          *tgt,
                                        int           size,
                                        unsigned char *val);
extern an_fp_return_type write_bfloat16_n(char          *tgt,
                                          int           size,
                                          unsigned char *val,
                                          int           ndigits);
extern an_fp_return_type write_float16(char          *tgt,
                                       int           size,
                                       unsigned char *val);
extern an_fp_return_type write_float16_n(char          *tgt,
                                         int           size,
                                         unsigned char *val,
                                         int           ndigits);
extern an_fp_return_type write_float(char          *tgt,
                                     int           size,
                                     unsigned char *val);
extern an_fp_return_type write_float_n(char          *tgt,
                                       int           size,
                                       unsigned char *val,
                                       int           ndigits);
extern an_fp_return_type write_double(char          *tgt,
                                      int           size,
                                      unsigned char *val);
extern an_fp_return_type write_double_n(char          *tgt,
                                        int           size,
                                        unsigned char *val,
                                        int           ndigits);
extern an_fp_return_type write_long_double(char          *tgt,
                                           int           size,
                                           unsigned char *val);
extern an_fp_return_type write_long_double_n(char          *tgt,
                                             int           size,
                                             unsigned char *val,
                                             int           ndigits);
#if FLOAT80_ENABLING_POSSIBLE
extern an_fp_return_type write_float80(char          *tgt,
                                       int           size,
                                       unsigned char *val);
extern an_fp_return_type write_float80_n(char          *tgt,
                                         int           size,
                                         unsigned char *val,
                                         int           ndigits);
#endif /* FLOAT80_ENABLING_POSSIBLE */
#if FLOAT128_ENABLING_POSSIBLE
extern an_fp_return_type write_float128(char          *tgt,
                                        int           size,
                                        unsigned char *val);
extern an_fp_return_type write_float128_n(char          *tgt,
                                          int           size,
                                          unsigned char *val,
                                          int           ndigits);
#endif /* FLOAT128_ENABLING_POSSIBLE */

extern an_fp_return_type read_float16(unsigned char *val,
                                      a_const_char  *str,
                                      int           len);
extern an_fp_return_type read_bfloat16(unsigned char *val,
                                       a_const_char  *str,
                                       int           len);
extern an_fp_return_type read_float(unsigned char *val,
                                    a_const_char  *str,
                                    int           len);
extern an_fp_return_type read_double(unsigned char *val,
                                     a_const_char  *str,
                                     int           len);
extern an_fp_return_type read_long_double(unsigned char *val,
                                          a_const_char  *str,
                                          int           len);
#if FLOAT80_ENABLING_POSSIBLE
extern an_fp_return_type read_float80(unsigned char *val,
                                      a_const_char  *str,
                                      int           len);
#endif /* FLOAT80_ENABLING_POSSIBLE */
#if FLOAT128_ENABLING_POSSIBLE
extern an_fp_return_type read_float128(unsigned char *val,
                                       a_const_char  *str,
                                       int           len);
#endif /* FLOAT128_ENABLING_POSSIBLE */

#if DEBUG
extern void db_binary_float16(unsigned char *val);
extern void db_binary_float(unsigned char *val);
extern void db_binary_double(unsigned char *val);
extern void db_binary_long_double(unsigned char *val);
#if FLOAT80_ENABLING_POSSIBLE
extern void db_binary_float80(unsigned char *val);
#endif /* FLOAT80_ENABLING_POSSIBLE */
#if FLOAT128_ENABLING_POSSIBLE
extern void db_binary_float128(unsigned char *val);
#endif /* FLOAT128_ENABLING_POSSIBLE */
#endif /* DEBUG */

EXTERN_THREAD a_boolean
                floating_init_called;
                        /* TRUE once floating_init is called. */

/*
This value can be passed as the value of ndigits to the write_*_internal
routines to request the shortest string that correctly rounds to the value,
and must be larger than the largest number of digits that can legitimately
be requested.
*/
#define FP_SHORTEST INT_MAX

/*
a_bigint must be large enough to hold the binary representation of the absolute
value of the largest floating-point value.  Values are stored as an array of
unsigned integral values.  a_bigint_uint and a_bigint_int are unsigned and
signed integral types with at least twice as many bits as will be stored in
each bigint_word.

Note that a_bigint is a data structure with a fixed size, and as such
places a limit on the maximum value that can be represented.  The configuration
below uses the size of the largest floating-point type to come up with
an appropriately-sized a_bigint, but it's possible to specify a long string
of text digits that won't fit in whatever fixed size is chosen.  This can
introduce conversions that are off by a single bit.  A larger buffer
(i.e., BIGINT_WORDS) makes this possibility smaller.

The value of BIGINT_WORD_BYTES determines the values of these macros and the
types named by the three typedefs.

BIGINT_WORD_BITS is the number of bits to be stored in each array element.

BIGINT_WORD_MASK is used to extract the low order BIGINT_WORD_BITS from a
value for storage in the internal array.

BIGINT_WORD_MAX is the largest value that can be stored in an array element.

BIGINT_WORD_STORAGE_BYTES is the number of bytes that each word of storage
occupies; it is needed for memset and memcpy.

BIGINT_MAX_BITS is the size of the internal array in bits.
BIGINT_MAX_DIGITS is the size of the internal array in decimal digits.
BIGINT_WORDS is the size of the internal array in words.

a_bigint_word is an unsigned integral type whose size is at least
BIGINT_WORD_BITS.
*/

#define BIGINT_WORD_BITS (int)(BIGINT_WORD_BYTES * BYTE_SIZE)
#define BIGINT_WORD_MASK (((a_bigint_uint)1 << BIGINT_WORD_BITS) - 1)
#define BIGINT_WORD_MAX (a_bigint_uint)BIGINT_WORD_MASK
#define BIGINT_WORD_STORAGE_BYTES sizeof(a_bigint_word)

#define BIGINT_MAX_BITS (FPT_LARGEST_MAX_EXP + 2 * FPT_LARGEST_MANT_DIG)
#define BIGINT_MAX_EXP PFLOG10_2times(BIGINT_MAX_BITS)
#define BIGINT_WORDS ((BIGINT_MAX_BITS + BIGINT_WORD_BITS - 1) / \
                                                              BIGINT_WORD_BITS)

/*
a_bigint holds large non-negative integer values.
*/
typedef struct a_bigint *a_bigint_ptr;
typedef struct a_bigint {
  a_bigint_ptr  next;   /* Link, used by the free list. */
  a_bigint_word words[BIGINT_WORDS];
                        /* The value, little-endian. */
  unsigned int  num_words;
                        /* Number of words in representation of the value.
                           0 when the value is zero. */
} a_bigint;

/*
NUM_BIGINTS is the number of statically allocated a_bigint objects available
to the conversion routines.  bin2dec requires 4, dec2bin requires 5.  These
never run simultaneously, so 5 suffices for both.  Also need 3 more for
bigint_mult_pow5.
*/
#ifndef NUM_BIGINTS
#define NUM_BIGINTS (5 + 3)
#endif /* ifndef NUM_BIGINTS */

/* Conditionally close the "edg" namespace. */
END_EDG_NAMESPACE

#endif /* !USE_HOST_FP_CONVERSION_ROUTINES || (USE_FLOAT128...) */

#endif  /* ifndef FLOATING_H */

