

static const int M_EOF = (32752+0) * (1);
static const int M_maxblk = (2+0) * (1);
static const int M_mb_wr = (eSCALE/(144+16));
static const int M_mb_mw = (704+1) * (1);
static const int M_cfl0 = (0+1) * (1);
static const int M_cfl1 = (3888+1) * (1);
static const int M_cfl2 = (31+1) * (1);
static const int M_freq_half = (31744+0) * (1);
static const int M_freq_sign = (11232+0) * (1);
static const int M_lsb0 = (91+1) * (1);
static const int M_lsb1 = (236+1) * (1);
static const int M_lsb2 = (136+1) * (1);
static const int M_lsb3 = (250+1) * (1);
static const int M_lsb4 = (110+1) * (1);
static const int M_lsb5 = (3409+1) * (1);
static const int M_lsb6 = (0+1) * (1);
static const int M_lsb7 = (0+1) * (1);
static const int M_mid_div1 = (12+2) * (1);
static const int M_mid_div2 = (3+2) * (1);
static const int M_mid0 = (0+1) * (1);
static const int M_mid1 = (1144+1) * (1);
static const int M_mid2 = (384+1) * (1);



struct M_T {

  
  void M_Init( void ) {
  
  
  }
  void M_Quit( void ) {
  
  }
};
