#define _FILE_OFFSET_BITS 64

// Every system header the whole program needs, in one place: coder0 and the
// transformer are one translation unit, and the transformer's own sources
// (tf/*.inc) carry no #include <...> of their own.
#include <cassert>
#include <cmath>
#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>     // clock_gettime, for progress.inc's monotonic clock

#include <algorithm>
#include <initializer_list>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

// Intel SSE/AVX intrinsics: the denormal microcode fix below, and the
// transformer kernels (AVX2/FMA/F16C, all present in -march=haswell).
#if defined(__SSE3__)||defined(__x86_64__)||defined(_M_X64)
#include <xmmintrin.h>
#include <pmmintrin.h>   // _MM_SET_DENORMALS_ZERO_MODE (gcc puts it here)
#include <immintrin.h>
#endif
#if defined(__linux__)
#include <sys/mman.h>    // arena_build's hugepage allocation
#endif

typedef uint16_t word;
typedef uint32_t uint;
typedef uint8_t byte;
typedef uint64_t qword;

typedef float*__restrict prfloat;
typedef const float*__restrict cprfloat;

#ifdef __GNUC__
#define INLINE __attribute__((always_inline))
#define NOINLINE __attribute__((noinline))
#define ALIGN(n) __attribute__((aligned(n)))
#define restrict __restrict
#else
#define INLINE __forceinline
#define NOINLINE __declspec(noinline)
#define ALIGN(n) __declspec(align(n))
#endif

#define AlignUp(x, r) ((x)+((r)-1))/(r)*(r)

uint flen(FILE* f) {
  fseek(f, 0, SEEK_END);
  uint len = ftell(f);
  fseek(f, 0, SEEK_SET);
  return len;
}

#include "sh_v2f.inc"
#include "MOD/sh_model_h.inc"

#include "ppmd2.hpp"

#include "utils.inc"

#include "progress.inc"

#include "transformer.inc"

static const uint CNUM = 256;

#include "newton.inc"

char cmap[CNUM];

int ppmd_order = 9;
int ppmd_memory = 6284; //1000;

// Searched in order when no weights file is given on the command line.
static const char* tf_weights_paths[] = {
  "6m-q4-fp32.tfwc2",
  "models/6m-q4-fp32.tfwc2",
  0
};

static const char* find_weights(const char* given) {
  const char* const one[] = { given, 0 };
  const char* const* list = given ? one : tf_weights_paths;
  for( int i = 0; list[i]; i++ ) {
    FILE* f = fopen(list[i], "rb");
    if( f ) {
      fclose(f);
      return list[i];
    }
  }
  return 0;   // also the "ppmd only" switch: name a file that does not exist
}

// The null device asks for a freshly initialized model rather than a file.
// It has to be recognized by name: on Windows fopen("nul") SUCCEEDS, so the
// loader would otherwise read an empty file and die, and on Linux
// "/dev/null" does the same.
static int is_null_device(const char* s) {
  static const char* names[] = { "nul", "nul:", "/dev/null", 0 };
  for( int i = 0; names[i]; i++ ) {
    int j = 0;
    for( ; s[j] && names[i][j]; j++ ) {
      int a = s[j], b = names[i][j];
      if( a>='A' && a<='Z' ) a += 'a'-'A';
      if( a!=b ) break;
    }
    if( !s[j] && !names[i][j] )
      return 1;
  }
  return 0;
}

ALIGN(64) Transformer tf;
ALIGN(64) Rangecoder rc;
ALIGN(64) UnifiedModel<Transformer> M;
ALIGN(64) BinaryMixer mixer[32];

// ---------------------------------------------------------------------------
// "gN <input> <output>": generate N bytes instead of coding a file.
//
// The input is a prompt.  It gets encoded to the output exactly as "c" would
// encode it - that is what feeds PPMD, the model and the mixer - and then the
// coder is turned round: the range decoder is pointed at a file of random
// bytes, the output is rewound to nothing, and N symbols are decoded into it.
//
// Decoding random bits IS sampling.  An arithmetic decoder maps a uniformly
// distributed number onto the model's cumulative distribution, so a symbol
// comes out with exactly the probability the model gave it; each one is then
// fed back through the same Update calls the coder uses, which makes this
// autoregressive inference with the input as the prompt.  The generated bytes
// can only be ones the prompt used - the alphabet comes from it.
// ---------------------------------------------------------------------------

// The bit source to decode from: n random bytes, plus slack, because the
// decoder primes itself with four and a model that is completely unsure can
// spend most of a byte per byte produced.  The generator is xorshift64* rather
// than rand() so that a given seed gives the same data on every platform;
// GEN_SEED picks a different sample.
#ifndef GEN_SEED
#define GEN_SEED 0x9E3779B97F4A7C15ULL
#endif
static FILE* make_random_file(const char* path, uint n) {
  FILE* t = fopen(path, "wb+");
  if( !t )
    return 0;
  qword s = GEN_SEED;
  for( uint i = 0; i<n+16; i++ ) {
    s ^= s>>12;
    s ^= s<<25;
    s ^= s>>27;
    putc(int(byte((s*0x2545F4914F6CDD1DULL)>>32)), t);
  }
  fseek(t, 0, SEEK_SET);
  return t;
}

int main(int argc, char** argv) {
  if( argc<4 ) {
    fprintf(stderr,
      "usage: coder0 c|d|gN <input> <output> [weights_in] [weights_out]\n"
      "  c / d        compress / decompress <input> to <output>\n"
      "  gN           generate N bytes: code <input> as a prompt, then sample\n"
      "               N bytes from the model into <output>, which ends up\n"
      "               holding the generated data alone\n"
      "  weights_in   the model to start from; without it, 6m-q4-fp32.tfwc2\n"
      "               then models/6m-q4-fp32.tfwc2.  \"nul\" (or /dev/null)\n"
      "               starts from a freshly initialized model instead of a\n"
      "               file.  Naming a file that does not exist runs PPMD\n"
      "               alone.\n"
      "  weights_out  write the model back out when the file is done, so a\n"
      "               later run can start from it (needs TF_FP32=1; with\n"
      "               TF_TRAIN it is the trained model that gets written).\n");
    return 1;
  }
#if defined(__SSE3__)||defined(__x86_64__)||defined(_M_X64)
  _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
  _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
#endif

  uint f_DEC = (argv[1][0]=='d'), i, c, code, low, total;
  uint n_chars = 0, freq[CNUM], f_len, f_pos;

  // "gN": code the prompt as an encoder would, then sample N bytes
  const uint f_GEN = (argv[1][0]=='g');
  const uint g_len = f_GEN ? uint(strtoul(argv[1]+1, 0, 10)) : 0;
  if( f_GEN && g_len==0 ) {
    fprintf(stderr, "coder0: \"g\" needs a byte count, as in g1000\n");
    return 1;
  }

  FILE* f = fopen(argv[2], "rb");
  if( !f )
    return 2;
  FILE* g = fopen(argv[3], "wb");
  if( !g )
    return 3;

  for( i = 0; i<CNUM; i++ ) {
    cmap[i] = 0;
    freq[i] = 1;
  }

  if( f_DEC==0 ) {
    f_len = flen(f);
    fwrite(&f_len, 1, sizeof(f_len), g);
    for( f_pos = 0; f_pos<f_len; f_pos++ )
      cmap[getc(f)] = 1;
    fseek(f, 0, SEEK_SET);
    rc.StartEncode(g);
  } else {
    fread(&f_len, 1, sizeof(f_len), f);
    rc.StartDecode(f);
  }

  for( n_chars = 0, i = 0; i<CNUM; i++ )
    n_chars += (cmap[i] = rc.rc_BProcess(SCALE/2, cmap[i]));

  // The prompt is what the models are built from and where the alphabet comes
  // from, so there has to be one.
  if( f_GEN && n_chars==0 ) {
    fprintf(stderr, "coder0: nothing to generate from, %s is empty\n", argv[2]);
    return 6;
  }
  const uint n_run = f_len+g_len;   // prompt, then generated

  // The transformer replaces the LSTM.  If the weights are missing or the
  // alphabet does not fit the model's 205 tokens the model stays disabled and
  // its input to the mixer is PPMD's own distribution, which still round-trips
  // (just without the transformer's contribution).
  const char* warg = argc>4 ? argv[4] : 0;
#if !TF_LOAD_WEIGHTS
  warg = "nul";  // the build-time switch makes the same request as the name
#endif
  if( warg && is_null_device(warg) ) {
    // no file: the model is initialized in memory instead (weights_init.inc)
    fprintf(stderr, "coder0: transformer weights initialized from seed %llu\n",
            (unsigned long long)TF_INIT_SEED);
    if( !tf.Init(0, cmap, n_run) )
      fprintf(stderr, "coder0: transformer disabled "
                      "(alphabet does not fit the model)\n");
  } else {
    const char* wpath = find_weights(warg);
    if( !wpath || !tf.Init(wpath, cmap, n_run) )
      fprintf(stderr, "coder0: transformer disabled (%s)\n",
              wpath ? "alphabet does not fit the model" : "no weights file");
  }
#if TF_TRAIN>=3
  fprintf(stderr, "coder0: whole transformer trained online (%d params, "
                  "lr %g, batch %d)\n", 5897145,
          TF_FULL_LR_X1000000/1000000.0, (int)TF_BATCH);
#elif TF_TRAIN
  fprintf(stderr, "coder0: transformer output layer trained online\n");
#endif

  M.Init(ppmd_order, ppmd_memory, cmap, &tf, n_run);

  for( uint m_idx = 0; m_idx<32; ++m_idx )
    mixer[m_idx].Init();

  uint history = 0;

  // written before the loop so a run that cannot make one fails early
  char rnd_path[1024];
  FILE* rnd = 0;
  if( f_GEN ) {
    snprintf(rnd_path, sizeof(rnd_path), "%s.rnd", argv[3]);
    rnd = make_random_file(rnd_path, g_len);
    if( !rnd ) {
      fprintf(stderr, "coder0: cannot write %s\n", rnd_path);
      return 7;
    }
  }

  Progress prog;
  prog.Init(n_run);

  for( f_pos = 0; f_pos<n_run; f_pos++ ) {
    if( f_GEN && f_pos==f_len ) {
      // The prompt is in.  Flush the encoder, drop what it wrote - the output
      // is for the generated data - and read from the random file instead.
      rc.FinishEncode();
      fclose(g);
      g = fopen(argv[3], "wb");     // rewinds to 0 and truncates in one step
      if( !g )
        return 3;
      rc.StartDecode(rnd);
      f_DEC = 1;
    }

    if( (f_pos&prog.mask)==0 )
      prog.Tick(f_pos);

    uint ctx = history&31;
    mixer[ctx].Mix(M.tf_probs_, M.ppmd_probs_, cmap);

    // Final frequency calculation with safety bounds
    total = 0;
    float weight = 0.00f;
    for( i = 0; i<CNUM; i++ ) {
      if( cmap[i] ) {
        float p = (1.0f-weight)*mixer[ctx].probs_[i]+weight*M.ppmd_probs_[i];
        freq[i] = (uint)(p*SCALE);
        if( freq[i]<1 )
          freq[i] = 1;
      } else
        freq[i] = 0;
      total += freq[i];
    }

    // Renormalize to ensure sum <= SCALE
    if( total>SCALE ) {
      uint new_total = 0;
      for( i = 0; i<CNUM; i++ ) {
        if( cmap[i] ) {
          freq[i] = (uint)((qword)freq[i]*(SCALE-n_chars)/total)+1;
        }
        new_total += freq[i];
      }
      total = new_total;
    }

    if( f_DEC==0 ) {
      c = getc(f);
      for( low = 0, i = 0; i<c; i++ )
        low += freq[i];
      rc.rc_Process(low, freq[c], total);
    } else {
      code = rc.rc_GetFreq(total);
      for( c = 0, low = 0; low+freq[c]<=code; c++ )
        low += freq[c];
      rc.rc_Process(low, freq[c], total);
      putc(c, g);
    }

    uint bit = (c>' ');
    history = (history<<1)|bit;

    M.UpdatePPMD(c);
    M.UpdateTransformer(c);
    mixer[ctx].Update(c);
  }

  if( f_DEC==0 )
    rc.FinishEncode();
  prog.Done(n_run);
  fclose(g);
  fclose(f);
  if( rnd ) {
    fclose(rnd);
    remove(rnd_path);
    fprintf(stderr, "coder0: generated %u bytes into %s\n", g_len, argv[3]);
  }

  // The model both sides end with is the same, so either can write it out;
  // saving from both and comparing the files is a check that they agree.
  if( argc>5 && tf.Ready() ) {
    if( tf.SaveWeights(argv[5]) )
      fprintf(stderr, "coder0: wrote the final model to %s\n", argv[5]);
    else
      return 4;
  }

  return 0;
}
