################################################################################
# ROSE (C/C++ support) built from source with the open-source EDG front end.
#
#   make -j$(nproc)     build build/lib/librose.so and build/bin/<tools>
#   make check          run the translator tests in tests/
#   make clean          remove the build directory
#
# Windows (cross-compiled with MinGW-w64; Boost built for MinGW-w64, see README.md):
#   make B=build-win CXX=x86_64-w64-mingw32-g++-posix BOOST_ROOT=<boost> -j$(nproc)
#   make B=build-win CXX=x86_64-w64-mingw32-g++-posix BOOST_ROOT=<boost> package
#
# Sources:
#   rose/      subset of ROSE 2.18.0     https://github.com/llnl/rose      (BSD-3)
#   edg/       EDG C/C++ front end 7.0   https://github.com/edgcpp/compiler (Apache-2.0 WITH LLVM-exception)
#   edg2sage/  new EDG IL -> ROSE Sage III AST translation (replaces ROSE's unreleased EDG/Sage connection)
#   tools/     translators built against librose
#
# Requirements: GNU make, g++ (C++14), flex, bison, zlib and the Boost libraries
# chrono date_time filesystem iostreams program_options random regex system
# thread wave serialization (e.g. "apt install libboost-all-dev flex bison").
################################################################################

ROSE_SRC := rose
EDG_SRC  := edg
CONN_SRC := edg2sage
TOOL_SRC := tools
B        := build

COMMA    := ,
EMPTY    :=
SPACE    := $(EMPTY) $(EMPTY)

CXX      ?= g++
FLEX     ?= flex
BISON    ?= bison
AR       ?= ar
OPT      ?= -O2

# The system the translators are built for: Windows when CXX is a MinGW-w64 compiler.
TARGET := $(shell $(CXX) -dumpmachine)
ifneq ($(findstring mingw,$(TARGET)),)
WINDOWS := 1
endif

# Programs that run during the build (ROSETTA's IR generator, EDG's error table generator) are
# compiled with HOST_CXX, and with the host's Boost (HOST_BOOST_ROOT) when cross-compiling.
ifdef WINDOWS
HOST_CXX ?= g++
ifeq ($(origin AR),default)
AR := $(TARGET)-ar
endif
else
HOST_CXX ?= $(CXX)
endif
ifneq ($(HOST_CXX),$(CXX))
CROSS := 1
endif

BOOST_ROOT ?=
HOST_BOOST_ROOT ?= $(if $(CROSS),,$(BOOST_ROOT))
ifneq ($(BOOST_ROOT),)
BOOST_CPPFLAGS := -isystem $(BOOST_ROOT)/include
BOOST_LDFLAGS  := -L$(BOOST_ROOT)/lib $(if $(WINDOWS),,-Wl$(COMMA)-rpath$(COMMA)$(BOOST_ROOT)/lib)
endif
ifneq ($(HOST_BOOST_ROOT),)
HOST_BOOST_CPPFLAGS := -isystem $(HOST_BOOST_ROOT)/include
HOST_BOOST_LDFLAGS  := -L$(HOST_BOOST_ROOT)/lib -Wl,-rpath,$(HOST_BOOST_ROOT)/lib
endif
BOOST_LIBS := -lboost_date_time -lboost_filesystem -lboost_iostreams -lboost_program_options \
              -lboost_random -lboost_regex -lboost_system -lboost_wave -lboost_chrono \
              -lboost_thread -lboost_atomic -lboost_serialization
HOST_SYS_LIBS := -lz -ldl -lrt -pthread
ifdef WINDOWS
SYS_LIBS := -lz -lshlwapi -lws2_32 -lbcrypt -lpsapi -pthread
else
SYS_LIBS := $(HOST_SYS_LIBS)
endif

# The backend compilers: they compile the unparsed code, and the build takes their version,
# predefined macros and system include directories from them.  The translators run them as
# BACKEND_CC_COMMAND and BACKEND_CXX_COMMAND (the Windows build runs gcc and g++ from the PATH).
ifdef WINDOWS
BACKEND_CC  ?= $(subst g++,gcc,$(CXX))
BACKEND_CC_COMMAND  ?= gcc
BACKEND_CXX_COMMAND ?= g++
else
BACKEND_CC  ?= gcc
endif
BACKEND_CXX ?= $(CXX)
ifndef BACKEND_CC_COMMAND
BACKEND_CC_COMMAND := $(shell command -v $(BACKEND_CC))
endif
ifndef BACKEND_CXX_COMMAND
BACKEND_CXX_COMMAND := $(shell command -v $(BACKEND_CXX))
endif

include rose-sources.mk

# A literal '#' usable inside $(shell ...) with all GNU make versions
HASH := \#

ROSE_VERSION := $(shell cat $(ROSE_SRC)/ROSE_VERSION)
ROSE_VERSION_NUMBER := $(shell cat $(ROSE_SRC)/config/SCM_DATE)
EDG_VERSION  := $(shell sed -n 's/^$(HASH)define VERSION_NUMBER "\([0-9.]*\)".*/\1/p' $(EDG_SRC)/src/version.h)

# "make V=1" shows the full compiler command lines
ifeq ($(V),1)
Q :=
msg = @true
else
Q := @
msg = @printf '  %-8s %s\n' $(1) $(2)
endif

GEN  := $(B)/gen
OBJ  := $(B)/obj
SAGE_GEN := $(GEN)/src/frontend/SageIII

################################################################################
# Compiler flags
################################################################################

ROSE_DEFS := -DBOOST_BIND_GLOBAL_PLACEHOLDERS -DROSE_ASSERTION_BEHAVIOR=ROSE_ASSERTION_EXIT \
             -D_GLIBCXX_USE_CXX11_ABI=1 -Ddisc_union=union
ROSE_INCFLAGS := $(ROSE_DEFS) -I$(GEN) -I$(SAGE_GEN) -I$(SAGE_GEN)/astFileIO -I$(GEN)/src \
                 $(addprefix -I$(ROSE_SRC)/,$(ROSE_INCDIRS))
# Windows: no -fPIC (all code is position independent), COFF objects with more than 32768
# sections (the IR classes generated by ROSETTA), and the portability layer in win32/ (see
# win32/rose_mingw.h; $(GEN)/win32 holds the patched copies of ROSE sources, Sawyer.h among them).
ifdef WINDOWS
TARGET_CXXFLAGS := -Wa,-mbig-obj
TARGET_CPPFLAGS := -I$(GEN)/win32 -Iwin32/include -include win32/rose_mingw.h -DBOOST_STACKTRACE_USE_NOOP
else
TARGET_CXXFLAGS := -fPIC
endif
ROSE_CPPFLAGS := $(TARGET_CPPFLAGS) $(ROSE_INCFLAGS) $(BOOST_CPPFLAGS)
ROSE_CXXFLAGS := -std=c++14 $(OPT) $(TARGET_CXXFLAGS) -pthread -w
HOST_CPPFLAGS := $(ROSE_INCFLAGS) $(HOST_BOOST_CPPFLAGS)
HOST_CXXFLAGS := -std=c++14 $(OPT) -pthread -w

# EDG is configured as a callable library ("source analysis" configuration: no IL lowering, no
# EDG back end; the IL is handed to edg2sage's back_end() routine), see edg2sage/edgconfig/.
# The target configuration follows the backend compiler (x86_64 Linux, or Windows with MinGW-w64).
EDG_CONFIG   := $(CONN_SRC)/edgconfig/edg_config.h
EDG_TARGET_DEFS := $(if $(findstring mingw,$(shell $(BACKEND_CXX) -dumpmachine)),-DEDG2SAGE_TARGET_MINGW)
EDG_CPPFLAGS := -DUSE_CMAKE_DEFINES $(EDG_TARGET_DEFS) -include $(EDG_CONFIG) -I$(CONN_SRC)/edgconfig \
                -I$(GEN)/edg -I$(EDG_SRC)/src
EDG_CXXFLAGS := -x c++ -std=c++14 $(OPT) $(TARGET_CXXFLAGS) -fno-rtti -w

################################################################################
# Top-level targets
################################################################################

TOOLS := identityTranslator dotGenerator
ifdef WINDOWS
EXE := .exe
# A static library: a DLL cannot export more than 65535 symbols.
LIBROSE := $(B)/lib/librose.a
else
LIBROSE := $(B)/lib/librose.so
endif
TOOL_PROGS := $(patsubst %,$(B)/bin/%$(EXE),$(TOOLS))

all: $(TOOL_PROGS) $(B)/edg-base/lib/predefined_macros.txt
.PHONY: all check clean rosetta package

clean:
	rm -rf $(B)

################################################################################
# Configuration headers (what ROSE's configure/CMake step would produce)
################################################################################

CXX_PATH := $(BACKEND_CXX_COMMAND)
CC_PATH  := $(BACKEND_CC_COMMAND)
# The GNU version (major minor patch) of a compiler
gnu_version = $(shell echo | $(1) -dM -E -x c - 2>/dev/null | awk '$$2 == "__GNUC__" {a = $$3} \
                $$2 == "__GNUC_MINOR__" {b = $$3} $$2 == "__GNUC_PATCHLEVEL__" {c = $$3} END {print a, b, c}')
CXX_VER  := $(call gnu_version,$(BACKEND_CXX))
CC_VER   := $(call gnu_version,$(BACKEND_CC))
# The backend compilers' system include directories
sys_inc_dirs = $(shell echo | $(1) -x$(2) -E -v - 2>&1 | sed -n '/^$(HASH)include <...> search starts here:/,/^End of search list/p' | \
                 sed -n 's/^ \(.*\)/\1/p')
CXX_SYS_INC_DIRS := $(call sys_inc_dirs,$(BACKEND_CXX),c++)
C_SYS_INC_DIRS   := $(call sys_inc_dirs,$(BACKEND_CC),c)
# ... as C initializer lists ("dir1", "dir2", ...).  The Windows build ships copies of them under
# $(B)/include/edg (relative names are relative to <prefix>/include/edg).
ifdef WINDOWS
SYS_INCLUDES_STAMP := $(B)/include/edg/stamp
stage_sys_includes = sh scripts/stage-sys-includes.sh $(1) $(B)/include/edg $(CXX_SYS_INC_DIRS) -- $(C_SYS_INC_DIRS)
CXX_INCLUDE_DIRS := $(shell $(call stage_sys_includes) | sed -n 1p)
C_INCLUDE_DIRS   := $(shell $(call stage_sys_includes) | sed -n 2p)
all: $(SYS_INCLUDES_STAMP)
$(SYS_INCLUDES_STAMP): scripts/stage-sys-includes.sh
	$(call msg,STAGE,$(@D))
	$(Q)$(call stage_sys_includes,--copy) > /dev/null
	$(Q)touch $@
else
c_string_list = $(subst $(SPACE),$(COMMA) ,$(strip $(patsubst %,"%",$(1))))
CXX_INCLUDE_DIRS := $(call c_string_list,$(CXX_SYS_INC_DIRS))
C_INCLUDE_DIRS   := $(call c_string_list,$(C_SYS_INC_DIRS))
endif
BOOST_VERSION := $(shell printf '$(HASH)include <boost/version.hpp>\nBOOST_VERSION\n' | \
                   $(CXX) $(BOOST_CPPFLAGS) -E -P -x c++ - 2>/dev/null | tail -1 | \
                   awk '{printf "%d.%d.%d", $$1/100000, $$1/100%1000, $$1%100}')

CONFIG_SUBST = sed -e 's|@ROSE_VERSION@|$(ROSE_VERSION)|g' \
  -e 's|@ROSE_VERSION_NUMBER@|$(ROSE_VERSION_NUMBER)|g' \
  -e 's|@BOOST_VERSION@|$(BOOST_VERSION)|g' \
  -e 's|@EDG_MAJOR@|$(word 1,$(subst ., ,$(EDG_VERSION)))|g' \
  -e 's|@EDG_MINOR@|$(word 2,$(subst ., ,$(EDG_VERSION)))|g' \
  -e 's|@BUILD_DIR@|$(abspath $(B))|g' \
  -e 's|@ROSE_SRC_DIR@|$(abspath $(ROSE_SRC))|g' \
  -e 's|@BUILD_DATE@|$(shell date -u +%Y-%m-%d)|g' \
  -e 's|@CXX_PATH@|$(CXX_PATH)|g' -e 's|@CXX_NAME@|$(notdir $(CXX_PATH))|g' \
  -e 's|@CXX_MAJOR@|$(word 1,$(CXX_VER))|g' -e 's|@CXX_MINOR@|$(word 2,$(CXX_VER) 0)|g' \
  -e 's|@CXX_PATCH@|$(word 3,$(CXX_VER) 0 0)|g' \
  -e 's|@CC_PATH@|$(CC_PATH)|g' -e 's|@CC_NAME@|$(notdir $(CC_PATH))|g' \
  -e 's|@CC_MAJOR@|$(word 1,$(CC_VER))|g' -e 's|@CC_MINOR@|$(word 2,$(CC_VER) 0)|g' \
  -e 's|@CC_PATCH@|$(word 3,$(CC_VER) 0 0)|g' \
  -e 's|@CXX_INCLUDE_DIRS@|$(CXX_INCLUDE_DIRS)|g' \
  -e 's|@C_INCLUDE_DIRS@|$(C_INCLUDE_DIRS)|g' \
  -e 's|@BUILD_OS@|$(if $(WINDOWS),mingw32,linux)|g'

# The generated files are only replaced when their content changes (avoids needless rebuilds).
define config_file
	@mkdir -p $(@D)
	$(Q)$(CONFIG_SUBST) $< > $@.tmp
	$(Q)if cmp -s $@.tmp $@; then rm $@.tmp; else mv $@.tmp $@; fi
endef
$(GEN)/rose_config.h: config/rose_config.h.in Makefile
	$(config_file)
$(GEN)/rosePublicConfig.h: config/rosePublicConfig.h.in Makefile
	$(config_file)
$(GEN)/src/util/rose_paths.C: config/rose_paths.C.in Makefile
	$(config_file)
$(GEN)/src/Rose/CommandLine/LicenseString.h: $(ROSE_SRC)/src/Rose/CommandLine/LicenseString.pre
	@mkdir -p $(@D)
	cp $< $@

# Windows: ROSE sources (under rose/src) that are used through copies with the changes in
# win32/patches/<name>.sed (written to $(GEN)/win32 by win32/patch-source.sh)
ifdef WINDOWS
WIN32_PATCHED := Sawyer/Sawyer.h Sawyer/Sawyer.C Sawyer/Message.C Rose/StringUtility/NumberToString.C \
                 frontend/SageIII/sage_support/sage_support.C roseSupport/utility_functions.C
define win32_patch_rule
$(GEN)/win32/$(1): $(ROSE_SRC)/src/$(1) win32/patches/$(notdir $(1)).sed win32/patch-source.sh
	$$(call msg,PATCH,$$@)
	$$(Q)sh win32/patch-source.sh $$< win32/patches/$(notdir $(1)).sed $$@
endef
$(foreach f,$(WIN32_PATCHED),$(eval $(call win32_patch_rule,$(f))))
endif

CONFIG_HEADERS := $(GEN)/rose_config.h $(GEN)/rosePublicConfig.h $(GEN)/src/Rose/CommandLine/LicenseString.h \
                  $(addprefix $(GEN)/win32/,$(filter %.h,$(WIN32_PATCHED)))

################################################################################
# ROSETTA: build the IR generator and generate the Sage III IR classes
################################################################################

# Windows: the portability layer's sources (win32/*.C: POSIX functions missing from MinGW-w64, and
# processSupport.C, which replaces ROSE's fork/exec-based one), and the patched ROSE sources;
# WIN32_REPLACED are the ROSE sources they replace.
ifdef WINDOWS
WIN32_PATCHED_SRCS := $(filter %.C,$(WIN32_PATCHED))
WIN32_REPLACED := src/util/processSupport.C $(addprefix src/,$(WIN32_PATCHED_SRCS))
WIN32_OBJS := $(patsubst win32/%.C,$(OBJ)/win32/%.o,$(wildcard win32/*.C)) \
              $(patsubst %.C,$(OBJ)/gen/win32/%.o,$(WIN32_PATCHED_SRCS))
endif
ROSE_UTIL_OBJS := $(patsubst %.C,$(OBJ)/rose/%.o,$(filter-out $(WIN32_REPLACED),$(ROSE_UTIL_SRCS))) \
                  $(WIN32_OBJS) $(OBJ)/gen/src/util/rose_paths.o
# ROSE sources whose Windows code uses the Windows API without including <windows.h>
ifdef WINDOWS
WIN32_API_SRCS := src/util/stringSupport/FileNameClassifier.C
$(patsubst %.C,$(OBJ)/rose/%.o,$(WIN32_API_SRCS)): ROSE_CPPFLAGS += -include win32/windows_api.h
# Sources that convert pointers to (unsigned) long, which is 32 bits on Windows: the AST file I/O
# (where the "pointers" are small indices), DOT node names and hash values, and the OpenAnalysis
# handles (which therefore do not work on Windows).  -fpermissive makes these casts warnings.
WIN32_LP64_OBJS := $(addprefix $(OBJ)/gen/src/frontend/SageIII/,AST_FILE_IO.o StorageClasses.o) \
  $(addprefix $(OBJ)/rose/src/midend/programAnalysis/,OAWrap/SAGE2OA.o \
    VirtualFunctionAnalysis/IntraProcAliasAnalysis.o dataflowAnalysis/ReachingDefinitionFacade.o \
    genericDataflow/simpleAnalyses/nodeConstAnalysis.o staticInterproceduralSlicing/ControlFlowGraph.o)
$(WIN32_LP64_OBJS): ROSE_CXXFLAGS += -fpermissive
endif
ROSETTA_OBJS   := $(patsubst %.C,$(OBJ)/rose/%.o,$(ROSETTA_SRCS))

# The programs run during the build; cross builds compile them separately for the build host.
ifdef CROSS
HOST_OBJ := $(B)/host/obj
HOST_BIN := $(B)/host/bin
HOST_ROSETTA_OBJS := $(patsubst %.C,$(HOST_OBJ)/rose/%.o,$(ROSETTA_SRCS) $(ROSE_UTIL_SRCS)) \
                     $(HOST_OBJ)/gen/src/util/rose_paths.o
else
HOST_OBJ := $(OBJ)
HOST_BIN := $(B)/bin
HOST_ROSETTA_OBJS := $(ROSETTA_OBJS) $(ROSE_UTIL_OBJS)
endif

$(HOST_BIN)/CxxGrammarMetaProgram: $(HOST_ROSETTA_OBJS)
	$(call msg,LINK,$@)
	@mkdir -p $(@D)
	$(Q)$(HOST_CXX) -pthread -o $@ $^ $(HOST_BOOST_LDFLAGS) $(BOOST_LIBS) $(HOST_SYS_LIBS)

# ROSETTA reads ../Grammar/* relative to its working directory and writes into the given directory.
# Some per-class headers are only generated for binary analysis; create them empty.
ROSETTA_STAMP := $(SAGE_GEN)/rosetta.stamp
$(ROSETTA_STAMP): $(HOST_BIN)/CxxGrammarMetaProgram $(wildcard $(ROSE_SRC)/src/ROSETTA/Grammar/*) $(ROSE_SRC)/src/ROSETTA/astNodeList
	$(call msg,ROSETTA,$(SAGE_GEN))
	$(Q)rm -rf $(B)/rosetta && mkdir -p $(B)/rosetta/src $(B)/rosetta/out/astFileIO $(B)/rosetta/out/Rose/Traits
	$(Q)cp -r $(ROSE_SRC)/src/ROSETTA/Grammar $(B)/rosetta/Grammar
	$(Q)cd $(B)/rosetta/src && $(abspath $<) $(abspath $(B))/rosetta/out/ > ../rosetta.log
	$(Q)for n in $$(cat $(ROSE_SRC)/src/ROSETTA/astNodeList); do \
	  case $$n in Sg*) [ -f $(B)/rosetta/out/$$n.h ] || touch $(B)/rosetta/out/$$n.h;; esac; done
	$(Q)cd $(B)/rosetta/out && find . -type f | while read f; do \
	  cmp -s "$$f" "$(abspath $(SAGE_GEN))/$$f" || { mkdir -p "$$(dirname "$(abspath $(SAGE_GEN))/$$f")"; \
	    cp "$$f" "$(abspath $(SAGE_GEN))/$$f"; }; done
	$(Q)touch $@
rosetta: $(ROSETTA_STAMP)

ROSETTA_GEN_SRCS := $(addprefix $(SAGE_GEN)/,Cxx_Grammar.C Cxx_GrammarCheckingIfDataMembersAreInMemoryPool.C \
  Cxx_GrammarCopyMemberFunctions.C Cxx_GrammarGetChildIndex.C Cxx_GrammarMemoryPoolSupport.C \
  Cxx_GrammarNewAndDeleteOperators.C Cxx_GrammarNewConstructors.C Cxx_GrammarProcessDataMemberReferenceToPointers.C \
  Cxx_GrammarReturnClassHierarchySubTree.C Cxx_GrammarReturnDataMemberPointers.C Cxx_GrammarRTI.C \
  Cxx_GrammarNodeIdSupport.C Cxx_GrammarTraverseMemoryPool.C Cxx_GrammarTreeTraversalSuccessorContainer.C \
  Cxx_GrammarVariantEnumNames.C Cxx_GrammarVisitorSupport.C StorageClasses.C AST_FILE_IO.C)
$(ROSETTA_GEN_SRCS): $(ROSETTA_STAMP) ;

################################################################################
# Lexers and parsers (preprocessor-directive lexer, OpenMP parser)
################################################################################

$(SAGE_GEN)/lex.yy.C: $(ROSE_SRC)/src/frontend/SageIII/preproc-c.ll
	@mkdir -p $(@D)
	$(FLEX) -t $< > $@
$(SAGE_GEN)/omp-lex.yy.C: $(ROSE_SRC)/src/frontend/SageIII/omplexer.ll
	@mkdir -p $(@D)
	$(FLEX) -t $< > $@
$(SAGE_GEN)/ompparser.C: $(ROSE_SRC)/src/frontend/SageIII/ompparser.yy
	@mkdir -p $(@D)
	$(BISON) $< -o $(SAGE_GEN)/ompparser.c && mv $(SAGE_GEN)/ompparser.c $@
$(SAGE_GEN)/ompparser.h: $(SAGE_GEN)/ompparser.C ;

################################################################################
# librose
################################################################################

ROSE_LIB_OBJS := $(patsubst %.C,$(OBJ)/rose/%.o,$(filter-out $(WIN32_REPLACED),$(filter %.C,$(ROSE_LIB_SRCS)))) \
                 $(patsubst %.cpp,$(OBJ)/rose/%.o,$(filter %.cpp,$(ROSE_LIB_SRCS))) \
                 $(patsubst %.cc,$(OBJ)/rose/%.o,$(filter %.cc,$(ROSE_LIB_SRCS)))
ROSE_GEN_OBJS := $(patsubst $(GEN)/%.C,$(OBJ)/gen/%.o,$(ROSETTA_GEN_SRCS) \
                   $(SAGE_GEN)/lex.yy.C $(SAGE_GEN)/omp-lex.yy.C $(SAGE_GEN)/ompparser.C)

# Everything except the ROSETTA generator itself needs the generated IR headers.
LIB_PREREQS := $(CONFIG_HEADERS) $(ROSETTA_STAMP) $(SAGE_GEN)/ompparser.h

$(ROSE_UTIL_OBJS) $(ROSETTA_OBJS) $(HOST_ROSETTA_OBJS): | $(CONFIG_HEADERS)
$(ROSE_LIB_OBJS) $(ROSE_GEN_OBJS): | $(LIB_PREREQS)

$(OBJ)/rose/%.o: $(ROSE_SRC)/%.C
	$(call msg,CXX,$<)
	@mkdir -p $(@D)
	$(Q)$(CXX) $(ROSE_CXXFLAGS) $(ROSE_CPPFLAGS) -MMD -MP -c $< -o $@
$(OBJ)/rose/%.o: $(ROSE_SRC)/%.cpp
	$(call msg,CXX,$<)
	@mkdir -p $(@D)
	$(Q)$(CXX) $(ROSE_CXXFLAGS) $(ROSE_CPPFLAGS) -MMD -MP -c $< -o $@
$(OBJ)/rose/%.o: $(ROSE_SRC)/%.cc
	$(call msg,CXX,$<)
	@mkdir -p $(@D)
	$(Q)$(CXX) $(ROSE_CXXFLAGS) $(ROSE_CPPFLAGS) -MMD -MP -c $< -o $@
$(OBJ)/gen/%.o: $(GEN)/%.C
	$(call msg,CXX,$<)
	@mkdir -p $(@D)
	$(Q)$(CXX) $(ROSE_CXXFLAGS) $(ROSE_CPPFLAGS) -MMD -MP -c $< -o $@
$(OBJ)/win32/%.o: win32/%.C
	$(call msg,CXX,$<)
	@mkdir -p $(@D)
	$(Q)$(CXX) $(ROSE_CXXFLAGS) $(ROSE_CPPFLAGS) -MMD -MP -c $< -o $@
ifdef CROSS
$(HOST_OBJ)/rose/%.o: $(ROSE_SRC)/%.C
	$(call msg,HOSTCXX,$<)
	@mkdir -p $(@D)
	$(Q)$(HOST_CXX) $(HOST_CXXFLAGS) $(HOST_CPPFLAGS) -MMD -MP -c $< -o $@
$(HOST_OBJ)/gen/%.o: $(GEN)/%.C
	$(call msg,HOSTCXX,$<)
	@mkdir -p $(@D)
	$(Q)$(HOST_CXX) $(HOST_CXXFLAGS) $(HOST_CPPFLAGS) -MMD -MP -c $< -o $@
endif

################################################################################
# EDG front end (compiled as C++, as EDG's own build does)
################################################################################

EDG_SRCS := $(addprefix $(EDG_SRC)/src/,attribute.c c_gen_be.c cfe.c class_decl.c cmd_line.c const_ints.c \
  cp_gen_be.c debug.c decl_inits.c decl_spec.c declarator.c decls.c def_arg.c disambig.c error.c expr.c \
  exprutil.c extasm.c fe_init.c fe_wrapup.c fixed_pt.c float_pt.c floating.c folding.c func_def.c \
  host_envir.c ifc_modules.c il.c il_alloc.c il_display.c il_read.c il_to_str.c il_walk.c il_write.c \
  inline.c interpret.c layout.c lexical.c literals.c lookup.c lower_c99.c lower_eh.c lower_il.c \
  lower_init.c lower_name.c macro.c mem_manage.c modules.c ms_attrib.c overload.c pch.c pragma.c \
  preproc.c scope_stk.c src_seq.c statements.c symbol_ref.c symbol_tbl.c sys_predef.c target.c \
  templates.c trans_copy.c trans_corresp.c trans_unit.c types.c cfe_daemon.c ifc_map_functions.c \
  ifc_map_functions_acc.c ifc_map_functions_dbg.c ifc_map_functions_mut.c ifc_map_functions_val.c \
  ifc_modules_read.c ifc_modules_templ.c ifc_modules_write.c unicode_name_fsm.c)
EDG_SRCS := $(wildcard $(EDG_SRCS))
EDG_OBJS := $(patsubst $(EDG_SRC)/src/%.c,$(OBJ)/edg/%.o,$(EDG_SRCS))
EDG_ERR_HEADERS := $(GEN)/edg/err_codes.h $(GEN)/edg/err_data.h

$(HOST_BIN)/mk_errinfo: $(EDG_SRC)/util/mk_errinfo.c
	@mkdir -p $(@D)
	$(HOST_CXX) -x c++ -std=c++14 -O1 -w -I$(EDG_SRC)/src -o $@ $<
$(GEN)/edg/err_codes.h: $(HOST_BIN)/mk_errinfo $(EDG_SRC)/src/error_msg.txt $(EDG_SRC)/src/error_tag.txt
	@mkdir -p $(@D)
	$(Q)$(HOST_BIN)/mk_errinfo $(EDG_SRC)/src/error_msg.txt $(EDG_SRC)/src/error_tag.txt $(EDG_ERR_HEADERS)
$(GEN)/edg/err_data.h: $(GEN)/edg/err_codes.h ;

$(EDG_OBJS): | $(EDG_ERR_HEADERS)
$(OBJ)/edg/%.o: $(EDG_SRC)/src/%.c $(EDG_CONFIG)
	$(call msg,CXX,$<)
	@mkdir -p $(@D)
	$(Q)$(CXX) $(EDG_CXXFLAGS) $(EDG_CPPFLAGS) -MMD -MP -c $< -o $@

# EDG's table of predefined macros, scraped from the backend compilers (EDG's own script)
$(B)/edg-base/lib/predefined_macros.txt: $(EDG_SRC)/util/make_predef_macro_table
	@mkdir -p $(@D)
	cd $(@D) && sh $(abspath $<) --gcc $(BACKEND_CC) --g++ $(BACKEND_CXX) > make_predef_macro_table.log 2>&1

################################################################################
# edg2sage: EDG IL -> Sage III translation
################################################################################

CONN_SRCS := $(wildcard $(CONN_SRC)/*.C)
CONN_OBJS := $(patsubst $(CONN_SRC)/%.C,$(OBJ)/edg2sage/%.o,$(CONN_SRCS))
$(CONN_OBJS): | $(LIB_PREREQS) $(EDG_ERR_HEADERS)
$(OBJ)/edg2sage/%.o: $(CONN_SRC)/%.C $(EDG_CONFIG)
	$(call msg,CXX,$<)
	@mkdir -p $(@D)
	$(Q)$(CXX) $(ROSE_CXXFLAGS) $(ROSE_CPPFLAGS) -I$(CONN_SRC) $(EDG_CPPFLAGS) \
	  -DEDG2SAGE_EDG_BASE='"$(abspath $(B))/edg-base"' -MMD -MP -c $< -o $@

################################################################################
# Link librose and the tools
################################################################################

ALL_LIB_OBJS := $(ROSE_UTIL_OBJS) $(ROSE_LIB_OBJS) $(ROSE_GEN_OBJS) $(EDG_OBJS) $(CONN_OBJS)

# ROSE_BOOST_PATH (the Boost installation, shown by --version) is defined for utility_functions.C
# only: elsewhere ROSE adds "$(ROSE_BOOST_PATH)/include" to the include paths of EDG and of the
# backend compiler, which would be "/include" (on Windows, that folder on the current drive).
$(filter %/utility_functions.o,$(ALL_LIB_OBJS)): ROSE_CPPFLAGS += -DROSE_BOOST_PATH='""'

ifdef WINDOWS
$(LIBROSE): $(ALL_LIB_OBJS)
	$(call msg,AR,$@)
	@mkdir -p $(@D)
	$(Q)rm -f $@ && $(AR) rcs $@ $^
else
$(LIBROSE): $(ALL_LIB_OBJS)
	$(call msg,LINK,$@)
	@mkdir -p $(@D)
	$(Q)$(CXX) -shared -pthread -o $@ $^ $(BOOST_LDFLAGS) $(BOOST_LIBS) $(SYS_LIBS)
endif

$(OBJ)/tools/%.o: $(TOOL_SRC)/%.C | $(LIB_PREREQS)
	$(call msg,CXX,$<)
	@mkdir -p $(@D)
	$(Q)$(CXX) $(ROSE_CXXFLAGS) $(ROSE_CPPFLAGS) -MMD -MP -c $< -o $@

# Keep the tool objects so that `make check` after `make all` does not
# recompile them.
.SECONDARY: $(addprefix $(OBJ)/tools/,$(addsuffix .o,$(TOOLS)))

ifdef WINDOWS
# Self-contained executables (no MinGW run-time DLLs needed), with a 64 MB stack (reserved
# address space) for the deep recursion in EDG and ROSE, like the 8 MB default on Linux and more
$(B)/bin/%.exe: $(OBJ)/tools/%.o $(LIBROSE)
	$(call msg,LINK,$@)
	@mkdir -p $(@D)
	$(Q)$(CXX) -static -pthread -Wl,--stack,67108864 -o $@ $< $(LIBROSE) $(BOOST_LDFLAGS) $(BOOST_LIBS) $(SYS_LIBS)
else
$(B)/bin/%: $(OBJ)/tools/%.o $(LIBROSE)
	$(call msg,LINK,$@)
	@mkdir -p $(@D)
	$(Q)$(CXX) -pthread -o $@ $< -L$(B)/lib -lrose -Wl,-rpath,$(abspath $(B))/lib $(BOOST_LDFLAGS) $(BOOST_LIBS) $(SYS_LIBS)
endif

################################################################################
# Tests
################################################################################

# The Windows build is tested under Wine (see tests/run-tests.sh)
check: all
	@CC="$(BACKEND_CC)" CXX="$(BACKEND_CXX)" sh tests/run-tests.sh $(B)/bin/identityTranslator$(EXE)

################################################################################
# Windows package: the translators with EDG's configuration and the system headers they parse
# with, as a relocatable zip file (<prefix>\bin, <prefix>\edg-base, <prefix>\include\edg)
################################################################################

PACKAGE := rose-$(ROSE_VERSION)-win64
PKG_DIR := $(B)/package/$(PACKAGE)
ifdef WINDOWS
package: all
	$(call msg,PACKAGE,$(B)/$(PACKAGE).zip)
	$(Q)rm -rf $(B)/package $(B)/$(PACKAGE).zip
	$(Q)mkdir -p $(PKG_DIR)/bin $(PKG_DIR)/edg-base/lib $(PKG_DIR)/include $(PKG_DIR)/licenses
	$(Q)cp $(TOOL_PROGS) $(PKG_DIR)/bin/ && $(TARGET)-strip $(PKG_DIR)/bin/*.exe
	$(Q)cp $(B)/edg-base/lib/predefined_macros.txt $(PKG_DIR)/edg-base/lib/
	$(Q)cp -R $(B)/include/edg $(PKG_DIR)/include/ && rm $(PKG_DIR)/include/edg/stamp
	$(Q)cp -R win32/examples $(PKG_DIR)/
	$(Q)for f in README.txt test.bat; do sed 's/$$/\r/' win32/$$f > $(PKG_DIR)/$$f; done
	$(Q)cp $(ROSE_SRC)/LICENSE $(PKG_DIR)/licenses/ROSE-LICENSE.txt
	$(Q)cp $(EDG_SRC)/LICENSE.txt $(PKG_DIR)/licenses/EDG-LICENSE.txt
	$(Q)cp win32/THIRD-PARTY.txt $(PKG_DIR)/licenses/
	$(Q)for f in /usr/share/doc/mingw-w64-common/copyright:MinGW-w64 /usr/share/doc/gcc-mingw-w64-base/copyright:GCC; do \
	  [ -f "$${f%%:*}" ] && cp "$${f%%:*}" "$(PKG_DIR)/licenses/$${f##*:}-copyright.txt"; done; true
	$(Q)cd $(B)/package && zip -qr9 ../$(PACKAGE).zip $(PACKAGE)
else
package:
	@echo "make package: only for the Windows build (CXX=x86_64-w64-mingw32-g++-posix ...)"; false
endif

################################################################################
# Windows source package: what the Windows build compiles (with the files it generates, and the
# parts of Boost that ROSE uses) and the package's run-time files, with a Makefile with which
# mingw32-make builds the translators on Windows (win32/source/), as a 7z file.  BOOST_SRC is
# the Boost source tree that BOOST_ROOT was built from, with Boost's bcp tool (./b2 tools/bcp).
################################################################################

SRC_PACKAGE := rose-$(ROSE_VERSION)-win64-src
BOOST_SRC ?=
BCP ?= $(BOOST_SRC)/dist/bin/bcp
define SOURCE_PACKAGE_VARS
OUT='$(B)/package/$(SRC_PACKAGE)'
ARCHIVE='$(abspath $(B))/$(SRC_PACKAGE).7z'
PKG_DIR='$(PKG_DIR)'
GEN='$(GEN)'
OBJ='$(OBJ)'
OPT='$(OPT)'
BOOST_INC='$(BOOST_ROOT)/include'
BOOST_SRC='$(BOOST_SRC)'
BCP='$(BCP)'
LIB_OBJS='$(ALL_LIB_OBJS)'
TOOL_OBJS='$(addprefix $(OBJ)/tools/,$(addsuffix .o,$(TOOLS)))'
ROSE_FLAGS='$(ROSE_CXXFLAGS) $(ROSE_CPPFLAGS)'
EDG_FLAGS='$(EDG_CXXFLAGS) $(EDG_CPPFLAGS)'
CONN_FLAGS='$(ROSE_CXXFLAGS) $(ROSE_CPPFLAGS) -I$(CONN_SRC) $(EDG_CPPFLAGS)'
LP64_OBJS='$(WIN32_LP64_OBJS)'
API_OBJS='$(patsubst %.C,$(OBJ)/rose/%.o,$(WIN32_API_SRCS))'
endef
ifdef WINDOWS
source-package: package
	$(call msg,PACKAGE,$(B)/$(SRC_PACKAGE).7z)
	$(file >$(B)/source-package.vars,$(SOURCE_PACKAGE_VARS))
	$(Q)sh scripts/windows-source-package.sh $(B)/source-package.vars
else
source-package:
	@echo "make source-package: only for the Windows build (CXX=x86_64-w64-mingw32-g++-posix ...)"; false
endif
.PHONY: source-package

-include $(shell find $(OBJ) $(B)/host -name '*.d' 2>/dev/null)

# Convenience targets for building parts of the tree
rose-objs: $(ROSE_UTIL_OBJS) $(ROSE_LIB_OBJS) $(ROSE_GEN_OBJS)
edg-objs: $(EDG_OBJS)
.PHONY: rose-objs edg-objs

# "make print-VAR" shows the value of a make variable
print-%:
	@echo '$($*)'
