#!/usr/bin/env python3
"""Regenerate mp3_htabs.h from mp3_A.h.

mp3_A.h keeps its Huffman / scalefactor-band / bit-allocation tables as
function-local statics, so they cannot be referenced from another translation
unit.  This copies them out verbatim (no hand editing, no retyping) into a
header that mp2.cpp can include.

usage: python3 mktabs.py [mp3_A.h [mp3_htabs.h]]
"""
import sys

src_path = sys.argv[1] if len(sys.argv) > 1 else "mp3_A.h"
dst_path = sys.argv[2] if len(sys.argv) > 2 else "mp3_htabs.h"
src = open(src_path).read()

TABLES = [
    ("static const _int16 tabs[]",                "const _int16 g_htabs[]"),
    ("static const _int16 tabindex[2*16]",        "const _int16 g_htabindex[2*16]"),
    ("static const _uint8 g_linbits[]",           "const _uint8 g_hlinbits[]"),
    ("static const _uint8 g_scf_long[8][23]",     "const _uint8 g_scf_long_tab[8][23]"),
    ("static const _uint8 g_bitalloc_code_tab[]", "const _uint8 g_bitalloc_code_tab_[]"),
]


def grab(decl):
    i = src.index(decl)
    j = src.index("{", i)
    depth, k = 0, j
    while True:
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
        if depth == 0:
            break
        k += 1
    return src[j:k + 1]


out = ["""// mp3_htabs.h - Huffman / scalefactor-band / bit-allocation tables extracted
// verbatim from mp3_A.h (they live inside functions there, so they cannot be
// referenced from outside).  Generated by mktabs.py - do not hand-edit.
#ifndef MP3_HTABS_H
#define MP3_HTABS_H
"""]
for decl, name in TABLES:
    out.append("%s = %s;\n" % (name, grab(decl)))
out.append("#endif // MP3_HTABS_H\n")
open(dst_path, "w").write("\n".join(out))
print("wrote %s" % dst_path)
