# File lists for the ROSE build (derived from ROSE 2.18.0's CMake build, C/C++ configuration).
# Paths are relative to $(ROSE_SRC).

# Utility code needed both by the ROSETTA code generator and by librose
ROSE_UTIL_SRCS := \
  src/util/LinearCongruentialGenerator.C \
  src/util/rose_getline.C \
  src/util/processSupport.C \
  src/util/rose_strtoull.C \
  src/util/commandlineProcessing/commandline_processing.C \
  src/util/commandlineProcessing/sla++.C \
  src/Sawyer/Assert.C \
  src/Sawyer/Attribute.C \
  src/Sawyer/Clexer.C \
  src/Sawyer/CommandLine.C \
  src/Sawyer/CommandLineBoost.C \
  src/Sawyer/DocumentBaseMarkup.C \
  src/Sawyer/RoseDatabase.C \
  src/Sawyer/DocumentMarkup.C \
  src/Sawyer/DocumentPodMarkup.C \
  src/Sawyer/DocumentTextMarkup.C \
  src/Sawyer/GraphTraversal.C \
  src/Sawyer/LineVector.C \
  src/Sawyer/Message.C \
  src/Sawyer/ProgressBar.C \
  src/Sawyer/Sawyer.C \
  src/Sawyer/SmallObject.C \
  src/Sawyer/Stopwatch.C \
  src/Sawyer/Synchronization.C \
  src/Sawyer/Time.C \
  src/Sawyer/Yaml.C \
  src/util/stringSupport/escape.C \
  src/util/stringSupport/FileNameClassifier.C \
  src/util/stringSupport/FileUtility.C \
  src/util/support/BitVectorRepr.C \
  src/util/support/CommandOptions.C \
  src/util/support/VectorCommandOptions.C \
  src/util/graphs/DGBaseGraphImpl.C \
  src/util/graphs/SCCAnalysis.C \
  src/util/graphs/TransAnalysis.C \
  src/util/graphs/TypedFusion.C

# ROSETTA: the generator of the Sage III IR classes (src/frontend/SageIII/Cxx_Grammar*)
ROSETTA_SRCS := \
  src/ROSETTA/src/CxxGrammarMetaProgram.C \
  src/ROSETTA/src/grammar.C \
  src/ROSETTA/src/GrammarFile.C \
  src/ROSETTA/src/grammarString.C \
  src/ROSETTA/src/grammarGenerator.C \
  src/ROSETTA/src/AstNodeClass.C \
  src/ROSETTA/src/type.C \
  src/ROSETTA/src/symbol.C \
  src/ROSETTA/src/expression.C \
  src/ROSETTA/src/statement.C \
  src/ROSETTA/src/support.C \
  src/ROSETTA/src/binaryInstruction.C \
  src/ROSETTA/src/storageSize.C \
  src/ROSETTA/src/visitorSupport.C \
  src/ROSETTA/src/poolBasedTraversal.C \
  src/ROSETTA/src/node.C \
  src/ROSETTA/src/nodeIdSupport.C \
  src/ROSETTA/src/buildAstFileIO.C \
  src/ROSETTA/src/buildRoseTraits.C \
  src/ROSETTA/src/buildStorageClasses.C \
  src/ROSETTA/src/buildConstructorsWithoutSourcePositionInformation.C \
  src/ROSETTA/src/outputClassesAndFields.C \
  src/ROSETTA/src/StringUtility.C \
  src/ROSETTA/src/jovialNodes.C

# The rest of librose (frontend/SageIII, midend, backend, ...)
ROSE_LIB_SRCS := \
  src/3rdPartyLibraries/MSTL/DOTGraphInterface.C \
  src/3rdPartyLibraries/MSTL/JSONGeneration.C \
  src/AstNodes/Expression/SgActualArgumentExpression.C \
  src/AstNodes/Expression/SgAdaAncestorInitializer.C \
  src/AstNodes/Expression/SgAdaAttributeExp.C \
  src/AstNodes/Expression/SgAdaProtectedRefExp.C \
  src/AstNodes/Expression/SgAdaRenamingRefExp.C \
  src/AstNodes/Expression/SgAdaTaskRefExp.C \
  src/AstNodes/Expression/SgAdaUnitRefExp.C \
  src/AstNodes/Expression/SgAddressOfOp.C \
  src/AstNodes/Expression/SgAggregateInitializer.C \
  src/AstNodes/Expression/SgAlignOfOp.C \
  src/AstNodes/Expression/SgAndOp.C \
  src/AstNodes/Expression/SgArrowExp.C \
  src/AstNodes/Expression/SgArrowStarOp.C \
  src/AstNodes/Expression/SgAsmOp.C \
  src/AstNodes/Expression/SgAssignInitializer.C \
  src/AstNodes/Expression/SgAsteriskShapeExp.C \
  src/AstNodes/Expression/SgAtExp.C \
  src/AstNodes/Expression/SgBinaryOp.C \
  src/AstNodes/Expression/SgBitComplementOp.C \
  src/AstNodes/Expression/SgBracedInitializer.C \
  src/AstNodes/Expression/SgCAFCoExpression.C \
  src/AstNodes/Expression/SgCallExpression.C \
  src/AstNodes/Expression/SgCastExp.C \
  src/AstNodes/Expression/SgChar16Val.C \
  src/AstNodes/Expression/SgChar32Val.C \
  src/AstNodes/Expression/SgClassExp.C \
  src/AstNodes/Expression/SgColonShapeExp.C \
  src/AstNodes/Expression/SgCommaOpExp.C \
  src/AstNodes/Expression/SgComplexVal.C \
  src/AstNodes/Expression/SgCompoundInitializer.C \
  src/AstNodes/Expression/SgConditionalExp.C \
  src/AstNodes/Expression/SgConstructorInitializer.C \
  src/AstNodes/Expression/SgCudaKernelCallExp.C \
  src/AstNodes/Expression/SgDeleteExp.C \
  src/AstNodes/Expression/SgDesignatedInitializer.C \
  src/AstNodes/Expression/SgDictionaryExp.C \
  src/AstNodes/Expression/SgDotDotExp.C \
  src/AstNodes/Expression/SgDotExp.C \
  src/AstNodes/Expression/SgDotStarOp.C \
  src/AstNodes/Expression/SgEnumVal.C \
  src/AstNodes/Expression/SgExponentiationOp.C \
  src/AstNodes/Expression/SgExprListExp.C \
  src/AstNodes/Expression/SgExpression.C \
  src/AstNodes/Expression/SgFinishExp.C \
  src/AstNodes/Expression/SgFunctionCallExp.C \
  src/AstNodes/Expression/SgFunctionParameterRefExp.C \
  src/AstNodes/Expression/SgFunctionRefExp.C \
  src/AstNodes/Expression/SgHereExp.C \
  src/AstNodes/Expression/SgIOItemExpression.C \
  src/AstNodes/Expression/SgImpliedDo.C \
  src/AstNodes/Expression/SgJavaAnnotation.C \
  src/AstNodes/Expression/SgJavaInstanceOfOp.C \
  src/AstNodes/Expression/SgJavaNormalAnnotation.C \
  src/AstNodes/Expression/SgJovialPresetPositionExp.C \
  src/AstNodes/Expression/SgJovialTablePresetExp.C \
  src/AstNodes/Expression/SgLabelRefExp.C \
  src/AstNodes/Expression/SgLambdaExp.C \
  src/AstNodes/Expression/SgLambdaRefExp.C \
  src/AstNodes/Expression/SgMatrixExp.C \
  src/AstNodes/Expression/SgMemberFunctionRefExp.C \
  src/AstNodes/Expression/SgMinusMinusOp.C \
  src/AstNodes/Expression/SgNaryBooleanOp.C \
  src/AstNodes/Expression/SgNaryComparisonOp.C \
  src/AstNodes/Expression/SgNaryOp.C \
  src/AstNodes/Expression/SgNewExp.C \
  src/AstNodes/Expression/SgNoexceptOp.C \
  src/AstNodes/Expression/SgNonrealRefExp.C \
  src/AstNodes/Expression/SgOrOp.C \
  src/AstNodes/Expression/SgPlusPlusOp.C \
  src/AstNodes/Expression/SgPntrArrRefExp.C \
  src/AstNodes/Expression/SgPointerDerefExp.C \
  src/AstNodes/Expression/SgPseudoDestructorRefExp.C \
  src/AstNodes/Expression/SgRangeExp.C \
  src/AstNodes/Expression/SgSizeOfOp.C \
  src/AstNodes/Expression/SgStatementExpression.C \
  src/AstNodes/Expression/SgStringVal.C \
  src/AstNodes/Expression/SgSubscriptExpression.C \
  src/AstNodes/Expression/SgSuperExp.C \
  src/AstNodes/Expression/SgTemplateFunctionRefExp.C \
  src/AstNodes/Expression/SgTemplateMemberFunctionRefExp.C \
  src/AstNodes/Expression/SgTemplateParameterVal.C \
  src/AstNodes/Expression/SgThisExp.C \
  src/AstNodes/Expression/SgThrowOp.C \
  src/AstNodes/Expression/SgTypeIdOp.C \
  src/AstNodes/Expression/SgTypeTraitBuiltinOperator.C \
  src/AstNodes/Expression/SgUnaryOp.C \
  src/AstNodes/Expression/SgUnknownArrayOrFunctionReference.C \
  src/AstNodes/Expression/SgUpcBlocksizeofExpression.C \
  src/AstNodes/Expression/SgUpcElemsizeofExpression.C \
  src/AstNodes/Expression/SgUpcLocalsizeofExpression.C \
  src/AstNodes/Expression/SgUserDefinedBinaryOp.C \
  src/AstNodes/Expression/SgUserDefinedUnaryOp.C \
  src/AstNodes/Expression/SgVarArgEndOp.C \
  src/AstNodes/Expression/SgVarArgOp.C \
  src/AstNodes/Expression/SgVarRefExp.C \
  src/AstNodes/Expression/SgWcharVal.C \
  src/Rose/AST/NodeId.C \
  src/Rose/AST/Traversal.C \
  src/Rose/AST/Utility.C \
  src/Rose/AST/utils/edge_ptr_repl.C \
  src/Rose/Color/Color.C \
  src/Rose/CommandLine/DurationParser.C \
  src/Rose/CommandLine/License.C \
  src/Rose/CommandLine/Parser.C \
  src/Rose/CommandLine/SelfTest.C \
  src/Rose/CommandLine/Version.C \
  src/Rose/Diagnostics/Diagnostics.C \
  src/Rose/FileSystem/FileSystem.C \
  src/Rose/FormattedTable.C \
  src/Rose/Initialize.C \
  src/Rose/Logger.C \
  src/Rose/Progress.C \
  src/Rose/Sarif/Analysis.C \
  src/Rose/Sarif/Artifact.C \
  src/Rose/Sarif/CodeFlow.C \
  src/Rose/Sarif/Exception.C \
  src/Rose/Sarif/Location.C \
  src/Rose/Sarif/Log.C \
  src/Rose/Sarif/Node.C \
  src/Rose/Sarif/Result.C \
  src/Rose/Sarif/Rule.C \
  src/Rose/Sarif/ThreadFlow.C \
  src/Rose/Sarif/ThreadFlowLocation.C \
  src/Rose/Source/AST/checker/checker.C \
  src/Rose/Source/AST/checker/cmdline.C \
  src/Rose/Source/AST/checker/integrity_declarations.C \
  src/Rose/Source/AST/checker/integrity_edges.C \
  src/Rose/Source/AST/checker/integrity_symbols.C \
  src/Rose/Source/AST/checker/integrity_types.C \
  src/Rose/Source/AST/graphviz.C \
  src/Rose/Source/AST/io/delete.C \
  src/Rose/Source/AST/io/link.C \
  src/Rose/Source/AST/io/load.C \
  src/Rose/Source/AST/io/merge.C \
  src/Rose/Source/AST/io/share.C \
  src/Rose/Source/Analysis/Analyzer.C \
  src/Rose/Source/Analysis/Visitor.C \
  src/Rose/Source/Generation/API.C \
  src/Rose/Source/Generation/Driver.C \
  src/Rose/Source/Generation/Factory.C \
  src/Rose/Source/Generation/SymbolScanner.C \
  src/Rose/Source/Sarif.C \
  src/Rose/SourceLocation.C \
  src/Rose/StringUtility/Convert.C \
  src/Rose/StringUtility/Diagnostics.C \
  src/Rose/StringUtility/Escape.C \
  src/Rose/StringUtility/NumberToString.C \
  src/Rose/StringUtility/Predicate.C \
  src/Rose/StringUtility/SplitJoin.C \
  src/Rose/StringUtility/StringToNumber.C \
  src/Rose/Yaml.C \
  src/backend/unparser/AdaCodeGeneration/unparseAda_expressions.C \
  src/backend/unparser/AdaCodeGeneration/unparseAda_statements.C \
  src/backend/unparser/AdaCodeGeneration/unparseAda_types.C \
  src/backend/unparser/CxxCodeGeneration/helpers_exprs.C \
  src/backend/unparser/CxxCodeGeneration/helpers_stmts.C \
  src/backend/unparser/CxxCodeGeneration/helpers_types.C \
  src/backend/unparser/CxxCodeGeneration/unparseAggrInit.C \
  src/backend/unparser/CxxCodeGeneration/unparseAssnInit.C \
  src/backend/unparser/CxxCodeGeneration/unparseBracedInit.C \
  src/backend/unparser/CxxCodeGeneration/unparseClassType.C \
  src/backend/unparser/CxxCodeGeneration/unparseCompInit.C \
  src/backend/unparser/CxxCodeGeneration/unparseCtorInit.C \
  src/backend/unparser/CxxCodeGeneration/unparseCxx_expressions.C \
  src/backend/unparser/CxxCodeGeneration/unparseCxx_statements.C \
  src/backend/unparser/CxxCodeGeneration/unparseCxx_types.C \
  src/backend/unparser/CxxCodeGeneration/unparseDesignatedInitializer.C \
  src/backend/unparser/CxxCodeGeneration/unparseNewOp.C \
  src/backend/unparser/CxxCodeGeneration/unparseTemplateArgumentList.C \
  src/backend/unparser/CxxCodeGeneration/unparseType.C \
  src/backend/unparser/CxxCodeGeneration/unparseVarDeclStmt.C \
  src/backend/unparser/FortranCodeGeneration/unparseFortran_expressions.C \
  src/backend/unparser/FortranCodeGeneration/unparseFortran_modfile.C \
  src/backend/unparser/FortranCodeGeneration/unparseFortran_statements.C \
  src/backend/unparser/FortranCodeGeneration/unparseFortran_types.C \
  src/backend/unparser/IncludedFilesUnparser.C \
  src/backend/unparser/JavaCodeGeneration/unparseJava_expressions.C \
  src/backend/unparser/JavaCodeGeneration/unparseJava_statements.C \
  src/backend/unparser/JavaCodeGeneration/unparseJava_types.C \
  src/backend/unparser/JovialCodeGeneration/unparseJovial_expressions.C \
  src/backend/unparser/JovialCodeGeneration/unparseJovial_modfile.C \
  src/backend/unparser/JovialCodeGeneration/unparseJovial_statements.C \
  src/backend/unparser/JovialCodeGeneration/unparseJovial_types.C \
  src/backend/unparser/MatlabCodeGeneration/MatlabUnparser.C \
  src/backend/unparser/MatlabCodeGeneration/MatlabUnparserBottomUpTraversal.C \
  src/backend/unparser/PHPCodeGeneration/unparsePHP.C \
  src/backend/unparser/astUnparseAttribute.C \
  src/backend/unparser/formatSupport/unparseFormatHelp.C \
  src/backend/unparser/formatSupport/unparse_format.C \
  src/backend/unparser/includeFileSupport.C \
  src/backend/unparser/languageIndependenceSupport/modified_sage.C \
  src/backend/unparser/languageIndependenceSupport/modified_sage_isUnaryOp.C \
  src/backend/unparser/languageIndependenceSupport/name_qualification_support.C \
  src/backend/unparser/languageIndependenceSupport/unparseLanguageIndependentConstructs.C \
  src/backend/unparser/languageIndependenceSupport/unparse_debug.C \
  src/backend/unparser/languageIndependenceSupport/unparser_opt.C \
  src/backend/unparser/nameQualificationSupport.C \
  src/backend/unparser/unparse_sym.C \
  src/backend/unparser/unparser.C \
  src/dummyCppFileForLibrose.C \
  src/frontend/SageIII/OmpAttribute.C \
  src/frontend/SageIII/Utf8.C \
  src/frontend/SageIII/astFixup/AstFixup.C \
  src/frontend/SageIII/astFixup/fixupDeclarations2.C \
  src/frontend/SageIII/astFixup/fixupEnumValues.C \
  src/frontend/SageIII/astFixup/fixupFriendTemplateDeclarations.C \
  src/frontend/SageIII/astFixup/fixupFunctionDefinitions.C \
  src/frontend/SageIII/astFixup/fixupInClassDataInitialization.C \
  src/frontend/SageIII/astFixup/fixupPrettyFunction.C \
  src/frontend/SageIII/astFixup/fixupSourcePositionInformation.C \
  src/frontend/SageIII/astFixup/fixupStorageAccessOfForwardTemplateDeclarations.C \
  src/frontend/SageIII/astFixup/fixupforGnuBackendCompiler.C \
  src/frontend/SageIII/astFixup/removeInitializedNamePtr.C \
  src/frontend/SageIII/astFromString/AstFromString.cpp \
  src/frontend/SageIII/astFromString/ParserBuilder.cpp \
  src/frontend/SageIII/astHiddenTypeAndDeclarationLists/HiddenList.C \
  src/frontend/SageIII/astHiddenTypeAndDeclarationLists/HiddenList_Intersection.C \
  src/frontend/SageIII/astHiddenTypeAndDeclarationLists/HiddenList_Output.C \
  src/frontend/SageIII/astHiddenTypeAndDeclarationLists/NamespacesAndClassTraversal.C \
  src/frontend/SageIII/astPostProcessing/addPrototypesForTemplateInstantiations.C \
  src/frontend/SageIII/astPostProcessing/astPostProcessing.C \
  src/frontend/SageIII/astPostProcessing/buildStatementNumbering.C \
  src/frontend/SageIII/astPostProcessing/checkIsCompilerGeneratedFlag.C \
  src/frontend/SageIII/astPostProcessing/checkIsFrontendSpecificFlag.C \
  src/frontend/SageIII/astPostProcessing/checkIsModifiedFlag.C \
  src/frontend/SageIII/astPostProcessing/checkPhysicalSourcePosition.C \
  src/frontend/SageIII/astPostProcessing/detectTransformations.C \
  src/frontend/SageIII/astPostProcessing/fixupConstantFoldedValues.C \
  src/frontend/SageIII/astPostProcessing/fixupConstructorPreinitializationLists.C \
  src/frontend/SageIII/astPostProcessing/fixupCxxSymbolTablesToSupportAliasingSymbols.C \
  src/frontend/SageIII/astPostProcessing/fixupDeclarationScope.C \
  src/frontend/SageIII/astPostProcessing/fixupDeclarations.C \
  src/frontend/SageIII/astPostProcessing/fixupDefiningAndNondefiningDeclarations.C \
  src/frontend/SageIII/astPostProcessing/fixupFileInfoFlags.C \
  src/frontend/SageIII/astPostProcessing/fixupFunctionDefaultArguments.C \
  src/frontend/SageIII/astPostProcessing/fixupInitializers.C \
  src/frontend/SageIII/astPostProcessing/fixupNames.C \
  src/frontend/SageIII/astPostProcessing/fixupNullPointers.C \
  src/frontend/SageIII/astPostProcessing/fixupSelfReferentialMacros.C \
  src/frontend/SageIII/astPostProcessing/fixupSymbolTables.C \
  src/frontend/SageIII/astPostProcessing/fixupTemplateArguments.C \
  src/frontend/SageIII/astPostProcessing/fixupTemplateInstantiations.C \
  src/frontend/SageIII/astPostProcessing/fixupTypeReferences.C \
  src/frontend/SageIII/astPostProcessing/fixupTypes.C \
  src/frontend/SageIII/astPostProcessing/fixupUseAndUsingDeclarations.C \
  src/frontend/SageIII/astPostProcessing/initializeExplicitScopeData.C \
  src/frontend/SageIII/astPostProcessing/insertFortranContainsStatement.C \
  src/frontend/SageIII/astPostProcessing/markBackendCompilerSpecificFunctions.C \
  src/frontend/SageIII/astPostProcessing/markCompilerGenerated.C \
  src/frontend/SageIII/astPostProcessing/markForOutputInCodeGeneration.C \
  src/frontend/SageIII/astPostProcessing/markLhsValues.C \
  src/frontend/SageIII/astPostProcessing/markOverloadedTemplateInstantiations.C \
  src/frontend/SageIII/astPostProcessing/markSharedDeclarationsForOutputInCodeGeneration.C \
  src/frontend/SageIII/astPostProcessing/markTemplateInstantiationsForOutput.C \
  src/frontend/SageIII/astPostProcessing/markTemplateSpecializationsForOutput.C \
  src/frontend/SageIII/astPostProcessing/markTransformationsForOutput.C \
  src/frontend/SageIII/astPostProcessing/normalizeTypedefSequenceLists.C \
  src/frontend/SageIII/astPostProcessing/processTemplateHandlingOptions.C \
  src/frontend/SageIII/astPostProcessing/propagateHiddenListData.C \
  src/frontend/SageIII/astPostProcessing/resetParentPointers.C \
  src/frontend/SageIII/astPostProcessing/resetTemplateNames.C \
  src/frontend/SageIII/astPostProcessing/resolveFortranReferences.C \
  src/frontend/SageIII/astTokenStream/artificialFrontier.C \
  src/frontend/SageIII/astTokenStream/createMap.C \
  src/frontend/SageIII/astTokenStream/detectMacroExpansionsToBeUnparsedAsAstTransformations.C \
  src/frontend/SageIII/astTokenStream/detectMacroOrIncludeFileExpansions.C \
  src/frontend/SageIII/astTokenStream/doCompleteMapping.C \
  src/frontend/SageIII/astTokenStream/frontierDetection.C \
  src/frontend/SageIII/astTokenStream/linearizeAST.C \
  src/frontend/SageIII/astTokenStream/maxExtents.C \
  src/frontend/SageIII/astTokenStream/previousAndNextNode.C \
  src/frontend/SageIII/astTokenStream/simpleFrontierDetection.C \
  src/frontend/SageIII/astTokenStream/tokenStreamMapping.C \
  src/frontend/SageIII/astTokenStream/unparseMacro.C \
  src/frontend/SageIII/astVisualization/AstAttributeDOT.C \
  src/frontend/SageIII/astVisualization/astGraph.C \
  src/frontend/SageIII/astVisualization/copyGraph.C \
  src/frontend/SageIII/astVisualization/includeGraph.C \
  src/frontend/SageIII/astVisualization/walrus.C \
  src/frontend/SageIII/astVisualization/wholeAST.C \
  src/frontend/SageIII/attachPreprocessingInfo.C \
  src/frontend/SageIII/attachPreprocessingInfoTraversal.C \
  src/frontend/SageIII/attributeListMap.C \
  src/frontend/SageIII/dwarfSupport.C \
  src/frontend/SageIII/fixupCopy_references.C \
  src/frontend/SageIII/fixupCopy_scopes.C \
  src/frontend/SageIII/fixupCopy_symbols.C \
  src/frontend/SageIII/includeDirectivesProcessing/CompilerOutputParser.C \
  src/frontend/SageIII/includeDirectivesProcessing/CompilerOutputReader.C \
  src/frontend/SageIII/includeDirectivesProcessing/IncludingPreprocessingInfosCollector.C \
  src/frontend/SageIII/manglingSupport.C \
  src/frontend/SageIII/ompAstConstruction.cpp \
  src/frontend/SageIII/ompFortranParser.C \
  src/frontend/SageIII/rose_attributes_list.C \
  src/frontend/SageIII/rose_graph_support.C \
  src/frontend/SageIII/rtiHelpers.C \
  src/frontend/SageIII/sageInterface/SageBuilderAsm.C \
  src/frontend/SageIII/sageInterface/abiStuff.C \
  src/frontend/SageIII/sageInterface/generateUniqueName.C \
  src/frontend/SageIII/sageInterface/sageBuilder.C \
  src/frontend/SageIII/sageInterface/sageBuilder_fortran.C \
  src/frontend/SageIII/sageInterface/sageInterface.C \
  src/frontend/SageIII/sageInterface/sageInterfaceAda.C \
  src/frontend/SageIII/sageInterface/sageInterfaceAsm.C \
  src/frontend/SageIII/sageInterface/sageInterface_asm.C \
  src/frontend/SageIII/sageInterface/sageInterface_type.C \
  src/frontend/SageIII/sage_support/cmdline.C \
  src/frontend/SageIII/sage_support/keep_going.C \
  src/frontend/SageIII/sage_support/sage_support.C \
  src/frontend/SageIII/virtualCFG/cfgToDot.C \
  src/frontend/SageIII/virtualCFG/customFilteredCFG.C \
  src/frontend/SageIII/virtualCFG/interproceduralCFG.C \
  src/frontend/SageIII/virtualCFG/memberFunctions.C \
  src/frontend/SageIII/virtualCFG/staticCFG.C \
  src/frontend/SageIII/virtualCFG/virtualBinCFG.C \
  src/frontend/SageIII/virtualCFG/virtualCFG.C \
  src/generated/Jovial/SgJovialBitVal.C \
  src/generated/Rose/Sarif/Analysis.C \
  src/generated/Rose/Sarif/Artifact.C \
  src/generated/Rose/Sarif/CodeFlow.C \
  src/generated/Rose/Sarif/Location.C \
  src/generated/Rose/Sarif/Log.C \
  src/generated/Rose/Sarif/Node.C \
  src/generated/Rose/Sarif/Result.C \
  src/generated/Rose/Sarif/Rule.C \
  src/generated/Rose/Sarif/ThreadFlow.C \
  src/generated/Rose/Sarif/ThreadFlowLocation.C \
  src/midend/abstractHandle/abstract_handle.cpp \
  src/midend/abstractHandle/roseAdapter.cpp \
  src/midend/abstractLayer/AstAnnotator.C \
  src/midend/abstractLayer/CPAstAttributeInterface.C \
  src/midend/abstractLayer/CodeThornException.C \
  src/midend/abstractLayer/DFAstAttribute.C \
  src/midend/abstractLayer/Label.C \
  src/midend/abstractLayer/Labeler.C \
  src/midend/abstractLayer/RDAstAttributeInterface.C \
  src/midend/abstractLayer/SgNodeHelper.C \
  src/midend/abstractLayer/VariableIdMapping.C \
  src/midend/abstractMemoryObject/memory_object.cpp \
  src/midend/abstractMemoryObject/memory_object_impl.cpp \
  src/midend/astDiagnostics/AstConsistencyTests.C \
  src/midend/astDiagnostics/AstPerformance.C \
  src/midend/astDiagnostics/AstStatistics.C \
  src/midend/astDiagnostics/AstWarnings.C \
  src/midend/astMatching/AstMatching.C \
  src/midend/astMatching/AstTerm.C \
  src/midend/astMatching/MatchOperation.C \
  src/midend/astMatching/RoseAst.C \
  src/midend/astMatching/matcherparser.C \
  src/midend/astProcessing/AstAttributeMechanism.C \
  src/midend/astProcessing/AstClearVisitFlags.C \
  src/midend/astProcessing/AstCombinedSimpleProcessing.C \
  src/midend/astProcessing/AstDOTGeneration.C \
  src/midend/astProcessing/AstJSONGeneration.C \
  src/midend/astProcessing/AstNodePtrs.C \
  src/midend/astProcessing/AstNodeVisitMapping.C \
  src/midend/astProcessing/AstProcessing.C \
  src/midend/astProcessing/AstRestructure.C \
  src/midend/astProcessing/AstReverseSimpleProcessing.C \
  src/midend/astProcessing/AstSharedMemoryParallelSimpleProcessing.C \
  src/midend/astProcessing/AstSimpleProcessing.C \
  src/midend/astProcessing/AstSuccessorsSelectors.C \
  src/midend/astProcessing/AstTextAttributesHandling.C \
  src/midend/astProcessing/AstTraversal.C \
  src/midend/astProcessing/plugin.C \
  src/midend/astQuery/astQuery.C \
  src/midend/astQuery/astQueryInheritedAttribute.C \
  src/midend/astQuery/booleanQuery.C \
  src/midend/astQuery/booleanQueryInheritedAttribute.C \
  src/midend/astQuery/nameQuery.C \
  src/midend/astQuery/nameQueryInheritedAttribute.C \
  src/midend/astQuery/nodeQuery.C \
  src/midend/astQuery/nodeQueryInheritedAttribute.C \
  src/midend/astQuery/numberQuery.C \
  src/midend/astQuery/numberQueryInheritedAttribute.C \
  src/midend/astRewriteMechanism/nodeCollection.C \
  src/midend/astRewriteMechanism/rewriteASTFragementString.C \
  src/midend/astRewriteMechanism/rewriteAccumulatedAttribute.C \
  src/midend/astRewriteMechanism/rewriteDebuggingSupport.C \
  src/midend/astRewriteMechanism/rewriteHighLevelInterface.C \
  src/midend/astRewriteMechanism/rewriteLowLevelInterface.C \
  src/midend/astRewriteMechanism/rewriteMidLevelInterface.C \
  src/midend/astRewriteMechanism/rewriteSynthesizedAttribute.C \
  src/midend/astRewriteMechanism/rewriteTemplateInstantiations.C \
  src/midend/astRewriteMechanism/rewriteTypeDeclaration.C \
  src/midend/astSnippet/Snippet.C \
  src/midend/astUtil/AstUtilInterface.C \
  src/midend/astUtil/annotation/AnnotCollect.C \
  src/midend/astUtil/annotation/AnnotDescriptors.C \
  src/midend/astUtil/annotation/AnnotExpr.C \
  src/midend/astUtil/annotation/AnnotGen.C \
  src/midend/astUtil/annotation/AnnotIO.C \
  src/midend/astUtil/annotation/OperatorAnnotation.C \
  src/midend/astUtil/annotation/OperatorDescriptors.C \
  src/midend/astUtil/annotation/TypeAnnotation.C \
  src/midend/astUtil/astInterface/AstInterface.C \
  src/midend/astUtil/astInterface/CPPAstInterface.C \
  src/midend/astUtil/astSupport/StmtInfoCollect.C \
  src/midend/astUtil/dependenceTracking/dependence_analysis.C \
  src/midend/astUtil/dependenceTracking/dependence_table.C \
  src/midend/astUtil/symbolicVal/SymbolicBound.C \
  src/midend/astUtil/symbolicVal/SymbolicExpr.C \
  src/midend/astUtil/symbolicVal/SymbolicFind.C \
  src/midend/astUtil/symbolicVal/SymbolicOperator.C \
  src/midend/astUtil/symbolicVal/SymbolicUnwrapCond.C \
  src/midend/astUtil/symbolicVal/SymbolicVal.C \
  src/midend/midend_roseh_pch.cpp \
  src/midend/programAnalysis/CFG/CFG_ROSE.C \
  src/midend/programAnalysis/CallGraphAnalysis/CallGraph.C \
  src/midend/programAnalysis/CallGraphAnalysis/CallGraphDB.C \
  src/midend/programAnalysis/CallGraphAnalysis/ClassHierarchyGraph.C \
  src/midend/programAnalysis/CallGraphAnalysis/newCallGraph.C \
  src/midend/programAnalysis/EditDistance/EditDistance.C \
  src/midend/programAnalysis/EditDistance/TreeEditDistance.C \
  src/midend/programAnalysis/OAWrap/OAWrap.C \
  src/midend/programAnalysis/OAWrap/SAGE2OA.C \
  src/midend/programAnalysis/ReadWriteSetAnalysis/LocalRWSetGenerator.C \
  src/midend/programAnalysis/ReadWriteSetAnalysis/Name2Node.C \
  src/midend/programAnalysis/ReadWriteSetAnalysis/ReadWriteSetRecords.C \
  src/midend/programAnalysis/ReadWriteSetAnalysis/SageUtils.C \
  src/midend/programAnalysis/ReadWriteSetAnalysis/TestabilityGrader.C \
  src/midend/programAnalysis/ReadWriteSetAnalysis/VxUtilFuncs.C \
  src/midend/programAnalysis/VirtualFunctionAnalysis/InterProcDataFlowAnalysis.C \
  src/midend/programAnalysis/VirtualFunctionAnalysis/IntraProcAliasAnalysis.C \
  src/midend/programAnalysis/VirtualFunctionAnalysis/IntraProcDataFlowAnalysis.C \
  src/midend/programAnalysis/VirtualFunctionAnalysis/PtrAliasAnalysis.C \
  src/midend/programAnalysis/VirtualFunctionAnalysis/VirtualFunctionAnalysis.C \
  src/midend/programAnalysis/bitvectorDataflow/DataFlowAnalysis.C \
  src/midend/programAnalysis/bitvectorDataflow/DefUseChain.C \
  src/midend/programAnalysis/bitvectorDataflow/ReachingDefinition.C \
  src/midend/programAnalysis/dataflowAnalysis/ReachingDefinitionFacade.C \
  src/midend/programAnalysis/defUseAnalysis/DefUseAnalysis.cpp \
  src/midend/programAnalysis/defUseAnalysis/DefUseAnalysisAbstract.cpp \
  src/midend/programAnalysis/defUseAnalysis/DefUseAnalysis_perFunction.cpp \
  src/midend/programAnalysis/defUseAnalysis/GlobalVarAnalysis.cpp \
  src/midend/programAnalysis/defUseAnalysis/LivenessAnalysis.cpp \
  src/midend/programAnalysis/defUseAnalysis/dfaToDot.cpp \
  src/midend/programAnalysis/genericDataflow/AnalysisDebuggingUtils.C \
  src/midend/programAnalysis/genericDataflow/analysis/analysis.C \
  src/midend/programAnalysis/genericDataflow/analysis/analysisCommon.C \
  src/midend/programAnalysis/genericDataflow/analysis/dataflow.C \
  src/midend/programAnalysis/genericDataflow/analysis/partitionedAnalysis.C \
  src/midend/programAnalysis/genericDataflow/arrIndexLabeler/arrIndexLabeler.C \
  src/midend/programAnalysis/genericDataflow/cfgUtils/CFGRewrite.C \
  src/midend/programAnalysis/genericDataflow/cfgUtils/CallGraphTraverse.C \
  src/midend/programAnalysis/genericDataflow/cfgUtils/DataflowCFG.C \
  src/midend/programAnalysis/genericDataflow/cfgUtils/VirtualCFGIterator.C \
  src/midend/programAnalysis/genericDataflow/cfgUtils/cfgUtils.C \
  src/midend/programAnalysis/genericDataflow/genUID.C \
  src/midend/programAnalysis/genericDataflow/lattice/ConstrGraph.C \
  src/midend/programAnalysis/genericDataflow/lattice/affineInequality.C \
  src/midend/programAnalysis/genericDataflow/lattice/lattice.C \
  src/midend/programAnalysis/genericDataflow/rwAccessLabeler/rwAccessLabeler.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/ConstrGraphAnalysis.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/divAnalysis.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/dominatorAnalysis.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/liveDeadVarAnalysis.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/nodeConstAnalysis.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/placeUIDs.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/printAnalysisStates.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/saveDotAnalysis.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/sequenceStructAnalysis.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/sgnAnalysis.C \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses/taintAnalysis.C \
  src/midend/programAnalysis/genericDataflow/state/functionState.C \
  src/midend/programAnalysis/genericDataflow/state/nodeState.C \
  src/midend/programAnalysis/genericDataflow/variables/varSets.C \
  src/midend/programAnalysis/genericDataflow/variables/variables.C \
  src/midend/programAnalysis/pointerAnal/PtrAnal.C \
  src/midend/programAnalysis/pointerAnal/PtrAnalCFG.C \
  src/midend/programAnalysis/ssaUnfilteredCfg/defsAndUsesUnfilteredCfg.C \
  src/midend/programAnalysis/ssaUnfilteredCfg/reachingDefUnfilteredCfg.C \
  src/midend/programAnalysis/ssaUnfilteredCfg/ssaUnfilteredCfgCalculation.C \
  src/midend/programAnalysis/ssaUnfilteredCfg/ssaUnfilteredCfgQueries.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/ControlDependenceGraph.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/ControlFlowGraph.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/CreateSlice.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/CreateSliceSet.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/DataDependenceGraph.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/DefUseExtension.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/DependenceGraph.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/EDefUse.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/FunctionDependenceGraph.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/MergedDependenceGraph.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/SlicingInfo.C \
  src/midend/programAnalysis/staticInterproceduralSlicing/SystemDependenceGraph.C \
  src/midend/programAnalysis/staticSingleAssignment/defsAndUsesTraversal.C \
  src/midend/programAnalysis/staticSingleAssignment/reachingDef.C \
  src/midend/programAnalysis/staticSingleAssignment/staticSingleAssignmentCalculation.C \
  src/midend/programAnalysis/staticSingleAssignment/staticSingleAssignmentInterprocedural.C \
  src/midend/programAnalysis/staticSingleAssignment/staticSingleAssignmentQueries.C \
  src/midend/programAnalysis/staticSingleAssignment/uniqueNameTraversal.C \
  src/midend/programAnalysis/valuePropagation/ArrayAnnot.C \
  src/midend/programAnalysis/valuePropagation/ValueAnnot.C \
  src/midend/programAnalysis/valuePropagation/ValuePropagate.C \
  src/midend/programAnalysis/variableRenaming/VariableRenaming.C \
  src/midend/programTransformation/astInlining/inliner.C \
  src/midend/programTransformation/astInlining/inlinerSupport.C \
  src/midend/programTransformation/astInlining/isPotentiallyModified.C \
  src/midend/programTransformation/astInlining/replaceExpressionWithStatement.C \
  src/midend/programTransformation/astOutlining/ASTtools.cc \
  src/midend/programTransformation/astOutlining/Block.cc \
  src/midend/programTransformation/astOutlining/Case.cc \
  src/midend/programTransformation/astOutlining/Check.cc \
  src/midend/programTransformation/astOutlining/CollectVars.cc \
  src/midend/programTransformation/astOutlining/Copy.cc \
  src/midend/programTransformation/astOutlining/ExtractIfs.cc \
  src/midend/programTransformation/astOutlining/GenerateCall.cc \
  src/midend/programTransformation/astOutlining/GenerateFunc.cc \
  src/midend/programTransformation/astOutlining/If.cc \
  src/midend/programTransformation/astOutlining/IfDirectiveContextFinder.cc \
  src/midend/programTransformation/astOutlining/IfDirectiveExtractor.cc \
  src/midend/programTransformation/astOutlining/Insert.cc \
  src/midend/programTransformation/astOutlining/Jumps.cc \
  src/midend/programTransformation/astOutlining/NameGenerator.cc \
  src/midend/programTransformation/astOutlining/NonLocalControlFlow.cc \
  src/midend/programTransformation/astOutlining/NonLocalDecls.cc \
  src/midend/programTransformation/astOutlining/Outliner.cc \
  src/midend/programTransformation/astOutlining/PragmaInterface.cc \
  src/midend/programTransformation/astOutlining/PrePostTraversal.cc \
  src/midend/programTransformation/astOutlining/PreprocIfs.cc \
  src/midend/programTransformation/astOutlining/Preprocess.cc \
  src/midend/programTransformation/astOutlining/PreprocessingInfo.cc \
  src/midend/programTransformation/astOutlining/StmtRewrite.cc \
  src/midend/programTransformation/astOutlining/This.cc \
  src/midend/programTransformation/astOutlining/ThisExprs.cc \
  src/midend/programTransformation/astOutlining/Transform.cc \
  src/midend/programTransformation/astOutlining/VarSym.cc \
  src/midend/programTransformation/constantFolding/constantFolding.C \
  src/midend/programTransformation/extractFunctionArgumentsNormalization/ExtractFunctionArguments.C \
  src/midend/programTransformation/extractFunctionArgumentsNormalization/functionEvaluationOrderTraversal.C \
  src/midend/programTransformation/finiteDifferencing/finiteDifferencing.C \
  src/midend/programTransformation/finiteDifferencing/patternRewrite.C \
  src/midend/programTransformation/functionCallNormalization/FunctionNormalization.C \
  src/midend/programTransformation/implicitCodeGeneration/analysisUtils.C \
  src/midend/programTransformation/implicitCodeGeneration/defaultFunctionGenerator.C \
  src/midend/programTransformation/implicitCodeGeneration/destructorCallAnnotator.C \
  src/midend/programTransformation/implicitCodeGeneration/shortCircuitingTransformation.C \
  src/midend/programTransformation/loopProcessing/computation/DepCompTransform.C \
  src/midend/programTransformation/loopProcessing/computation/LoopTree.C \
  src/midend/programTransformation/loopProcessing/computation/LoopTreeDepComp.C \
  src/midend/programTransformation/loopProcessing/computation/LoopTreeDummyNode.C \
  src/midend/programTransformation/loopProcessing/computation/LoopTreeLocality.C \
  src/midend/programTransformation/loopProcessing/computation/LoopTreeShadow.C \
  src/midend/programTransformation/loopProcessing/computation/LoopTreeTransform.C \
  src/midend/programTransformation/loopProcessing/depGraph/DepGraphBuild.C \
  src/midend/programTransformation/loopProcessing/depGraph/LoopAnalysis.C \
  src/midend/programTransformation/loopProcessing/depGraph/TransDepGraph.C \
  src/midend/programTransformation/loopProcessing/depInfo/DepEDD.C \
  src/midend/programTransformation/loopProcessing/depInfo/DepInfo.C \
  src/midend/programTransformation/loopProcessing/depInfo/DepInfoAnal.C \
  src/midend/programTransformation/loopProcessing/depInfo/DepInfoSet.C \
  src/midend/programTransformation/loopProcessing/depInfo/DepRel.C \
  src/midend/programTransformation/loopProcessing/depInfo/DomainInfo.C \
  src/midend/programTransformation/loopProcessing/depInfo/ReuseAnalysis.C \
  src/midend/programTransformation/loopProcessing/depInfo/StmtDepAnal.C \
  src/midend/programTransformation/loopProcessing/driver/ArrayInterface.C \
  src/midend/programTransformation/loopProcessing/driver/AutoTuningInterface.C \
  src/midend/programTransformation/loopProcessing/driver/BlockingAnal.C \
  src/midend/programTransformation/loopProcessing/driver/CopyArrayAnal.C \
  src/midend/programTransformation/loopProcessing/driver/FusionAnal.C \
  src/midend/programTransformation/loopProcessing/driver/InterchangeAnal.C \
  src/midend/programTransformation/loopProcessing/driver/LoopTransformInterface.C \
  src/midend/programTransformation/loopProcessing/driver/LoopTransformOptions.C \
  src/midend/programTransformation/loopProcessing/driver/NormalizeCPP.C \
  src/midend/programTransformation/loopProcessing/driver/ParallelizeLoop.C \
  src/midend/programTransformation/loopProcessing/driver/TransformComputation.C \
  src/midend/programTransformation/loopProcessing/driver/TypedFusionImpl.C \
  src/midend/programTransformation/loopProcessing/outsideInterface/ArrayRewrite.C \
  src/midend/programTransformation/loopProcessing/prepostTransformation/BreakupStmt.C \
  src/midend/programTransformation/loopProcessing/prepostTransformation/LoopUnroll.C \
  src/midend/programTransformation/loopProcessing/prepostTransformation/PrivatizeScalar.C \
  src/midend/programTransformation/loopProcessing/slicing/CompSlice.C \
  src/midend/programTransformation/loopProcessing/slicing/CompSliceDepGraph.C \
  src/midend/programTransformation/loopProcessing/slicing/CompSliceLocality.C \
  src/midend/programTransformation/loopProcessing/slicing/DependenceHoisting.C \
  src/midend/programTransformation/loopProcessing/slicing/DynamicCompSlice.C \
  src/midend/programTransformation/ompLowering/omp_lowering.cpp \
  src/midend/programTransformation/partialRedundancyElimination/expressionTreeEqual.C \
  src/midend/programTransformation/partialRedundancyElimination/pre.C \
  src/midend/programTransformation/partialRedundancyElimination/preControlFlowGraph.C \
  src/midend/programTransformation/singleStatementToBlockNormalization/SingleStatementToBlockNormalization.C \
  src/midend/programTransformation/transformationTracking/transformationTracking.cpp \
  src/roseExtensions/failSafe/failSafePragma.C \
  src/roseSupport/Combinatorics.C \
  src/roseSupport/IncludeDirective.C \
  src/roseSupport/memoryUsage.C \
  src/roseSupport/optionDeclaration.C \
  src/roseSupport/rangemap.C \
  src/roseSupport/roseTranslators.C \
  src/roseSupport/sourceLocationInheritedAttribute.C \
  src/roseSupport/stringify.C \
  src/roseSupport/transformationSupport.C \
  src/roseSupport/utility_functions.C


# Include directories, relative to $(ROSE_SRC)
ROSE_INCDIRS := \
  src/roseExtensions/failSafe \
  src/midend/programTransformation/transformationTracking \
  src/frontend/ECJ_ROSE_Connection \
  src/midend/astMatching \
  src/util \
  src/frontend \
  . \
  src/frontend/SageIII \
  src/frontend/SageIII/sage_support \
  src/ROSETTA/src \
  src \
  src/generated \
  src/frontend/SageIII/astFixup \
  src/frontend/SageIII/astPostProcessing \
  src/frontend/SageIII/astVisualization \
  src/frontend/SageIII/includeDirectivesProcessing \
  src/frontend/SageIII/astFileIO \
  src/frontend/SageIII/sageInterface \
  src/frontend/SageIII/virtualCFG \
  src/frontend/SageIII/astTokenStream \
  src/frontend/SageIII/astHiddenTypeAndDeclarationLists \
  src/frontend/SageIII/astFromString \
  src/frontend/OpenFortranParser_SAGE_Connection \
  src/frontend/PHPFrontend \
  src/frontend/PythonFrontend \
  src/frontend/BinaryFormats \
  src/frontend/Disassemblers \
  src/backend/unparser \
  src/backend/unparser/formatSupport \
  src/backend/unparser/languageIndependenceSupport \
  src/backend/unparser/CxxCodeGeneration \
  src/backend/unparser/FortranCodeGeneration \
  src/backend/unparser/JavaCodeGeneration \
  src/backend/unparser/PHPCodeGeneration \
  src/backend/unparser/PythonCodeGeneration \
  src/backend/unparser/AdaCodeGeneration \
  src/backend/unparser/JovialCodeGeneration \
  src/backend/asmUnparser \
  src/util/support \
  src/util/graphs \
  src/util/stringSupport \
  src/util/commandlineProcessing \
  src/midend \
  src/midend/abstractHandle \
  src/midend/abstractLayer \
  src/midend/abstractMemoryObject \
  src/midend/astDiagnostics \
  src/midend/programTransformation/astInlining \
  src/midend/programTransformation/astOutlining \
  src/midend/astProcessing \
  src/midend/astQuery \
  src/midend/astRewriteMechanism \
  src/midend/astUtil \
  src/midend/astUtil/annotation \
  src/midend/astUtil/astInterface \
  src/midend/astUtil/astSupport \
  src/midend/astUtil/symbolicVal \
  src/midend/astUtil/dependenceTracking \
  src/midend/BinaryAnalysis \
  src/midend/programTransformation/loopProcessing/computation \
  src/midend/programTransformation/loopProcessing/depGraph \
  src/midend/programTransformation/loopProcessing/depInfo \
  src/midend/programTransformation/loopProcessing/driver \
  src/midend/programTransformation/loopProcessing/outsideInterface \
  src/midend/programTransformation/loopProcessing/prepostTransformation \
  src/midend/programTransformation/loopProcessing/slicing \
  src/midend/programTransformation/ompLowering \
  src/midend/programAnalysis \
  src/midend/programAnalysis/CFG \
  src/midend/programAnalysis/CallGraphAnalysis \
  src/midend/programAnalysis/OAWrap \
  src/midend/programAnalysis/bitvectorDataflow \
  src/midend/programAnalysis/VirtualFunctionAnalysis \
  src/midend/programAnalysis/defUseAnalysis \
  src/midend/programAnalysis/distributedMemoryAnalysis \
  src/midend/programAnalysis/dominanceAnalysis \
  src/midend/programAnalysis/pointerAnal \
  src/midend/programAnalysis/staticSingleAssignment \
  src/midend/programAnalysis/staticInterproceduralSlicing \
  src/midend/programAnalysis/valuePropagation \
  src/midend/programTransformation/partialRedundancyElimination \
  src/midend/programTransformation/finiteDifferencing \
  src/midend/programTransformation/functionCallNormalization \
  src/midend/programTransformation/constantFolding \
  src/midend/programTransformation/implicitCodeGeneration \
  src/roseSupport \
  src/3rdPartyLibraries/MSTL \
  src/3rdPartyLibraries/json \
  src/midend/programTransformation/extractFunctionArgumentsNormalization \
  src/midend/programTransformation/singleStatementToBlockNormalization \
  src/frontend/Experimental_General_Language_Support \
  src/midend/programAnalysis/genericDataflow \
  src/midend/programAnalysis/genericDataflow/analysis \
  src/midend/programAnalysis/genericDataflow/arrIndexLabeler \
  src/midend/programAnalysis/genericDataflow/cfgUtils \
  src/midend/programAnalysis/genericDataflow/lattice \
  src/midend/programAnalysis/genericDataflow/simpleAnalyses \
  src/midend/programAnalysis/genericDataflow/rwAccessLabeler \
  src/midend/programAnalysis/genericDataflow/state \
  src/midend/programAnalysis/genericDataflow/variables \
  src/midend/programAnalysis/ssaUnfilteredCfg
