#!/bin/bash
# verify_win.sh <windows.exe> [tag]
#
# Cross-OS byte-identity for a MinGW build, run under wine.  Beyond what
# verify.sh does per-platform, this checks the thing that actually matters for a
# compressor shipped on two OSes: an archive written on one must decode on the
# other.  So for every case:
#
#   encode(win)  == encode(linux baseline)     byte-for-byte
#   decode(win,   archive written by win)      == plaintext
#   decode(win,   archive written by LINUX)    == plaintext
#   decode(linux, archive written by WIN)      == plaintext
#
# The last two are the cross-OS legs.  REF holds the pristine Linux baseline's
# archives (generated by verify.sh's setup).
set -u
EXE=${1:?usage: verify_win.sh <windows.exe> [tag]}
TAG=${2:-$(basename "$EXE")}
S=${S:-/tmp/claude-0/-home-user-pe2elf1/5e5d7486-4d33-5d0b-9606-ca56f9d55bc1/scratchpad}
W=${W:-$S/vfy}
REF=${REF:-$S/ref}
LINBIN=${LINBIN:-./paq8hpc}          # pristine Linux baseline
export WINEPREFIX=${WINEPREFIX:-$S/wineprefix} WINEDEBUG=-all
WINE=${WINE:-/usr/lib/wine/wine64}
fail=0

# wine startup is ~0.3 s per invocation and each case costs 4 of them, so this
# set is smaller than verify.sh's; L11 is dropped (4.5 GB under wine is slow).
CASES=${CASES:-"b300:0 b64k:4 b128k:6 b128k:8 b16k:1"}

for c in $CASES; do
  inp=${c%:*}; lvl=${c#*:}
  out=$S/win.$TAG.$inp.$lvl
  $WINE "$EXE" c "$W/$inp" "$out" "$lvl" >/dev/null 2>&1
  if [ ! -s "$out" ]; then echo "  FAIL($TAG) win encode $inp L$lvl: no output"; fail=1; continue; fi
  if ! cmp -s "$out" "$REF/$inp.$lvl"; then
    echo "  FAIL($TAG) win encode $inp L$lvl differs from Linux baseline"; fail=1; continue
  fi
  $WINE "$EXE" d "$out" "$out.d1" >/dev/null 2>&1
  cmp -s "$W/$inp" "$out.d1" || { echo "  FAIL($TAG) win round-trip $inp L$lvl"; fail=1; }
  $WINE "$EXE" d "$REF/$inp.$lvl" "$out.d2" >/dev/null 2>&1
  cmp -s "$W/$inp" "$out.d2" || { echo "  FAIL($TAG) win decoding LINUX archive $inp L$lvl"; fail=1; }
  "$LINBIN" d "$out" "$out.d3" >/dev/null 2>&1
  cmp -s "$W/$inp" "$out.d3" || { echo "  FAIL($TAG) linux decoding WIN archive $inp L$lvl"; fail=1; }
  rm -f "$out.d1" "$out.d2" "$out.d3"
done

[ $fail = 0 ] && echo "  ok($TAG) $(echo $CASES|wc -w) cases: win==linux bytes, win round-trip, win<-linux, linux<-win"
exit $fail
