#  Copyright (C) 2026 Kamila Szewczyk
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.

"""Fold the per-release dumps written by bookgen.c into ../vbooks_gen.inc.

Every release is a separate program -- two libvorbis copies cannot share one
address space -- so each writes a dump and this merges them.  Books are
interned by content, which is what makes carrying twenty releases affordable:
they overwhelmingly ship the same tables, and the ones that differ are what
the whole exercise is for.

Sets are keyed on the channel count and the book list alone.  The rate ranges
of every release agreeing on a list are unioned, so a set that four releases
produce over four adjoining ranges becomes one entry covering all of them, and
the encoder setting the release called it by drops out: two settings landing
on the same books are the same set as far as a stream is concerned.  What is
kept per set is where it came from, as a comment, because that is the only
thing a reader will want when a set turns out to be wrong."""

import sys, collections

books = []                       # content tuples, in first-seen order
book_id = {}                     # content -> index
sets = collections.OrderedDict() # (ch, booklist) -> [ranges, provenance]

def intern(content):
    i = book_id.get(content)
    if i is None:
        i = book_id[content] = len(books)
        books.append(content)
    return i

for path in sys.argv[1:]:
    lib, local, pending = '?', {}, []
    cur_id, cur = None, None

    def finish():
        #  a record is complete once its lengthlist and, if it has one, its
        #  quantlist have been read
        global cur_id, cur
        if cur is not None:
            local[cur_id] = intern(cur)
            cur_id, cur = None, None

    for line in open(path):
        f = line.split()
        if not f:
            continue
        if f[0] == 'lib':
            lib = f[1]
        elif f[0] == 'set':
            #  set <ch> <rate_lo> <rate_hi> <param> <n> <book>...
            n = int(f[5])
            assert len(f) == 6 + n, line
            pending.append((int(f[1]), int(f[2]), int(f[3]), f[4],
                            tuple(int(x) for x in f[6:])))
        elif f[0] == 'book':
            #  book <id> <dim> <entries> <maptype> <qmin> <qdelta> <qquant> <qseq>
            finish()
            cur_id = int(f[1])
            cur = tuple(int(x) for x in f[2:9])
        elif f[0] == 'l':
            cur = cur + (tuple(int(x) for x in f[1:]),)
        elif f[0] == 'q':
            cur = cur + (tuple(int(x) for x in f[1:]),)
            finish()
        else:
            raise SystemExit('bad line in %s: %r' % (path, line))
        if f[0] == 'l' and cur[2] == 0:      # maptype 0: no quantlist follows
            cur = cur + ((),)
            finish()
    finish()

    for ch, lo, hi, param, bl in pending:
        key = (ch, tuple(local[b] for b in bl))
        e = sets.setdefault(key, [[], []])
        e[0].append((lo, hi))
        e[1].append('%s %s' % (lib, param))

def union(rs):
    out = []
    for lo, hi in sorted(rs):
        if out and lo <= out[-1][1] + 1: out[-1][1] = max(out[-1][1], hi)
        else: out.append([lo, hi])
    return out

#  one table entry per (ch, books, contiguous rate range)
rows = []
for (ch, bl), (ranges, prov) in sets.items():
    who = []
    for p in prov:
        lib = p.split()[0]
        if lib not in who: who.append(lib)
    #  a set most releases agree on would otherwise print thirty names
    tag = ' '.join(who[:3]) + ('' if len(who) <= 3 else ' +%d' % (len(who) - 3))
    for lo, hi in union(ranges):
        rows.append((ch, lo, hi, bl, tag))
rows.sort(key=lambda r: (r[0], r[1], r[2]))

idx, first = [], []
for ch, lo, hi, bl, who in rows:
    first.append(len(idx));  idx.extend(bl)

w = sys.stdout.write
w('/*  Generated by psyfit/bookdump.sh -- do not edit.\n'
  '    %d distinct codebooks, %d sets, %d index entries,\n'
  '    from %d encoders.  */\n'
  % (len(books), len(rows), len(idx), len(sys.argv) - 1))

for i, b in enumerate(books):
    dim, ent, maptype, qmin, qdelta, qquant, qseq, ll, ql = b
    if ll:
        w('static const char vg_l%d[] = {%s};\n' % (i, ','.join(map(str, ll))))
    if maptype:
        w('static const long vg_q%d[] = {%s};\n' % (i, ','.join(map(str, ql))))

w('static const vg_book vg_books[%d] = {\n' % len(books))
for i, b in enumerate(books):
    dim, ent, maptype, qmin, qdelta, qquant, qseq, ll, ql = b
    w('  {%d,%d,%s,%d,%d,%d,%d,%d,%s},\n'
      % (dim, ent, ('vg_l%d' % i) if ll else '0', maptype, qmin, qdelta,
         qquant, qseq, ('vg_q%d' % i) if maptype else '0'))
w('};\n')

w('static const unsigned short vg_idx[%d] = {%s};\n'
  % (len(idx), ','.join(map(str, idx))))

w('static const vg_set vg_sets[%d] = {\n' % len(rows))
for (ch, lo, hi, bl, who), fi in zip(rows, first):
    w('  {%d,%d,%d,%d,%d},  /*  %s  */\n' % (ch, lo, hi, len(bl), fi, who))
w('};\n')

sys.stderr.write('%d books, %d sets, %d idx\n' % (len(books), len(rows), len(idx)))
