

static const int I_LW = (32764+0) * (1);
static const int I_W0 = (13824+0) * (1);
static const int I_Pmin = (3072+0) * (1);
static const int I_Wclip = (1024+0) * (1);
static const int I_W_M1 = (192520+0) * (1);
static const int I_W_M2 = (6144+0) * (1);
static const int I_W_NW = (261123+0) * (1);
static const int I_W_INC = (78532+0) * (1);
static const int I_W_STEP = (51328+0) * (1);
static const int I_W_G2 = (32+0) * (1);
static const int I_W_D_CLIP = (16000+0) * (1);
static const int I_W_R_CLIP = (18692+0) * (1);



struct I_T { 
#undef USE_NEW
#define USE_NEW 0


  
  void I_Init( void ) {
  
  }
  void I_Quit( void ) {
  }
};
