// Auto-generated by `zipcl g`: a ZipCrypto key-recovery model for CBMC.
// SPREAD variant: 8 unknown bits in the low byte of EACH of k0,k1,k2 (24 total),
// (and the crc-derived header check byte). Real key:
//   k0=A3E30892 k1=F9185194 k2=EB474B09  ->  UNK = k2lo<<16|k1lo<<8|k0lo = 0x099492
typedef unsigned int uint; typedef unsigned char byte;
#define MASK 0x00FFFFFFu
#define KM 0xFFu          // per-key low-byte mask
// ZipCrypto's CRC32(crc,b) is the standard reflected CRC32 single-byte update,
// emitted bitwise (not table-driven) so its GF(2)-linear structure stays
// visible to the SAT solver -- a 256-entry symbolic table lookup is far harder.
uint CRC32(uint crc, byte b){ crc^=b; for(int k=0;k<8;k++) crc=(crc>>1)^(0xEDB88320u&(0u-(crc&1u))); return crc; }
uint k0,k1,k2;
void update_keys(byte c){k0=CRC32(k0,c);k1=(k1+(k0&0xffu))*134775813u+1u;k2=CRC32(k2,(byte)(k1>>24));}
byte decrypt_byte(){uint t=(k2&0xffffu)|2u;return (byte)((t*(t^1u))>>8);}
extern uint UNK;          // nondeterministic: the SAT solver fills this in
int main(){
  __CPROVER_assume((UNK & ~MASK)==0u);   // only the low 24 bit(s) are free
  // file 0: uSize=4852 cSize=1530 crc=19CFF2AC  -> BFINAL=1 BTYPE=10
  k0=(0xA3E30892u&~KM)|(UNK&KM); k1=(0xF9185194u&~KM)|((UNK>>8)&KM); k2=(0xEB474B09u&~KM)|((UNK>>16)&KM);
  { static const byte ct[13]={0x96,0x44,0xE6,0xB2,0x44,0xE0,0xEC,0xDF,0x3C,0x8D,0xA9,0x3A,0xBC}; byte pt=0;
    for(int i=0;i<12;i++){ pt=ct[i]^decrypt_byte(); update_keys(pt); }
    __CPROVER_assume(pt==0x19u);              // crc check byte
    byte b0=ct[12]^decrypt_byte();
    __CPROVER_assume((b0&7u)==5u);             // deflate BFINAL|BTYPE
  }
  // file 1: uSize=847 cSize=412 crc=FE89BDB9  -> BFINAL=1 BTYPE=10
  k0=(0xA3E30892u&~KM)|(UNK&KM); k1=(0xF9185194u&~KM)|((UNK>>8)&KM); k2=(0xEB474B09u&~KM)|((UNK>>16)&KM);
  { static const byte ct[13]={0x01,0x60,0x71,0xF0,0xE8,0xCE,0xB7,0x5A,0x26,0x58,0xDE,0xA0,0x9C}; byte pt=0;
    for(int i=0;i<12;i++){ pt=ct[i]^decrypt_byte(); update_keys(pt); }
    __CPROVER_assume(pt==0xFEu);              // crc check byte
    byte b0=ct[12]^decrypt_byte();
    __CPROVER_assume((b0&7u)==5u);             // deflate BFINAL|BTYPE
  }
  // file 2: uSize=4783 cSize=1547 crc=EFEAC857  -> BFINAL=1 BTYPE=10
  k0=(0xA3E30892u&~KM)|(UNK&KM); k1=(0xF9185194u&~KM)|((UNK>>8)&KM); k2=(0xEB474B09u&~KM)|((UNK>>16)&KM);
  { static const byte ct[13]={0xF8,0x5B,0x3E,0x8F,0x03,0xDF,0x9A,0x5B,0x6D,0xE9,0xDA,0x0E,0x7E}; byte pt=0;
    for(int i=0;i<12;i++){ pt=ct[i]^decrypt_byte(); update_keys(pt); }
    __CPROVER_assume(pt==0xEFu);              // crc check byte
    byte b0=ct[12]^decrypt_byte();
    __CPROVER_assume((b0&7u)==5u);             // deflate BFINAL|BTYPE
  }
  match: {}   // reachable iff UNK is consistent with every file's known plaintext
  return 0;
}
