// Auto-generated by `zipcl g`: a ZipCrypto key-recovery model for CBMC.
// Recover the low 8 bit(s) of k0 from known-plaintext deflate-header bits
// (and the crc-derived header check byte). Real key:
//   k0=A3E30892 k1=F9185194 k2=EB474B09  ->  unknown bits = 00000092
typedef unsigned int uint; typedef unsigned char byte;
#define MASK 0x000000FFu
// ZipCrypto's CRC32(crc,b) is the standard reflected CRC32 single-byte update,
// emitted bitwise (not table-driven) so its GF(2)-linear structure stays
// visible to the SAT solver -- a 256-entry symbolic table lookup is far harder.
uint CRC32(uint crc, byte b){ crc^=b; for(int k=0;k<8;k++) crc=(crc>>1)^(0xEDB88320u&(0u-(crc&1u))); return crc; }
uint k0,k1,k2;
void update_keys(byte c){k0=CRC32(k0,c);k1=(k1+(k0&0xffu))*134775813u+1u;k2=CRC32(k2,(byte)(k1>>24));}
byte decrypt_byte(){uint t=(k2&0xffffu)|2u;return (byte)((t*(t^1u))>>8);}
extern uint UNK;          // nondeterministic: the SAT solver fills this in
uint CL(byte*b,uint p){ uint q=p>>3,r=p&7; return ((b[q]>>r)|(b[q+1]<<(8-r)))&7u; } // 3-bit field @ bit p
int main(){
  __CPROVER_assume((UNK & ~MASK)==0u);   // only the low 8 bit(s) are free
  // file 0: uSize=4852 cSize=1530 crc=19CFF2AC  -> BFINAL=1 BTYPE=10
  k0=(0xA3E30892u&~MASK)|(UNK&MASK); k1=0xF9185194u; k2=0xEB474B09u;
  { static const byte ct[24]={0x96,0x44,0xE6,0xB2,0x44,0xE0,0xEC,0xDF,0x3C,0x8D,0xA9,0x3A,0xBC,0x5A,0x9D,0x4B,0x98,0x1B,0xA4,0xC4,0x64,0xD4,0xCF,0xFD}; byte b[12]; byte pt=0;
    for(int i=0;i<12;i++){ pt=ct[i]^decrypt_byte(); update_keys(pt); }
    for(int i=0;i<12;i++){ b[i]=ct[12+i]^decrypt_byte(); update_keys(b[i]); }
    __CPROVER_assume((b[0]&7u)==5u);                // deflate BFINAL|BTYPE
    __CPROVER_assume(((b[0]>>3)&0x1Fu)<=29u);        // nlen = HLIT+257 <= 286
    __CPROVER_assume((b[1]&0x1Fu)<=29u);             // ndist = HDIST+1 <= 30
    uint ncode=(((b[1]>>5)&7u)|((b[2]&1u)<<3))+4u;   // HCLEN+4
    uint kraft=0;
    for(int j=0;j<19;j++){ uint cl=CL(b,17u+3u*(uint)j); if((uint)j<ncode && cl>0u) kraft+=(128u>>cl); }
    __CPROVER_assume(kraft==128u);                   // code-length code is complete
  }
  match: {}   // reachable iff UNK is consistent with every file's known plaintext
  return 0;
}
