// Auto-generated by `zipcl g ... reverse`: REVERSE ZipCrypto key-recovery model.
// The free variables are each file's key state at the start of its body (S[]).
// We run the cipher BACKWARD through the 12-byte header; the recovered initial
// state must equal the known key, whose low 16 bit(s) are left free = answer UNK.
//   k0=A3E30892 k1=F9185194 k2=EB474B09  ->  unknown bits = 00000892
typedef unsigned int uint; typedef unsigned char byte;
#define MASK 0x0000FFFFu
#define MINV 0xD94FA8CDu      // (134775813)^-1 mod 2^32, inverts the k1 step
// inverse of the standard reflected CRC32 single-byte update (8 rounds undone):
uint CRC32inv(uint x, byte b){ for(int k=0;k<8;k++){ uint t=x>>31; x=((x^(t?0xEDB88320u:0u))<<1)|t; } return x^b; }
byte decrypt_byte(uint k2){ uint t=(k2&0xffffu)|2u; return (byte)((t*(t^1u))>>8); }
extern uint UNK;            // recovered low key bit(s) -- the answer
extern uint S[6];          // free: each file's key state at its body start
int main(){
  __CPROVER_assume((UNK & ~MASK)==0u);
  // file 0: uSize=4852 cSize=1530 crc=19CFF2AC  -> BFINAL=1 BTYPE=10
  { uint a0=S[0], a1=S[1], a2=S[2];           // free state at body start
    static const byte ct[13]={0x96,0x44,0xE6,0xB2,0x44,0xE0,0xEC,0xDF,0x3C,0x8D,0xA9,0x3A,0xBC};
    __CPROVER_assume(((ct[12]^decrypt_byte(a2))&7u)==5u);  // deflate (body-start k2)
    byte pt11=0;
    for(int i=11;i>=0;i--){                       // undo the 12 header updates
      uint b2=CRC32inv(a2,(byte)(a1>>24));
      byte c=ct[i]^decrypt_byte(b2);              // recovered header plaintext byte
      uint b1=(a1-1u)*MINV-(a0&0xffu);
      uint b0=CRC32inv(a0,c);
      if(i==11) pt11=c;
      a0=b0; a1=b1; a2=b2;
    }
    __CPROVER_assume(pt11==0x19u);                      // crc check byte
    __CPROVER_assume(a1==0xF9185194u);                  // recovered init must equal
    __CPROVER_assume(a2==0xEB474B09u);                  // the known key ...
    __CPROVER_assume((a0 & ~MASK)==(0xA3E30892u & ~MASK));
    __CPROVER_assume((a0 & MASK)==(UNK & MASK));    // ... and exposes UNK
  }
  // file 1: uSize=847 cSize=412 crc=FE89BDB9  -> BFINAL=1 BTYPE=10
  { uint a0=S[3], a1=S[4], a2=S[5];           // free state at body start
    static const byte ct[13]={0x01,0x60,0x71,0xF0,0xE8,0xCE,0xB7,0x5A,0x26,0x58,0xDE,0xA0,0x9C};
    __CPROVER_assume(((ct[12]^decrypt_byte(a2))&7u)==5u);  // deflate (body-start k2)
    byte pt11=0;
    for(int i=11;i>=0;i--){                       // undo the 12 header updates
      uint b2=CRC32inv(a2,(byte)(a1>>24));
      byte c=ct[i]^decrypt_byte(b2);              // recovered header plaintext byte
      uint b1=(a1-1u)*MINV-(a0&0xffu);
      uint b0=CRC32inv(a0,c);
      if(i==11) pt11=c;
      a0=b0; a1=b1; a2=b2;
    }
    __CPROVER_assume(pt11==0xFEu);                      // crc check byte
    __CPROVER_assume(a1==0xF9185194u);                  // recovered init must equal
    __CPROVER_assume(a2==0xEB474B09u);                  // the known key ...
    __CPROVER_assume((a0 & ~MASK)==(0xA3E30892u & ~MASK));
    __CPROVER_assume((a0 & MASK)==(UNK & MASK));    // ... and exposes UNK
  }
  match: {}   // reachable iff UNK is consistent with every file's known plaintext
  return 0;
}
