#!/usr/bin/env python3
# rc_iftree.inc -- the decoder's byte as a 255-node tree of static branch sites.
# Generated, like rc_vecD.inc; not committed.
#
# One node per context, so cty[c] is a compile-time address and every node gets
# its own predictor entry.  The eight bits of a byte live in eight INDEPENDENT
# lanes (byte m's bit j is lane m*8+j), so their code/range are all known when
# the byte starts and the renorms are hoisted out; inside the tree the only
# serial edge is the context itself, which is what the predictor runs ahead of.
#
# The tree does NOTHING but pick the bits. Each node loads its counter, forms
# rpre = (range>>SCALElog)*p, stores it into IFT_PRE[] and branches on the
# compare -- the multiply has to be inside the branch structure because the
# frequency is what the context selects. The range/rpre update and the renorm
# are batched after the walk, over the lane arrays, where they vectorize; the
# leaf carries every bit the batch needs (bit d is (IFT_SYM>>(7-d))&1).
#
# The counter UPDATES are not in the tree either. Each node would need a dependent
# load from FSM2 and a store, which roughly doubles the node and put the two
# trees at 50 KB against a 32 KB L1i -- measured 0.58x. They are replayed after
# the leaf instead: the leaf IS the path, node d is IFT_SYM>>(8-d) and its bit
# is (IFT_SYM>>(7-d))&1, and a counter is touched once per byte so re-reading
# its state after the walk reads the same state the walk saw.
#
# The base lane comes in as IFT_B and the byte goes out in IFT_SYM, so the
# includer instantiates it once per byte of the group with a literal base --
# which is what keeps the lane arrays at constant indices.  See
# misc/iftree_lanes.md.
import sys
DEPTH = int(sys.argv[2]) if len(sys.argv)>2 else 8
def emit(c, depth, out):
    ind = '  '*(depth+1)
    L = f'IFT_B+{depth}'
    out.append(f'{ind}IFT_PRE[{depth}] = (range[{L}]>>SCALElog) * t_Counter::P(cty[{c}].Get());')
    out.append(f'{ind}if( code[{L}] >= IFT_PRE[{depth}] ) {{')
    if depth == DEPTH-1: out.append(f'{ind}  IFT_SYM = {2*c+1};')
    else:                emit(2*c+1, depth+1, out)
    out.append(f'{ind}}} else {{')
    if depth == DEPTH-1: out.append(f'{ind}  IFT_SYM = {2*c};')
    else:                emit(2*c, depth+1, out)
    out.append(f'{ind}}}')
out = ['/*  generated by mk_iftree.py -- do not edit.  See misc/iftree_lanes.md. */',
       '/*  The includer defines IFT_B (the group\'s base lane, a literal) and */',
       '/*  IFT_SYM (where the byte lands), and has already renormalised the   */',
       '/*  eight lanes IFT_B..IFT_B+7.                                        */']
if DEPTH>0: emit(1, 0, out)
else: out.append('  IFT_SYM = 1;')
open(sys.argv[1] if len(sys.argv)>1 else 'rc_iftree.inc','w').write('\n'.join(out)+'\n')
print(f'mk_iftree.py: depth {DEPTH}, {2**DEPTH-1} nodes ->', sys.argv[1] if len(sys.argv)>1 else 'rc_iftree.inc',
      f'({len(out)} lines)')
