

// bmf.cpp — BMF, the whole program, as one translation unit.
//
// BMF 2.01 by Dmitry Shkarin, recovered from the 32-bit Windows binary: 143
// functions decompiled with Hex-Rays and corrected against the disassembly
// until the compressed streams came out bit-for-bit identical to the
// original's on every test image.  See README.md.
//
// One translation unit because the bodies are not independent: they share
// globals by address (blob.inc), several are entered through calling
// conventions that only exist inside a file (thiscall, fastcall), and the
// order below is callees-before-callers so that a call to an already-defined
// body needs no forward declaration.  Splitting it up would buy nothing and
// cost all of that.
//
// Generated by incdec/bmf/standalone/mkbmfc.py.  Do not edit.

// Selects the standalone half of bmfhead.h and of each body: no redirects
// into a loaded BMF.exe, no entry-point thunks for callers that no longer
// exist, no call-count probes.
#define BMF_STANDALONE 1

// blob.inc was here: BMF.exe's data segment as one generated array, 343 794
// bytes of it.  What survived is `bmf_bss` in subs1.hpp -- 19 584 zero bytes,
// which is what the surviving globals actually need.
//--- #include "bmfhead.h"    // Hex-Rays' type vocabulary, SSE wrappers, defs.h
// bmfhead.h — the vocabulary the decompiled bodies are written in.
//
// Generated from incdec/bmf/dummy32_head.cpp by incdec/bmf/standalone/
// mkbmfc.py, with the conditionals for the injected build evaluated out.
// Do not edit: change the original and re-run the generator.

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <cmath>
#include <cctype>     // isspace/isdigit/toupper — §6.5 lets these fall through
#include <cstdarg>
// The last intrinsic is gone; M128 below is a plain union and needs no header.
// These two are still here for the MXCSR mode bits alone -- flush-to-zero and
// denormals-are-zero, which main sets and the float results depend on.
#include <xmmintrin.h>   // _MM_SET_FLUSH_ZERO_MODE
#include <pmmintrin.h>   // _MM_SET_DENORMALS_ZERO_MODE

// ---------------------------------------------------------------------------
// Hex-Rays type vocabulary.
//
// This is Hex-Rays' own defs.h, verbatim — the same header BMF.cpp's `#include
// <defs.h>` refers to — rather than a hand-rolled subset.  It brings LOBYTE /
// BYTEn / WORDn / SBYTEn / __ROLn__ / __RORn__ / __PAIRn__ / abs32 / qmemcpy /
// COERCE_* / _UNKNOWN and the __intN aliases, all with the exact semantics the
// decompiler assumed when it emitted them.
//
// BMF.cpp's other include, <windows.h>, is deliberately not used on any
// target, and nothing here needs it any more: no body names a Win32 type, a
// Win32 constant or a Win32 function.
//
// defs.h does not know that, though: `#ifndef _WINDOWS_` it defines
// BYTE/WORD/DWORD/LONG/BOOL itself, and as *signed* types (`typedef int8
// BYTE`, int8 being plain char), which is the opposite of what windows.h
// means by them.  Nothing spells those names now — the bodies say uint8_t and
// uint32_t — so rather than supply a second wrong set, declare _WINDOWS_ and
// let there be none: a body that grew a `BYTE` back would then fail to
// compile instead of quietly sign-extending.
// ---------------------------------------------------------------------------
#define _WINDOWS_

//--- #include "bmfdefs.h"
/*

   This file contains definitions used in the Hex-Rays decompiler output.
   It has type definitions and convenience macros to make the
   output more readable.

   Copyright (c) 2007-2025 Hex-Rays

*/

#ifndef HEXRAYS_DEFS_H
#define HEXRAYS_DEFS_H

#if defined(__GNUC__)
  typedef          long long ll;
  typedef unsigned long long ull;
  #define __int64 long long
  #define __int32 int
  #define __int16 short
  #define __int8  char
  #define MAKELL(num) num ## LL
  #define FMT_64 "ll"
#elif defined(_MSC_VER)
  typedef          __int64 ll;
  typedef unsigned __int64 ull;
  #define MAKELL(num) num ## i64
  #define FMT_64 "I64"
#elif defined (__BORLANDC__)
  typedef          __int64 ll;
  typedef unsigned __int64 ull;
  #define MAKELL(num) num ## i64
  #define FMT_64 "L"
#else
  #error "unknown compiler"
#endif
typedef unsigned int uint;
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned long ulong;

typedef          char   int8;
typedef   signed char   sint8;
typedef unsigned char   uint8;
typedef          short  int16;
typedef   signed short  sint16;
typedef unsigned short  uint16;
typedef          int    int32;
typedef   signed int    sint32;
typedef unsigned int    uint32;
typedef ll              int64;
typedef ll              sint64;
typedef ull             uint64;

// Partially defined types. They are used when the decompiler does not know
// anything about the type except its size.
#define _BYTE  uint8
#define _WORD  uint16
#define _DWORD uint32
#define _QWORD uint64
#if !defined(_MSC_VER)
#define _LONGLONG __int128
#endif

// Non-standard boolean types. They are used when the decompiler cannot use
// the standard "bool" type because of the size mistmatch but the possible
// values are only 0 and 1. See also 'BOOL' type below.
typedef int8 _BOOL1;
typedef int16 _BOOL2;
typedef int32 _BOOL4;
typedef int64 _BOOL8;

#ifndef _WINDOWS_
typedef int8 BYTE;
typedef int16 WORD;
typedef int32 DWORD;
typedef int32 LONG;
typedef int BOOL;       // uppercase BOOL is usually 4 bytes
#endif
typedef int64 QWORD;
#ifndef __cplusplus
typedef int bool;       // we want to use bool in our C programs
#endif

#ifndef __pure
// a modern gcc defines __pure as '__attribute__((__pure__))'
#define __pure  // pure function:
                // when given the same arguments, always returns the same value
                // has no side effects
#endif

// Non-returning function
#if defined(__GNUC__)
#define __noreturn  __attribute__((noreturn))
#else
#define __noreturn  __declspec(noreturn)
#endif


#ifndef NULL
#define NULL 0
#endif

// Some convenience macros to make partial accesses nicer
#define LAST_IND(x,part_type)    (sizeof(x)/sizeof(part_type) - 1)
#if defined(__BYTE_ORDER) && __BYTE_ORDER == __BIG_ENDIAN
#  define LOW_IND(x,part_type)   LAST_IND(x,part_type)
#  define HIGH_IND(x,part_type)  0
#else
#  define HIGH_IND(x,part_type)  LAST_IND(x,part_type)
#  define LOW_IND(x,part_type)   0
#endif
// first unsigned macros:
#define BYTEn(x, n)   (*((_BYTE*)&(x)+n))
#define WORDn(x, n)   (*((_WORD*)&(x)+n))
#define DWORDn(x, n)  (*((_DWORD*)&(x)+n))

#define LOBYTE(x)  BYTEn(x,LOW_IND(x,_BYTE))
#define LOWORD(x)  WORDn(x,LOW_IND(x,_WORD))
#define LODWORD(x) DWORDn(x,LOW_IND(x,_DWORD))
#define HIBYTE(x)  BYTEn(x,HIGH_IND(x,_BYTE))
#define HIWORD(x)  WORDn(x,HIGH_IND(x,_WORD))
#define HIDWORD(x) DWORDn(x,HIGH_IND(x,_DWORD))
#define BYTE1(x)   BYTEn(x,  1)         // byte 1 (counting from 0)
#define BYTE2(x)   BYTEn(x,  2)
#define BYTE3(x)   BYTEn(x,  3)
#define BYTE4(x)   BYTEn(x,  4)
#define BYTE5(x)   BYTEn(x,  5)
#define BYTE6(x)   BYTEn(x,  6)
#define BYTE7(x)   BYTEn(x,  7)
#define BYTE8(x)   BYTEn(x,  8)
#define BYTE9(x)   BYTEn(x,  9)
#define BYTE10(x)  BYTEn(x, 10)
#define BYTE11(x)  BYTEn(x, 11)
#define BYTE12(x)  BYTEn(x, 12)
#define BYTE13(x)  BYTEn(x, 13)
#define BYTE14(x)  BYTEn(x, 14)
#define BYTE15(x)  BYTEn(x, 15)
#define WORD1(x)   WORDn(x,  1)
#define WORD2(x)   WORDn(x,  2)         // third word of the object, unsigned
#define WORD3(x)   WORDn(x,  3)
#define WORD4(x)   WORDn(x,  4)
#define WORD5(x)   WORDn(x,  5)
#define WORD6(x)   WORDn(x,  6)
#define WORD7(x)   WORDn(x,  7)

// now signed macros (the same but with sign extension)
#define SBYTEn(x, n)   (*((int8*)&(x)+n))
#define SWORDn(x, n)   (*((int16*)&(x)+n))
#define SDWORDn(x, n)  (*((int32*)&(x)+n))

#define SLOBYTE(x)  SBYTEn(x,LOW_IND(x,int8))
#define SLOWORD(x)  SWORDn(x,LOW_IND(x,int16))
#define SLODWORD(x) SDWORDn(x,LOW_IND(x,int32))
#define SHIBYTE(x)  SBYTEn(x,HIGH_IND(x,int8))
#define SHIWORD(x)  SWORDn(x,HIGH_IND(x,int16))
#define SHIDWORD(x) SDWORDn(x,HIGH_IND(x,int32))
#define SBYTE1(x)   SBYTEn(x,  1)
#define SBYTE2(x)   SBYTEn(x,  2)
#define SBYTE3(x)   SBYTEn(x,  3)
#define SBYTE4(x)   SBYTEn(x,  4)
#define SBYTE5(x)   SBYTEn(x,  5)
#define SBYTE6(x)   SBYTEn(x,  6)
#define SBYTE7(x)   SBYTEn(x,  7)
#define SBYTE8(x)   SBYTEn(x,  8)
#define SBYTE9(x)   SBYTEn(x,  9)
#define SBYTE10(x)  SBYTEn(x, 10)
#define SBYTE11(x)  SBYTEn(x, 11)
#define SBYTE12(x)  SBYTEn(x, 12)
#define SBYTE13(x)  SBYTEn(x, 13)
#define SBYTE14(x)  SBYTEn(x, 14)
#define SBYTE15(x)  SBYTEn(x, 15)
#define SWORD1(x)   SWORDn(x,  1)
#define SWORD2(x)   SWORDn(x,  2)
#define SWORD3(x)   SWORDn(x,  3)
#define SWORD4(x)   SWORDn(x,  4)
#define SWORD5(x)   SWORDn(x,  5)
#define SWORD6(x)   SWORDn(x,  6)
#define SWORD7(x)   SWORDn(x,  7)

// Generate a pair of operands. S stands for 'signed'
#define __SPAIR16__(high, low)  (((int16)  (high) <<  8) | (uint8) (low))
#define __SPAIR32__(high, low)  (((int32)  (high) << 16) | (uint16)(low))
#define __SPAIR64__(high, low)  (((int64)  (high) << 32) | (uint32)(low))
#define __SPAIR128__(high, low) (((int128) (high) << 64) | (uint64)(low))
#define __PAIR16__(high, low)   (((uint16) (high) <<  8) | (uint8) (low))
#define __PAIR32__(high, low)   (((uint32) (high) << 16) | (uint16)(low))
#define __PAIR64__(high, low)   (((uint64) (high) << 32) | (uint32)(low))
#define __PAIR128__(high, low)  (((uint128)(high) << 64) | (uint64)(low))

// Helper functions to represent some assembly instructions.

#ifdef __cplusplus

// compile time assertion
#define __CASSERT_N0__(l) COMPILE_TIME_ASSERT_ ## l
#define __CASSERT_N1__(l) __CASSERT_N0__(l)
#define CASSERT(cnd) typedef char __CASSERT_N1__(__LINE__) [(cnd) ? 1 : -1]

// check that unsigned multiplication does not overflow
template<class T> bool is_mul_ok(T count, T elsize)
{
  CASSERT(T(-1) > 0); // make sure T is unsigned
  if ( elsize == 0 || count == 0 )
    return true;
  return count <= T(-1) / elsize;
}

// multiplication that saturates (yields the biggest value) instead of overflowing
// such a construct is useful in "operator new[]"
template<class T> bool saturated_mul(T count, T elsize)
{
  return is_mul_ok(count, elsize) ? count * elsize : T(-1);
}

#include <stddef.h> // for size_t

// memcpy() with determined behavoir: it always copies
// from the start to the end of the buffer
// note: it copies byte by byte, so it is not equivalent to, for example, rep movsd
inline void *qmemcpy(void *dst, const void *src, size_t cnt)
{
  char *out = (char *)dst;
  const char *in = (const char *)src;
  while ( cnt > 0 )
  {
    *out++ = *in++;
    --cnt;
  }
  return dst;
}

// rotate left
template<class T> T __ROL__(T value, int count)
{
  const uint nbits = sizeof(T) * 8;

  if ( count > 0 )
  {
    count %= nbits;
    T high = value >> (nbits - count);
    if ( T(-1) < 0 ) // signed value
      high &= ~((T(-1) << count));
    value <<= count;
    value |= high;
  }
  else
  {
    count = -count % nbits;
    T low = value << (nbits - count);
    value >>= count;
    value |= low;
  }
  return value;
}

inline uint8  __ROL1__(uint8  value, int count) { return __ROL__((uint8)value, count); }
inline uint16 __ROL2__(uint16 value, int count) { return __ROL__((uint16)value, count); }
inline uint32 __ROL4__(uint32 value, int count) { return __ROL__((uint32)value, count); }
inline uint64 __ROL8__(uint64 value, int count) { return __ROL__((uint64)value, count); }
inline uint8  __ROR1__(uint8  value, int count) { return __ROL__((uint8)value, -count); }
inline uint16 __ROR2__(uint16 value, int count) { return __ROL__((uint16)value, -count); }
inline uint32 __ROR4__(uint32 value, int count) { return __ROL__((uint32)value, -count); }
inline uint64 __ROR8__(uint64 value, int count) { return __ROL__((uint64)value, -count); }

// sign flag
template<class T> int8 __SETS__(T x)
{
  if ( sizeof(T) == 1 )
    return int8(x) < 0;
  if ( sizeof(T) == 2 )
    return int16(x) < 0;
  if ( sizeof(T) == 4 )
    return int32(x) < 0;
  return int64(x) < 0;
}

// overflow flag of subtraction (x-y)
template<class T, class U> int8 __OFSUB__(T x, U y)
{
  if ( sizeof(T) < sizeof(U) )
  {
    U x2 = x;
    int8 sx = __SETS__(x2);
    return (sx ^ __SETS__(y)) & (sx ^ __SETS__(U(x2-y)));
  }
  else
  {
    T y2 = y;
    int8 sx = __SETS__(x);
    return (sx ^ __SETS__(y2)) & (sx ^ __SETS__(T(x-y2)));
  }
}

// overflow flag of addition (x+y)
template<class T, class U> int8 __OFADD__(T x, U y)
{
  if ( sizeof(T) < sizeof(U) )
  {
    U x2 = x;
    int8 sx = __SETS__(x2);
    return ((1 ^ sx) ^ __SETS__(y)) & (sx ^ __SETS__(U(x2+y)));
  }
  else
  {
    T y2 = y;
    int8 sx = __SETS__(x);
    return ((1 ^ sx) ^ __SETS__(y2)) & (sx ^ __SETS__(T(x+y2)));
  }
}

// https://en.wikipedia.org/wiki/Carry_flag#Carry_flag_vs._borrow_flag
#if defined(__ARM__) || defined(__PPC__)
#define SUB_WITH_CARRY 1
#else
#define SUB_WITH_CARRY 0
#endif

// carry flag of subtraction (x-y)
template<class T, class U> int8 __CFSUB__(T x, U y)
{
  int size = sizeof(T) > sizeof(U) ? sizeof(T) : sizeof(U);
  bool res;
  if ( size == 1 )
    res = uint8(x) < uint8(y);
  else if ( size == 2 )
    res = uint16(x) < uint16(y);
  else if ( size == 4 )
    res = uint32(x) < uint32(y);
  else
    res = uint64(x) < uint64(y);
#if SUB_WITH_CARRY
  res = !res;
#endif
  return res;
}

// carry flag of addition (x+y)
template<class T, class U> int8 __CFADD__(T x, U y)
{
  int size = sizeof(T) > sizeof(U) ? sizeof(T) : sizeof(U);
  if ( size == 1 )
    return uint8(x) > uint8(x+y);
  if ( size == 2 )
    return uint16(x) > uint16(x+y);
  if ( size == 4 )
    return uint32(x) > uint32(x+y);
  return uint64(x) > uint64(x+y);
}

// carry flag of subtraction with carry
template<class T, class U> int8 __CFSUB__(T x, U y, int8 cf)
{
#if SUB_WITH_CARRY
  cf = !cf;
#endif
  return __CFADD__(y, cf) ^ __CFSUB(x, y + cf);
}

// overflow flag of subtraction with carry
template<class T, class U> int8 __OFSUB__(T x, U y, int8 cf)
{
#if SUB_WITH_CARRY
  cf = !cf;
#endif
  return __OFADD__(y, cf) ^ __OFSUB(x, y + cf);
}

inline uint8   abs8(int8     x) { return x >= 0 ? x : -x; }
inline uint16  abs16(int16   x) { return x >= 0 ? x : -x; }
inline uint32  abs32(int32   x) { return x >= 0 ? x : -x; }
inline uint64  abs64(int64   x) { return x >= 0 ? x : -x; }
//inline uint128 abs128(int128 x) { return x >= 0 ? x : -x; }

#include <string.h>     // for memcpy
#include <type_traits>  // for enable_if

template <typename T, typename F>
inline typename std::enable_if<sizeof(T) <= sizeof(F), T>::type __coerce(F f)
{
  T t;
  memcpy(&t, &f, sizeof(T));
  return t;
}
#define COERCE_FLOAT(v) __coerce<float>(v)
#define COERCE_DOUBLE(v) __coerce<double>(v)
#define COERCE_LONG_DOUBLE(v) __coerce<long double>(v)
#define COERCE_UNSIGNED_INT(v) __coerce<unsigned int>(v)
#define COERCE_UNSIGNED_INT64(v) __coerce<uint64>(v)

#else // C++
// For C, we just provide macros, they are not quite correct.
#define __ROL__(x, y) __rotl__(x, y)      // Rotate left
#define __ROR__(x, y) __rotr__(x, y)      // Rotate right
#define __CFSHL__(x, y) invalid_operation // Generate carry flag for (x<<y)
#define __CFSHR__(x, y) invalid_operation // Generate carry flag for (x>>y)
#define __CFADD__(x, y) invalid_operation // Generate carry flag for (x+y)
#define __CFSUB__(x, y) invalid_operation // Generate carry flag for (x-y)
#define __OFADD__(x, y) invalid_operation // Generate overflow flag for (x+y)
#define __OFSUB__(x, y) invalid_operation // Generate overflow flag for (x-y)

#define abs8(x)   (int8)  ((int8)  (x) >= 0 ? (x) : -(x))
#define abs16(x)  (int16) ((int16) (x) >= 0 ? (x) : -(x))
#define abs32(x)  (int32) ((int32) (x) >= 0 ? (x) : -(x))
#define abs64(x)  (int64) ((int64) (x) >= 0 ? (x) : -(x))
#define abs128(x) (int128)((int128)(x) >= 0 ? (x) : -(x))

#endif // C++

#if defined(__MIPS__)
// traps for MIPS arithmetic operation
void __noreturn __integer_oveflow(void); // SIGFPE/FPE_INTOVF
void __noreturn __divide_by_zero(void);  // SIGFPE/FPE_INTDIV
void __noreturn __trap(uint16 trapcode); // SIGTRAP
void __noreturn __break(uint16 code, uint16 subcode);
#endif

#define __SETP__(x, y)   invalid_operation // Generate parity flag for (x-y)

// In the decompilation listing there are some objects declared as _UNKNOWN
// because we could not determine their types. Since the C compiler does not
// accept void item declarations, we replace them by anything of our choice,
// for example a char:

#define _UNKNOWN char

#ifdef _MSC_VER
#define snprintf _snprintf
#define vsnprintf _vsnprintf
#endif

// The ADJ() macro is used for shifted pointers.
// While compilers do not understand it, it makes the code more readable.
// A shifted pointer is declared like this, for example:
//      char *__shifted(mystruct,8) p;
// It means: while 'p' points to 'char', it also points to the middle of 'mystruct'.
// More precisely, it is at the offset of 8 bytes from the beginning of 'mystruct'.
//
// The ADJ() macro performs the necessary adjustment.
// The __parentof() and __deltaof() functions are made up, they do not exist.
// __parentof() returns the parent structure type.
// __deltaof() returns the shift amount.

#define ADJ(p) (__parentof(p) *)(p-__deltaof(p))

#endif // HEXRAYS_DEFS_H

// defs.h stops at SLODWORD/SHIDWORD; the bodies also index DWORD lanes
// directly.  Same DWORDn/SDWORDn machinery, just the names it left out.
#define DWORD1(x)  DWORDn(x, 1)
#define DWORD2(x)  DWORDn(x, 2)
#define DWORD3(x)  DWORDn(x, 3)
#define SDWORD1(x) SDWORDn(x, 1)
#define SDWORD2(x) SDWORDn(x, 2)
#define SDWORD3(x) SDWORDn(x, 3)

// ---------------------------------------------------------------------------
// Sixteen bytes, read as whatever reads them.
//
// Hex-Rays wrote MSVC's spelling for the halves of an SSE register --
// `v.m128i_i32[1]`, `q.m128_f32[0]` -- because on Windows __m128i, __m128 and
// __m128d are *unions* with those members, and GCC's are bare vector types
// with none.  The bodies used to need the vector types themselves, so there
// were four wrappers -- one per MSVC union, each with its own member prefix --
// with conversions between them and target attributes to carry them through
// the intrinsics.
//
// There are no intrinsics left.  What the file actually does with these is
// read and write sixteen bytes under half a dozen names, which is one union
// with all the names in it -- no vector member, no conversions, no target
// attribute.  `__m128` and `__m128i` are both spellings of it, so the casts
// Hex-Rays wrote between them are the no-ops they always were.
//
// The alignment is stated rather than inherited: `*(__m128i *)ptr` still has
// to address a sixteen-byte-aligned object, and several globals are declared
// alignas(16) on the strength of it.
// ---------------------------------------------------------------------------
union alignas(16) M128 {
  float              m128_f32[4];
  // m128_i8 is `char`, not `signed char`: MSVC's __int8 is plain char (so is
  // Hex-Rays' -- see defs.h), and the bodies hand `x.m128_i8` straight to
  // strcpy/strrchr, which take char*.
  char               m128_i8[16];
  short              m128_i16[8];
  int                m128_i32[4];
  long long          m128_i64[2];
  unsigned char      m128_u8[16];
  unsigned short     m128_u16[8];
  unsigned int       m128_u32[4];
  unsigned long long m128_u64[2];
  M128() = default;
  // Hex-Rays writes "zero the register" as `x = 0` / `(__m128)0LL` even for a
  // 16-byte object; a non-zero scalar zero-extends, which is what the
  // corresponding MOVD/MOVQ does.
  M128(long long z) { __builtin_memset(this, 0, 16); m128_i64[0] = z; }
};

static_assert(sizeof(M128) == 16 && alignof(M128) == 16, "M128 layout");

#define __m128i M128
#define __m128  M128
#define __m128d M128

// i386 g++ has no __int128 (verified: "expected primary-expression").  The
// only things typed that way here are 16-byte xmmword globals, so give them
// the same 16-byte type.
typedef M128 _OWORD;
#define __int128 M128

//--- #include "crt.cpp"      // what is left of the runtime BMF got from the PE
// crt.cpp — the runtime BMF used to get from the PE.
//
// Included between the head and the moved bodies.  Everything in it once had
// to announce itself through a `__PE_DECL___x` guard, so that the generated
// .inc files would not also declare `__x` at its address inside a loaded
// BMF.exe.  There is no loaded BMF.exe here and the .inc files arrived as one
// flattened header, so the guards went with the rest of that seam.
//
// This was thirty-one CRT entries and ten kernel32 imports.  Then the switch
// parser, the wildcard walk, the .ini and five image formats went, and with
// them everything that reached for a file handle, a timestamp or a directory.
// What was left of the CRT half was fopen, fclose, fread, fwrite, fseek, feof,
// ferror, fgetc, fflush, printf, vprintf, exit, malloc and free -- wrappers
// whose whole content was to call the function of the same name, standing
// between the bodies and the C library for no reason once BMF's own runtime
// was out of the picture.  The bodies call the C library directly now, so
// those are gone too, and so are FILE1 and Stream, the two typedefs that stood
// in for FILE.  §6.5's reason for routing stdio into the PE -- that a glibc
// FILE* handed to BMF's fread would be read as a Win32 _iobuf -- ended when
// BMF's fread did.
//
// Which leaves this file with two things: the page allocator and out_of_memory_handler.
// Intel's runtime went the same way -- its two error-reporting hooks served
// only the no-SSE2 exit, and its log entries were `log` -- and so did the
// CPUID helpers that answered for its dispatcher.  No Win32 and no Intel
// runtime remain on either host, so there is no longer a Windows half and a
// POSIX half.

// ---------------------------------------------------------------------------
// The page allocator.
//
// Four bodies asked kernel32 for a megabyte with
//
//     VirtualAlloc(0, 0x103E30, MEM_COMMIT, PAGE_READWRITE)
//
// and gave it back with VirtualFree(p, 0, MEM_RELEASE).  Two properties of
// that block are load-bearing: it arrives zeroed, and it is page-aligned, so
// the SSE stores the bodies make into it are aligned however far in they land.
// malloc promises neither, so this supplies both over malloc.
//
// Not aligned_alloc: MSVC does not have it, and on mingw it is either absent
// or a _aligned_malloc alias whose blocks must not go to free() — which is
// exactly the portability the request was about.  Over-allocating and stepping
// the pointer forward is plain C89 and behaves the same everywhere; the base
// malloc returned is parked in the word ahead of the aligned block, which is
// what bmf_page_free hands back.
// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
// A heap the program's own 32-bit pointer fields can address -- 64-bit only.
//
// BMF's structures keep pointers in 32-bit fields.  At 32 bits that is merely
// untyped; at 64 it is lossy.  The clean fix is to widen the fields, and
// REFACTORING.md §4 records why that cannot be done here: every one of the 159
// objects is walked with variable offsets as well as constant ones, so moving a
// field moves the arrays after it.
//
// This is the other way, and it is the only one left: put every allocation the
// program makes below 4 GB, so a 32-bit field holds a whole address.  It does
// not make the code honest about its types and it is not a substitute for
// doing that.
//
// Compiled only for a 64-bit target, so the 32-bit build -- the one the streams
// are verified against -- allocates exactly as it did.
// ---------------------------------------------------------------------------
#if UINTPTR_MAX > 0xFFFFFFFFu
#if defined(__linux__)
#  include <sys/mman.h>
#  define BMF_LOW_ARENA 1
#endif
#define BMF_ARENA_BYTES (768u << 20)
static char  *bmf_arena;
static size_t bmf_arena_used;
static void bmf_arena_init(void) {
#ifdef BMF_LOW_ARENA
  void *p = mmap(nullptr, BMF_ARENA_BYTES, PROT_READ | PROT_WRITE,
                 MAP_PRIVATE | MAP_ANONYMOUS | MAP_32BIT, -1, 0);
  bmf_arena = (p == MAP_FAILED) ? nullptr : (char *)p;
#else
  bmf_arena = (char *)malloc(BMF_ARENA_BYTES);
#endif
  if (!bmf_arena) { fprintf(stderr, "bmf: no arena\n"); exit(7); }
  if (sizeof(void *) > 4 && (uintptr_t)bmf_arena + BMF_ARENA_BYTES > 0xFFFFFFFFu) {
    fprintf(stderr, "bmf: arena above 4 GB\n"); exit(7);
  }
}
#define BMF_BUCKETS 40
static void *bmf_bucket[BMF_BUCKETS];
static int bmf_bucket_of(size_t n) { int b=0; while ((size_t)1<<(b+5) < n && b<BMF_BUCKETS-1) b++; return b; }
static void *bmf_malloc(size_t n) {
  if (!bmf_arena) bmf_arena_init();
  int b = bmf_bucket_of(n);
  size_t need = (size_t)1 << (b + 5);
  if (bmf_bucket[b]) { void *p=bmf_bucket[b]; bmf_bucket[b]=*(void**)p; ((size_t*)p)[-2]=(size_t)b; return p; }
  if (bmf_arena_used + need + 16 > BMF_ARENA_BYTES) return nullptr;
  char *p = bmf_arena + bmf_arena_used + 16;
  ((size_t *)p)[-2] = (size_t)b;
  bmf_arena_used += need + 16;
  return p;
}
static void bmf_free(void *p) {
  if (!p) return;
  int b=(int)((size_t*)p)[-2];
  if (b<0||b>=BMF_BUCKETS) return;
  *(void**)p = bmf_bucket[b]; bmf_bucket[b]=p;
}
#define malloc bmf_malloc
#define free   bmf_free

#endif  // 64-bit only

#define BMF_PAGE 4096u

static void *bmf_page_alloc(size_t n) {
  void *base = malloc(n + BMF_PAGE + sizeof(void *));
  if (!base)
    return nullptr;
  uintptr_t raw = (uintptr_t)base + sizeof(void *);
  char *p = (char *)((raw + (BMF_PAGE - 1)) & ~(uintptr_t)(BMF_PAGE - 1));
  ((void **)p)[-1] = base;
  memset(p, 0, n);
  return p;
}

static void bmf_page_free(void *p) {
  if (p)
    free(((void **)p)[-1]);
}

// out_of_memory_handler is `push 7; call exit_402E40` — the handler main
// hands to set_new_handler.  IDA's call analysis failed on it (hence "no decompiled
// body" in the generated declaration), but the two instructions are not in
// doubt.  Defined after the bodies, since exit_402E40 is one of them.
void __out_of_memory_handler();

// ---------------------------------------------------------------------------
// operator new is not malloc.
//
// Every allocation in the bodies came out of IDA as `__op_new`, MSVC's
// `operator new`, and the imported tree defined it here as a one-line shim over
// malloc.  A later commit inlined that shim on the grounds that a wrapper whose
// entire content is a call to the C library stands between the bodies and the
// library for no reason.  That was right about `fread` and wrong about this
// one: `operator new` has a contract malloc does not, and BMF depends on it.
// MSVC's calls the handler installed by `_set_new_handler` when an allocation
// fails, and `main`'s first act after setting the FPU mode is
//
//     set_new_handler(out_of_memory_handler);
//
// which is `exit_402E40(7)` — "Out of memory!", exit status 7.  With the shim
// gone that store went to a global nothing reads, the handler became a function
// nothing can call, and a run that cannot get memory dies of a null dereference
// with no message instead of saying what happened.  Nothing caught it because
// no test had ever made an allocation fail; `ulimit -v` makes one fail in a
// second (REFACTORING.md §2.3).
//
// This is that contract and no more of it: try, and on failure call whatever
// handler the program stored, then try again.  The handler exits, so the retry
// is theory rather than a loop; with no handler stored this returns null, which
// is what the callers already assume and what the shim did.  Reading the
// handler out of `__pout_of_memory_handler` is the point — it puts
// `set_new_handler` back on a live path rather than working around it.
static void *bmf_new(size_t n);

// ---------------------------------------------------------------------------
// The block copies MSVC unrolled.
//
// Twenty-seven places in the bodies copy an 18-byte record as four dwords and a
// word, ascending, which is what the compiler made of `memcpy(d, s, 18)` and
// all Hex-Rays could give back.  `tools/uncopy.py` folds each run into one call
// through here.
//
// A store sequence and a `memcpy` differ in exactly one case -- overlapping
// regions -- so that is checked rather than argued.  `BMF_COPY_CHECK=1
// ./build.sh` makes this abort when the regions touch, and the gate is run
// against it; none of the twenty-seven does.  They are rows of a table 144
// bytes apart, which is why.
// ---------------------------------------------------------------------------
static inline void bmf_copy(void *d, const void *s, size_t n) {
#ifdef BMF_COPY_CHECK
  const char *dp = (const char *)d, *sp = (const char *)s;
  if (dp < sp + n && sp < dp + n) {
    fprintf(stderr, "bmf: overlapping copy, %p <- %p, %u bytes\n",
            d, s, (unsigned)n);
    abort();
  }
#endif
  memcpy(d, s, n);
}

#include "subs1.hpp"

static void *bmf_new(size_t n) {
  for (;;) {
    void *p = malloc(n ? n : 1);       // `n ? n : 1` as the imported shim had it
    if (p)
      return p;
    void (*handler)() = (void (*)())__pout_of_memory_handler;
    if (!handler)
      return nullptr;
    handler();
  }
}

