

// bmf.cpp — BMF, the whole program, as one translation unit.
//
// BMF 2.01 by Dmitry Shkarin, recovered from the 32-bit Windows binary: 143
// functions decompiled with Hex-Rays and corrected against the disassembly
// until the compressed streams came out bit-for-bit identical to the
// original's on every test image.  See README.md.
//
// One translation unit because the bodies are not independent: they share
// globals by address (blob.inc), several are entered through calling
// conventions that only exist inside a file (thiscall, fastcall), and the
// order below is callees-before-callers so that a call to an already-defined
// body needs no forward declaration.  Splitting it up would buy nothing and
// cost all of that.
//
// Generated by incdec/bmf/standalone/mkbmfc.py.  Do not edit.

// Selects the standalone half of bmfhead.h and of each body: no redirects
// into a loaded BMF.exe, no entry-point thunks for callers that no longer
// exist, no call-count probes.
#define BMF_STANDALONE 1

#include "blob.inc"     // BMF's data segment, and the globals' base
//--- #include "bmfhead.h"    // Hex-Rays' type vocabulary, SSE wrappers, defs.h
// bmfhead.h — the vocabulary the decompiled bodies are written in.
//
// Generated from incdec/bmf/dummy32_head.cpp by incdec/bmf/standalone/
// mkbmfc.py, with the conditionals for the injected build evaluated out.
// Do not edit: change the original and re-run the generator.

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <cmath>
#include <cctype>     // isspace/isdigit/toupper — §6.5 lets these fall through
#include <cstdarg>
#include <immintrin.h>

// ---------------------------------------------------------------------------
// Hex-Rays type vocabulary.
//
// This is Hex-Rays' own defs.h, verbatim — the same header BMF.cpp's `#include
// <defs.h>` refers to — rather than a hand-rolled subset.  It brings LOBYTE /
// BYTEn / WORDn / SBYTEn / __ROLn__ / __RORn__ / __PAIRn__ / abs32 / qmemcpy /
// COERCE_* / _UNKNOWN and the __intN aliases, all with the exact semantics the
// decompiler assumed when it emitted them.
//
// BMF.cpp's other include, <windows.h>, is deliberately not used on any
// target.  On a POSIX host there is no Win32 SDK to include; on a Windows host
// there is, and pulling it in would put the current SDK's declarations up
// against the layouts the decompilation was typed for, which is a collision
// with nothing to gain.  The handful of types and constants the bodies name
// are below, at the offsets IDA recovered.
//
// defs.h keys several typedefs off that header, though: `#ifndef _WINDOWS_` it
// defines BYTE/WORD/DWORD/LONG/BOOL itself, and as *signed* types (`typedef
// int8 BYTE`, int8 being plain char).  BMF was compiled against the real
// windows.h, where they are unsigned.  So declare _WINDOWS_ and supply the
// windows.h spellings ourselves; letting defs.h win would silently sign-extend
// every BYTE the bodies touch.
// ---------------------------------------------------------------------------
#define _WINDOWS_
typedef unsigned char  BYTE;
typedef unsigned short WORD;
typedef unsigned long  DWORD;
typedef long           LONG;
typedef int            BOOL;

//--- #include "bmfdefs.h"
/*

   This file contains definitions used in the Hex-Rays decompiler output.
   It has type definitions and convenience macros to make the
   output more readable.

   Copyright (c) 2007-2025 Hex-Rays

*/

#ifndef HEXRAYS_DEFS_H
#define HEXRAYS_DEFS_H

#if defined(__GNUC__)
  typedef          long long ll;
  typedef unsigned long long ull;
  #define __int64 long long
  #define __int32 int
  #define __int16 short
  #define __int8  char
  #define MAKELL(num) num ## LL
  #define FMT_64 "ll"
#elif defined(_MSC_VER)
  typedef          __int64 ll;
  typedef unsigned __int64 ull;
  #define MAKELL(num) num ## i64
  #define FMT_64 "I64"
#elif defined (__BORLANDC__)
  typedef          __int64 ll;
  typedef unsigned __int64 ull;
  #define MAKELL(num) num ## i64
  #define FMT_64 "L"
#else
  #error "unknown compiler"
#endif
typedef unsigned int uint;
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned long ulong;

typedef          char   int8;
typedef   signed char   sint8;
typedef unsigned char   uint8;
typedef          short  int16;
typedef   signed short  sint16;
typedef unsigned short  uint16;
typedef          int    int32;
typedef   signed int    sint32;
typedef unsigned int    uint32;
typedef ll              int64;
typedef ll              sint64;
typedef ull             uint64;

// Partially defined types. They are used when the decompiler does not know
// anything about the type except its size.
#define _BYTE  uint8
#define _WORD  uint16
#define _DWORD uint32
#define _QWORD uint64
#if !defined(_MSC_VER)
#define _LONGLONG __int128
#endif

// Non-standard boolean types. They are used when the decompiler cannot use
// the standard "bool" type because of the size mistmatch but the possible
// values are only 0 and 1. See also 'BOOL' type below.
typedef int8 _BOOL1;
typedef int16 _BOOL2;
typedef int32 _BOOL4;
typedef int64 _BOOL8;

#ifndef _WINDOWS_
typedef int8 BYTE;
typedef int16 WORD;
typedef int32 DWORD;
typedef int32 LONG;
typedef int BOOL;       // uppercase BOOL is usually 4 bytes
#endif
typedef int64 QWORD;
#ifndef __cplusplus
typedef int bool;       // we want to use bool in our C programs
#endif

#ifndef __pure
// a modern gcc defines __pure as '__attribute__((__pure__))'
#define __pure  // pure function:
                // when given the same arguments, always returns the same value
                // has no side effects
#endif

// Non-returning function
#if defined(__GNUC__)
#define __noreturn  __attribute__((noreturn))
#else
#define __noreturn  __declspec(noreturn)
#endif


#ifndef NULL
#define NULL 0
#endif

// Some convenience macros to make partial accesses nicer
#define LAST_IND(x,part_type)    (sizeof(x)/sizeof(part_type) - 1)
#if defined(__BYTE_ORDER) && __BYTE_ORDER == __BIG_ENDIAN
#  define LOW_IND(x,part_type)   LAST_IND(x,part_type)
#  define HIGH_IND(x,part_type)  0
#else
#  define HIGH_IND(x,part_type)  LAST_IND(x,part_type)
#  define LOW_IND(x,part_type)   0
#endif
// first unsigned macros:
#define BYTEn(x, n)   (*((_BYTE*)&(x)+n))
#define WORDn(x, n)   (*((_WORD*)&(x)+n))
#define DWORDn(x, n)  (*((_DWORD*)&(x)+n))

#define LOBYTE(x)  BYTEn(x,LOW_IND(x,_BYTE))
#define LOWORD(x)  WORDn(x,LOW_IND(x,_WORD))
#define LODWORD(x) DWORDn(x,LOW_IND(x,_DWORD))
#define HIBYTE(x)  BYTEn(x,HIGH_IND(x,_BYTE))
#define HIWORD(x)  WORDn(x,HIGH_IND(x,_WORD))
#define HIDWORD(x) DWORDn(x,HIGH_IND(x,_DWORD))
#define BYTE1(x)   BYTEn(x,  1)         // byte 1 (counting from 0)
#define BYTE2(x)   BYTEn(x,  2)
#define BYTE3(x)   BYTEn(x,  3)
#define BYTE4(x)   BYTEn(x,  4)
#define BYTE5(x)   BYTEn(x,  5)
#define BYTE6(x)   BYTEn(x,  6)
#define BYTE7(x)   BYTEn(x,  7)
#define BYTE8(x)   BYTEn(x,  8)
#define BYTE9(x)   BYTEn(x,  9)
#define BYTE10(x)  BYTEn(x, 10)
#define BYTE11(x)  BYTEn(x, 11)
#define BYTE12(x)  BYTEn(x, 12)
#define BYTE13(x)  BYTEn(x, 13)
#define BYTE14(x)  BYTEn(x, 14)
#define BYTE15(x)  BYTEn(x, 15)
#define WORD1(x)   WORDn(x,  1)
#define WORD2(x)   WORDn(x,  2)         // third word of the object, unsigned
#define WORD3(x)   WORDn(x,  3)
#define WORD4(x)   WORDn(x,  4)
#define WORD5(x)   WORDn(x,  5)
#define WORD6(x)   WORDn(x,  6)
#define WORD7(x)   WORDn(x,  7)

// now signed macros (the same but with sign extension)
#define SBYTEn(x, n)   (*((int8*)&(x)+n))
#define SWORDn(x, n)   (*((int16*)&(x)+n))
#define SDWORDn(x, n)  (*((int32*)&(x)+n))

#define SLOBYTE(x)  SBYTEn(x,LOW_IND(x,int8))
#define SLOWORD(x)  SWORDn(x,LOW_IND(x,int16))
#define SLODWORD(x) SDWORDn(x,LOW_IND(x,int32))
#define SHIBYTE(x)  SBYTEn(x,HIGH_IND(x,int8))
#define SHIWORD(x)  SWORDn(x,HIGH_IND(x,int16))
#define SHIDWORD(x) SDWORDn(x,HIGH_IND(x,int32))
#define SBYTE1(x)   SBYTEn(x,  1)
#define SBYTE2(x)   SBYTEn(x,  2)
#define SBYTE3(x)   SBYTEn(x,  3)
#define SBYTE4(x)   SBYTEn(x,  4)
#define SBYTE5(x)   SBYTEn(x,  5)
#define SBYTE6(x)   SBYTEn(x,  6)
#define SBYTE7(x)   SBYTEn(x,  7)
#define SBYTE8(x)   SBYTEn(x,  8)
#define SBYTE9(x)   SBYTEn(x,  9)
#define SBYTE10(x)  SBYTEn(x, 10)
#define SBYTE11(x)  SBYTEn(x, 11)
#define SBYTE12(x)  SBYTEn(x, 12)
#define SBYTE13(x)  SBYTEn(x, 13)
#define SBYTE14(x)  SBYTEn(x, 14)
#define SBYTE15(x)  SBYTEn(x, 15)
#define SWORD1(x)   SWORDn(x,  1)
#define SWORD2(x)   SWORDn(x,  2)
#define SWORD3(x)   SWORDn(x,  3)
#define SWORD4(x)   SWORDn(x,  4)
#define SWORD5(x)   SWORDn(x,  5)
#define SWORD6(x)   SWORDn(x,  6)
#define SWORD7(x)   SWORDn(x,  7)

// Generate a pair of operands. S stands for 'signed'
#define __SPAIR16__(high, low)  (((int16)  (high) <<  8) | (uint8) (low))
#define __SPAIR32__(high, low)  (((int32)  (high) << 16) | (uint16)(low))
#define __SPAIR64__(high, low)  (((int64)  (high) << 32) | (uint32)(low))
#define __SPAIR128__(high, low) (((int128) (high) << 64) | (uint64)(low))
#define __PAIR16__(high, low)   (((uint16) (high) <<  8) | (uint8) (low))
#define __PAIR32__(high, low)   (((uint32) (high) << 16) | (uint16)(low))
#define __PAIR64__(high, low)   (((uint64) (high) << 32) | (uint32)(low))
#define __PAIR128__(high, low)  (((uint128)(high) << 64) | (uint64)(low))

// Helper functions to represent some assembly instructions.

#ifdef __cplusplus

// compile time assertion
#define __CASSERT_N0__(l) COMPILE_TIME_ASSERT_ ## l
#define __CASSERT_N1__(l) __CASSERT_N0__(l)
#define CASSERT(cnd) typedef char __CASSERT_N1__(__LINE__) [(cnd) ? 1 : -1]

// check that unsigned multiplication does not overflow
template<class T> bool is_mul_ok(T count, T elsize)
{
  CASSERT(T(-1) > 0); // make sure T is unsigned
  if ( elsize == 0 || count == 0 )
    return true;
  return count <= T(-1) / elsize;
}

// multiplication that saturates (yields the biggest value) instead of overflowing
// such a construct is useful in "operator new[]"
template<class T> bool saturated_mul(T count, T elsize)
{
  return is_mul_ok(count, elsize) ? count * elsize : T(-1);
}

#include <stddef.h> // for size_t

// memcpy() with determined behavoir: it always copies
// from the start to the end of the buffer
// note: it copies byte by byte, so it is not equivalent to, for example, rep movsd
inline void *qmemcpy(void *dst, const void *src, size_t cnt)
{
  char *out = (char *)dst;
  const char *in = (const char *)src;
  while ( cnt > 0 )
  {
    *out++ = *in++;
    --cnt;
  }
  return dst;
}

// rotate left
template<class T> T __ROL__(T value, int count)
{
  const uint nbits = sizeof(T) * 8;

  if ( count > 0 )
  {
    count %= nbits;
    T high = value >> (nbits - count);
    if ( T(-1) < 0 ) // signed value
      high &= ~((T(-1) << count));
    value <<= count;
    value |= high;
  }
  else
  {
    count = -count % nbits;
    T low = value << (nbits - count);
    value >>= count;
    value |= low;
  }
  return value;
}

inline uint8  __ROL1__(uint8  value, int count) { return __ROL__((uint8)value, count); }
inline uint16 __ROL2__(uint16 value, int count) { return __ROL__((uint16)value, count); }
inline uint32 __ROL4__(uint32 value, int count) { return __ROL__((uint32)value, count); }
inline uint64 __ROL8__(uint64 value, int count) { return __ROL__((uint64)value, count); }
inline uint8  __ROR1__(uint8  value, int count) { return __ROL__((uint8)value, -count); }
inline uint16 __ROR2__(uint16 value, int count) { return __ROL__((uint16)value, -count); }
inline uint32 __ROR4__(uint32 value, int count) { return __ROL__((uint32)value, -count); }
inline uint64 __ROR8__(uint64 value, int count) { return __ROL__((uint64)value, -count); }

// sign flag
template<class T> int8 __SETS__(T x)
{
  if ( sizeof(T) == 1 )
    return int8(x) < 0;
  if ( sizeof(T) == 2 )
    return int16(x) < 0;
  if ( sizeof(T) == 4 )
    return int32(x) < 0;
  return int64(x) < 0;
}

// overflow flag of subtraction (x-y)
template<class T, class U> int8 __OFSUB__(T x, U y)
{
  if ( sizeof(T) < sizeof(U) )
  {
    U x2 = x;
    int8 sx = __SETS__(x2);
    return (sx ^ __SETS__(y)) & (sx ^ __SETS__(U(x2-y)));
  }
  else
  {
    T y2 = y;
    int8 sx = __SETS__(x);
    return (sx ^ __SETS__(y2)) & (sx ^ __SETS__(T(x-y2)));
  }
}

// overflow flag of addition (x+y)
template<class T, class U> int8 __OFADD__(T x, U y)
{
  if ( sizeof(T) < sizeof(U) )
  {
    U x2 = x;
    int8 sx = __SETS__(x2);
    return ((1 ^ sx) ^ __SETS__(y)) & (sx ^ __SETS__(U(x2+y)));
  }
  else
  {
    T y2 = y;
    int8 sx = __SETS__(x);
    return ((1 ^ sx) ^ __SETS__(y2)) & (sx ^ __SETS__(T(x+y2)));
  }
}

// https://en.wikipedia.org/wiki/Carry_flag#Carry_flag_vs._borrow_flag
#if defined(__ARM__) || defined(__PPC__)
#define SUB_WITH_CARRY 1
#else
#define SUB_WITH_CARRY 0
#endif

// carry flag of subtraction (x-y)
template<class T, class U> int8 __CFSUB__(T x, U y)
{
  int size = sizeof(T) > sizeof(U) ? sizeof(T) : sizeof(U);
  bool res;
  if ( size == 1 )
    res = uint8(x) < uint8(y);
  else if ( size == 2 )
    res = uint16(x) < uint16(y);
  else if ( size == 4 )
    res = uint32(x) < uint32(y);
  else
    res = uint64(x) < uint64(y);
#if SUB_WITH_CARRY
  res = !res;
#endif
  return res;
}

// carry flag of addition (x+y)
template<class T, class U> int8 __CFADD__(T x, U y)
{
  int size = sizeof(T) > sizeof(U) ? sizeof(T) : sizeof(U);
  if ( size == 1 )
    return uint8(x) > uint8(x+y);
  if ( size == 2 )
    return uint16(x) > uint16(x+y);
  if ( size == 4 )
    return uint32(x) > uint32(x+y);
  return uint64(x) > uint64(x+y);
}

// carry flag of subtraction with carry
template<class T, class U> int8 __CFSUB__(T x, U y, int8 cf)
{
#if SUB_WITH_CARRY
  cf = !cf;
#endif
  return __CFADD__(y, cf) ^ __CFSUB(x, y + cf);
}

// overflow flag of subtraction with carry
template<class T, class U> int8 __OFSUB__(T x, U y, int8 cf)
{
#if SUB_WITH_CARRY
  cf = !cf;
#endif
  return __OFADD__(y, cf) ^ __OFSUB(x, y + cf);
}

inline uint8   abs8(int8     x) { return x >= 0 ? x : -x; }
inline uint16  abs16(int16   x) { return x >= 0 ? x : -x; }
inline uint32  abs32(int32   x) { return x >= 0 ? x : -x; }
inline uint64  abs64(int64   x) { return x >= 0 ? x : -x; }
//inline uint128 abs128(int128 x) { return x >= 0 ? x : -x; }

#include <string.h>     // for memcpy
#include <type_traits>  // for enable_if

template <typename T, typename F>
inline typename std::enable_if<sizeof(T) <= sizeof(F), T>::type __coerce(F f)
{
  T t;
  memcpy(&t, &f, sizeof(T));
  return t;
}
#define COERCE_FLOAT(v) __coerce<float>(v)
#define COERCE_DOUBLE(v) __coerce<double>(v)
#define COERCE_LONG_DOUBLE(v) __coerce<long double>(v)
#define COERCE_UNSIGNED_INT(v) __coerce<unsigned int>(v)
#define COERCE_UNSIGNED_INT64(v) __coerce<uint64>(v)

#else // C++
// For C, we just provide macros, they are not quite correct.
#define __ROL__(x, y) __rotl__(x, y)      // Rotate left
#define __ROR__(x, y) __rotr__(x, y)      // Rotate right
#define __CFSHL__(x, y) invalid_operation // Generate carry flag for (x<<y)
#define __CFSHR__(x, y) invalid_operation // Generate carry flag for (x>>y)
#define __CFADD__(x, y) invalid_operation // Generate carry flag for (x+y)
#define __CFSUB__(x, y) invalid_operation // Generate carry flag for (x-y)
#define __OFADD__(x, y) invalid_operation // Generate overflow flag for (x+y)
#define __OFSUB__(x, y) invalid_operation // Generate overflow flag for (x-y)

#define abs8(x)   (int8)  ((int8)  (x) >= 0 ? (x) : -(x))
#define abs16(x)  (int16) ((int16) (x) >= 0 ? (x) : -(x))
#define abs32(x)  (int32) ((int32) (x) >= 0 ? (x) : -(x))
#define abs64(x)  (int64) ((int64) (x) >= 0 ? (x) : -(x))
#define abs128(x) (int128)((int128)(x) >= 0 ? (x) : -(x))

#endif // C++

#if defined(__MIPS__)
// traps for MIPS arithmetic operation
void __noreturn __integer_oveflow(void); // SIGFPE/FPE_INTOVF
void __noreturn __divide_by_zero(void);  // SIGFPE/FPE_INTDIV
void __noreturn __trap(uint16 trapcode); // SIGTRAP
void __noreturn __break(uint16 code, uint16 subcode);
#endif

#define __SETP__(x, y)   invalid_operation // Generate parity flag for (x-y)

// In the decompilation listing there are some objects declared as _UNKNOWN
// because we could not determine their types. Since the C compiler does not
// accept void item declarations, we replace them by anything of our choice,
// for example a char:

#define _UNKNOWN char

#ifdef _MSC_VER
#define snprintf _snprintf
#define vsnprintf _vsnprintf
#endif

// The ADJ() macro is used for shifted pointers.
// While compilers do not understand it, it makes the code more readable.
// A shifted pointer is declared like this, for example:
//      char *__shifted(mystruct,8) p;
// It means: while 'p' points to 'char', it also points to the middle of 'mystruct'.
// More precisely, it is at the offset of 8 bytes from the beginning of 'mystruct'.
//
// The ADJ() macro performs the necessary adjustment.
// The __parentof() and __deltaof() functions are made up, they do not exist.
// __parentof() returns the parent structure type.
// __deltaof() returns the shift amount.

#define ADJ(p) (__parentof(p) *)(p-__deltaof(p))

#endif // HEXRAYS_DEFS_H

typedef void*         HANDLE;
typedef unsigned int  UINT;

// ---------------------------------------------------------------------------
// The data segment, as one object.
//
// Every global a moved body touches is a reference into `blob1` at its
// original offset — `*(int*)(blob1 + 0x00441040 - BMF_BLOB_BASE)` — rather
// than a bare `*(int *)0x00441040`.  Same address, same layout, but the data
// has a definition instead of being 845 scattered constants, and the two
// builds can put it in different places:
//
//   hybrid      blob1 *is* the loaded PE's data.  The moved bodies share their
//               globals with the code still running in the image, so there is
//               nothing to copy and the pointer is the load address.
//   standalone  blob1 is an array, defined in standalone/blob.inc, which
//               build.sh includes ahead of this file.  The linker puts it
//               wherever it likes; the absolute pointers *inside* the data are
//               rebased once at startup.
//
// incdec.md §6.1 is why the offsets stay: naming the globals is a much larger
// job than moving them, because the same address is an `int` to one function
// and a `char[]` to the next.
// ---------------------------------------------------------------------------
#ifndef BMF_BLOB_BASE
#define BMF_BLOB_BASE 0x00438000u
#endif

// The same rebasing for an address Hex-Rays baked into an *expression* rather
// than into a named global — `*(_QWORD *)(n64 + 4469652)`, where 4469652 is
// 0x00443394.  extract.py rewrites those to BMF_BLOB(0x00443394); in the
// hybrid build it is the identity, since blob1 is 0x00438000 there.
#define BMF_BLOB(va) ((int)(blob1 + ((va) - BMF_BLOB_BASE)))

// Win32 manifest constants the bodies spell out.  windows.h is not included
// (see above), and these are the only ones referenced.
#define MEM_COMMIT      0x00001000
#define MEM_RESERVE     0x00002000
#define MEM_DECOMMIT    0x00004000
#define MEM_RELEASE     0x00008000
#define MEM_TOP_DOWN    0x00100000
#define PAGE_NOACCESS         0x01
#define PAGE_READONLY         0x02
#define PAGE_READWRITE        0x04
#define PAGE_EXECUTE_READWRITE 0x40
#define INVALID_HANDLE_VALUE ((HANDLE)(long)-1)
#define INVALID_FILE_ATTRIBUTES ((DWORD)-1)
#define GENERIC_READ          0x80000000
#define GENERIC_WRITE         0x40000000
#define FILE_SHARE_READ              0x01
#define FILE_READ_ATTRIBUTES         0x80
#define FILE_ATTRIBUTE_NORMAL        0x80
#define FILE_ATTRIBUTE_DIRECTORY     0x10
#define FILE_WRITE_EA                0x10   // IDA's name for the same bit
#define CREATE_ALWAYS                   2
#define OPEN_EXISTING                   3
#define MAX_PATH                      260

// The handful of Win32 types the file-handling bodies name, with the layouts
// windows.h gives them.  The structs are read and written by real Win32 calls
// — through the shim in the injected build, by kernel32 itself in the Windows
// one — so the field offsets have to match.
typedef char           CHAR;
typedef unsigned short WCHAR;   // `const WCHAR SrcStr = 0u;` — an empty string
typedef char *         LPSTR;
typedef const char *   LPCSTR;
typedef void *         LPVOID;
typedef struct _FILETIME {
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
} FILETIME;
typedef struct _WIN32_FIND_DATAA {
  DWORD    dwFileAttributes;      // +0x00
  FILETIME ftCreationTime;        // +0x04
  FILETIME ftLastAccessTime;      // +0x0C
  FILETIME ftLastWriteTime;       // +0x14
  DWORD    nFileSizeHigh;         // +0x1C
  DWORD    nFileSizeLow;          // +0x20
  DWORD    dwReserved0;           // +0x24
  DWORD    dwReserved1;           // +0x28
  CHAR     cFileName[MAX_PATH];   // +0x2C
  CHAR     cAlternateFileName[14];// +0x130
} WIN32_FIND_DATAA;
static_assert(sizeof(WIN32_FIND_DATAA) == 320, "Win32 WIN32_FIND_DATAA is 320 bytes");

// The standalone build has no PE runtime to hand out _iobufs: every stdio
// call goes to the host's C library, so `FILE1` is its FILE — glibc's on
// POSIX, msvcrt's (which is this layout) on Windows.  No body reads a field of
// one, verified across all 143, so nothing depends on the layout; only on
// fopen's result reaching fread unchanged.  The name has to survive because
// the bodies still say `#define FILE FILE1`.
typedef FILE FILE1;

// Hex-Rays invented a struct type named `Stream` for the thing fopen returns
// (`Stream *Stream; ... Stream = fopen(...)`), so bodies use it as a type
// name.  It is FILE.  extract.py renames any *variable* called Stream out of
// the way, since a body that declares one would otherwise shadow this.
typedef FILE1 Stream;

// defs.h stops at SLODWORD/SHIDWORD; the bodies also index DWORD lanes
// directly.  Same DWORDn/SDWORDn machinery, just the names it left out.
#define DWORD1(x)  DWORDn(x, 1)
#define DWORD2(x)  DWORDn(x, 2)
#define DWORD3(x)  DWORDn(x, 3)
#define SDWORD1(x) SDWORDn(x, 1)
#define SDWORD2(x) SDWORDn(x, 2)
#define SDWORD3(x) SDWORDn(x, 3)

// Calling-convention keywords survive inside *casts* — Hex-Rays writes
// `(void (__cdecl *)(int, int))f` — where extract.py's signature rewriting
// does not reach.  cdecl is gcc's i386 default, so it maps to nothing.
#define __cdecl
#define __stdcall  __attribute__((stdcall))
#define __fastcall __attribute__((fastcall))
#define __thiscall __attribute__((thiscall))

// Every moved entry point carries BMF_REALIGN.  In the hybrid build a PE
// caller can enter one with esp aligned to 4 — the Microsoft i386 ABI promises
// no more — while g++ assumes 16 and spills SSE locals with `movaps`, so the
// prologue has to realign (§8.2.3).  Standalone there is no such caller: every
// call comes from g++, which has already done the work, and the macro is empty.
#define BMF_REALIGN

// main splits argv[] on '\' to separate the directory from the file name,
// because BMF is a Windows program.  Under the shim that works — it translates
// backslashes — but standalone on POSIX a `dir/file.bmp` argument would leave
// the directory part empty and the file would be looked for in the working
// directory instead.  fixups.txt routes both strrchr calls through this, which
// takes whichever separator appears last, so one body serves both builds.
static inline char *bmf_path_sep(const char *s) {
  const char *a = strrchr(s, '/');
  const char *b = strrchr(s, '\\');
  return (char *)(a > b ? a : b);
}

// incdec.md §8.2
#define _BitScanForward(idx_ptr, mask_val) \
  ((mask_val) ? ((*(idx_ptr) = __builtin_ctz((unsigned int)(mask_val))), 1u) : 0u)

// ---------------------------------------------------------------------------
// SSE register types.
//
// Hex-Rays writes MSVC's spelling for the halves of an SSE register —
// `v.m128i_i32[1]`, `q.m128_f32[0]`, `w.m64_u64` — because on Windows __m128i,
// __m128, __m128d and __m64 are *unions* with those members.  That union is
// MSVC's; GCC's __m128i is a bare vector type (`long long
// __attribute__((vector_size(16)))`) with no members at all, and nothing in
// immintrin.h / x86intrin.h adds them.  <intrin.h> does not help either — on
// GCC that header is just an x86intrin.h alias, so the Intel-compiler spelling
// it provides on Windows is not what arrives here.
//
// So wrap them.  Each M* below is the MSVC union plus conversions in both
// directions, and the __m128* / __m64 names are redirected onto the wrappers
// *after* the intrinsic headers are done with the originals.  The conversions
// carry a wrapper through the intrinsics unchanged: `_mm_mul_ps(a, b)` takes
// its arguments via `operator __gnu_m128&`, and its `__m128` result lands back
// in an M128F through the converting constructor.  Reinterpreting casts between
// the four (`(__m128)xmmword_441120`, which Hex-Rays emits freely) go through
// the cross-type constructors, which copy the bits.
//
// The unions are layout-compatible with the vector types — same size, same
// alignment, vector first — so a pointer cast to one of them still addresses a
// real SSE register image, which is what makes `*(__m128i *)ptr` work.
// ---------------------------------------------------------------------------
typedef __m128i __gnu_m128i;
typedef __m128  __gnu_m128;
typedef __m128d __gnu_m128d;
typedef __m64   __gnu_m64;

union M128I;
union M128F;
union M128D;

union M128I {
  __gnu_m128i v;
  // m128i_i8 is `char`, not `signed char`: MSVC's __int8 is plain char (so is
  // Hex-Rays' — see defs.h), and the bodies hand `x.m128i_i8` straight to
  // strcpy/strrchr, which take char*.
  char               m128i_i8[16];
  short              m128i_i16[8];
  int                m128i_i32[4];
  long long          m128i_i64[2];
  unsigned char      m128i_u8[16];
  unsigned short     m128i_u16[8];
  unsigned int       m128i_u32[4];
  unsigned long long m128i_u64[2];
  M128I() = default;
  M128I(__gnu_m128i a) : v(a) {}
  // Hex-Rays writes "zero the register" as `x = 0` / `(__m128i)0LL` even for a
  // 16-byte object; a non-zero scalar zero-extends, which is what the
  // corresponding MOVD/MOVQ does.
  M128I(long long z) { __builtin_memset(this, 0, 16); m128i_i64[0] = z; }
  inline M128I(const M128F &o);
  inline M128I(const M128D &o);
  operator __gnu_m128i&() { return v; }
  operator const __gnu_m128i&() const { return v; }
};

union M128F {
  __gnu_m128         v;
  float              m128_f32[4];
  char               m128_i8[16];
  short              m128_i16[8];
  int                m128_i32[4];
  long long          m128_i64[2];
  unsigned char      m128_u8[16];
  unsigned short     m128_u16[8];
  unsigned int       m128_u32[4];
  unsigned long long m128_u64[2];
  M128F() = default;
  M128F(__gnu_m128 a) : v(a) {}
  M128F(long long z) { __builtin_memset(this, 0, 16); m128_i64[0] = z; }
  inline M128F(const M128I &o);
  inline M128F(const M128D &o);
  operator __gnu_m128&() { return v; }
  operator const __gnu_m128&() const { return v; }
};

union M128D {
  __gnu_m128d        v;
  double             m128d_f64[2];
  float              m128d_f32[4];
  long long          m128d_i64[2];
  unsigned long long m128d_u64[2];
  M128D() = default;
  M128D(__gnu_m128d a) : v(a) {}
  M128D(long long z) { __builtin_memset(this, 0, 16); m128d_i64[0] = z; }
  inline M128D(const M128I &o);
  inline M128D(const M128F &o);
  operator __gnu_m128d&() { return v; }
  operator const __gnu_m128d&() const { return v; }
};

inline M128I::M128I(const M128F &o) { __builtin_memcpy(this, &o, 16); }
inline M128I::M128I(const M128D &o) { __builtin_memcpy(this, &o, 16); }
inline M128F::M128F(const M128I &o) { __builtin_memcpy(this, &o, 16); }
inline M128F::M128F(const M128D &o) { __builtin_memcpy(this, &o, 16); }
inline M128D::M128D(const M128I &o) { __builtin_memcpy(this, &o, 16); }
inline M128D::M128D(const M128F &o) { __builtin_memcpy(this, &o, 16); }

union M64 {
  __gnu_m64          v;
  char               m64_i8[8];
  short              m64_i16[4];
  int                m64_i32[2];
  long long          m64_i64;
  unsigned char      m64_u8[8];
  unsigned short     m64_u16[4];
  unsigned int       m64_u32[2];
  unsigned long long m64_u64;
  M64() = default;
  M64(__gnu_m64 a) : v(a) {}
  M64(long long z) : m64_i64(z) {}
  operator __gnu_m64&() { return v; }
  operator const __gnu_m64&() const { return v; }
};

static_assert(sizeof(M128I) == 16 && alignof(M128I) == alignof(__gnu_m128i), "M128I layout");
static_assert(sizeof(M128F) == 16 && alignof(M128F) == alignof(__gnu_m128),  "M128F layout");
static_assert(sizeof(M128D) == 16 && alignof(M128D) == alignof(__gnu_m128d), "M128D layout");
static_assert(sizeof(M64)   ==  8, "M64 layout");

// The memory-operand intrinsics take a pointer to the *vector* type, and the
// bodies cast to the wrapper (`(__m128i *)p` expands to `(M128I *)p`).  These
// overloads accept that.  They are the only place the head itself touches SSE,
// hence the explicit target attribute: build.sh deliberately does not turn SSE
// on for the whole translation unit — extract.py puts the same attribute on
// each body that needs it, so nothing else in the file has its code generation
// changed by intrinsics appearing in one function.
#define BMF_SSE __attribute__((target("mmx,sse4.2,fxsr")))
BMF_SSE static inline __gnu_m128i _mm_load_si128 (const M128I *p) { __gnu_m128i r; __builtin_memcpy(&r, p, 16); return r; }
BMF_SSE static inline __gnu_m128i _mm_loadu_si128(const M128I *p) { __gnu_m128i r; __builtin_memcpy(&r, p, 16); return r; }
BMF_SSE static inline __gnu_m128i _mm_loadl_epi64(const M128I *p) { __gnu_m128i r = __extension__ (__gnu_m128i){0, 0}; __builtin_memcpy(&r, p, 8); return r; }
BMF_SSE static inline void _mm_store_si128 (M128I *p, __gnu_m128i a) { __builtin_memcpy(p, &a, 16); }
BMF_SSE static inline void _mm_storeu_si128(M128I *p, __gnu_m128i a) { __builtin_memcpy(p, &a, 16); }
BMF_SSE static inline void _mm_stream_si128(M128I *p, __gnu_m128i a) { _mm_stream_si128((__gnu_m128i *)p, a); }
BMF_SSE static inline void _mm_stream_pi   (M64   *p, __gnu_m64   a) { _mm_stream_pi((__gnu_m64 *)p, a); }

#define __m128i M128I
#define __m128  M128F
#define __m128d M128D
#define __m64   M64

// i386 g++ has no __int128 (verified: "expected primary-expression").  The
// only things typed that way here are 16-byte xmmword globals, so give them
// the same 16-byte SSE type.
typedef M128I _OWORD;
#define __int128 M128I

// The standalone build has no Intel runtime to call, so the three
// register-convention entries below become ordinary C.  Each is a plain
// library function underneath — Intel's own documentation for the first two
// is "log", and the third is strlen — and the trampolines existed only to
// reach the PE's copies with their private register convention.
BMF_SSE static inline unsigned __intel_sse2_strlen(unsigned off, const void *p) {
  (void)off;
  return (unsigned)strlen((const char *)p);
}

// Natural log, despite the name: see override/sub_436E10.inc.  Lane 1 is
// computed too — the caller only ever reads lane 0 through the mask, but
// leaving it undefined would let a signalling value through.
BMF_SSE static inline M128D __svml_log2(const M128I &a) {
  M128D x = a, r;
  r.m128d_f64[0] = log(x.m128d_f64[0]);
  r.m128d_f64[1] = log(x.m128d_f64[1]);
  return r;
}

BMF_SSE static inline double __libm_sse2_log(double d) { return log(d); }

// ---------------------------------------------------------------------------
// CPUID, for the routines that override/ rewrites from their expected
// results (Hex-Rays renders them as `__asm { cpuid }` plus reads of its
// _EAX/_ECX/_EDX pseudo-registers, which have no C form).
// ---------------------------------------------------------------------------
// EFLAGS.ID (bit 21) is writable iff the CPU implements CPUID.
static int bmf_has_cpuid()
{
  unsigned before, after;
  __asm__ volatile("pushfl\n\t"
                   "popl %0\n\t"
                   "movl %0, %1\n\t"
                   "xorl $0x200000, %1\n\t"
                   "pushl %1\n\t"
                   "popfl\n\t"
                   "pushfl\n\t"
                   "popl %1\n\t"
                   : "=&r"(before), "=&r"(after) : : "cc");
  if (before == after)
    return 0;
  __asm__ volatile("pushl %0\n\t popfl" : : "r"(before) : "cc");
  return 1;
}

static void bmf_cpuid(unsigned leaf, unsigned *a, unsigned *b, unsigned *c, unsigned *d)
{
  // -fPIC on i386 reserves EBX, so it has to be saved around CPUID by hand.
  __asm__ volatile("xchgl %%ebx, %1\n\t"
                   "cpuid\n\t"
                   "xchgl %%ebx, %1"
                   : "=a"(*a), "=&r"(*b), "=c"(*c), "=d"(*d)
                   : "0"(leaf), "2"(0));
}

// XGETBV encoded by hand: the mnemonic needs -mxsave, which the rest of this
// translation unit is not built with.
static unsigned bmf_xgetbv0()
{
  unsigned lo, hi;
  __asm__ volatile(".byte 0x0f, 0x01, 0xd0" : "=a"(lo), "=d"(hi) : "c"(0));
  (void)hi;
  return lo;
}

// Every body opens with PROBE_DECL/PROBE_HIT.  Those were the instrument that
// answered "did this function actually run inside the original binary?" while
// the decompilation was being migrated one function at a time; here there is
// nothing to compare against and they compile away.  The calls stay in the
// bodies so that those files remain byte-identical to the extractor's output.
#define PROBE_DECL(sym)
#define PROBE_HIT(sym)  ((void)0)


//--- #include "crt.cpp"      // the C runtime and the ten kernel32 imports
// crt.cpp — the runtime BMF used to get from the PE.
//
// Included between the head and the moved bodies, and only in the standalone
// build.  Every symbol here fills in one of the `#ifndef __PE_DECL___x` slots
// the generated .inc files open: each of those blocks is "declare `__x` at its
// address inside BMF.exe *unless* someone already has", so defining the guard
// plus a real `__x` before the includes replaces the PE entry point without
// touching a single generated line.
//
// Three groups:
//
//   * The statically-linked MSVC CRT (§6.5 routed these into the PE because a
//     glibc FILE* handed to BMF's fread would be read as a Win32 _iobuf; with
//     BMF's code gone there is no second runtime and they are just the host's).
//   * The ten kernel32 imports, which were behind IAT slots and so are named
//     directly rather than through a `#define`.
//   * Three odds and ends: operator new/delete, the two Intel memcpy/memset
//     dispatchers, and sub_402E30, the out-of-memory handler main installs.
//
// Two hosts.  On Windows all of this is native — the CRT entries are msvcrt's
// under their `_`-prefixed names, and the ten kernel32 imports are the real
// ones, so that half of the file is ten declarations and no code.  On POSIX
// they are written out against open/opendir/futimens.
//
// What is deliberately *not* here on either host: winapi_shim32's Win32
// emulation.  That is the right answer when you are running BMF's own code and
// it expects Windows; it is the wrong one when the goal is a program that
// stands on its own.  Ten functions against POSIX is less code than the shim's
// handle table alone.

#include <stdarg.h>
#include <time.h>
#ifdef _WIN32
#include <conio.h>    // _getch
#include <io.h>       // _access, _filelength, _fileno
#include <string.h>   // _stricmp
// Not <windows.h>: the head has already declared HANDLE, FILETIME,
// WIN32_FIND_DATAA and the manifest constants the bodies name, with the layouts
// the decompilation assumes, and it defines _WINDOWS_ to keep Hex-Rays' defs.h
// from supplying *signed* BYTE/WORD/DWORD.  Including the real header on top of
// that is a collision at best; the ten imports below are declared by hand
// instead, with the signatures the .inc files were type-checked against.
#else
#include <dirent.h>
#include <fcntl.h>
#include <fnmatch.h>
#include <limits.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#endif

// gcc checks a wrapper's format string only if told which dialect it is, and
// mingw defaults to the MS one, where %zu and friends are not accepted.
#ifdef _WIN32
#define BMF_FMT(kind, f, a) __attribute__((format(gnu_##kind, f, a)))
#else
#define BMF_FMT(kind, f, a) __attribute__((format(kind, f, a)))
#endif

// ---------------------------------------------------------------------------
// MSVC CRT
//
// The bodies call these through `#define fopen __fopen`, so the names have to
// be exactly `__` + what CRT_PROTO calls them, and the signatures have to be
// the ones extract.py would have emitted — the call sites were type-checked
// against those.
// ---------------------------------------------------------------------------
#define __PE_DECL___fopen
#define __PE_DECL___fclose
#define __PE_DECL___fread
#define __PE_DECL___fwrite
#define __PE_DECL___fseek
#define __PE_DECL___ftell
#define __PE_DECL___feof
#define __PE_DECL___ferror
#define __PE_DECL___fgetc
#define __PE_DECL___fgets
#define __PE_DECL___fflush
#define __PE_DECL___fputc
#define __PE_DECL___putc
#define __PE_DECL___fputs
#define __PE_DECL___remove
#define __PE_DECL___rename
#define __PE_DECL___printf
#define __PE_DECL___sprintf
#define __PE_DECL___sscanf
#define __PE_DECL___fprintf
#define __PE_DECL___fscanf
#define __PE_DECL___vprintf
#define __PE_DECL___exit
#define __PE_DECL___flsall
#define __PE_DECL___tmpnam
#define __PE_DECL____access
#define __PE_DECL____filelength
#define __PE_DECL____fileno
#define __PE_DECL____getch
#define __PE_DECL____strcmpi
#define __PE_DECL___irc__get_msg
#define __PE_DECL___irc__print

static inline FILE1 *__fopen(const char *p, const char *m) { return fopen(p, m); }
static inline int    __fclose(FILE1 *f)                    { return fclose(f); }
static inline unsigned __fread(void *b, unsigned s, unsigned n, FILE1 *f)
                                                           { return (unsigned)fread(b, s, n, f); }
static inline unsigned __fwrite(const void *b, unsigned s, unsigned n, FILE1 *f)
                                                           { return (unsigned)fwrite(b, s, n, f); }
static inline int    __fseek(FILE1 *f, long o, int w)      { return fseek(f, o, w); }
static inline long   __ftell(FILE1 *f)                     { return ftell(f); }
static inline int    __feof(FILE1 *f)                      { return feof(f); }
static inline int    __ferror(FILE1 *f)                    { return ferror(f); }
static inline int    __fgetc(FILE1 *f)                     { return fgetc(f); }
static inline char  *__fgets(char *s, int n, FILE1 *f)     { return fgets(s, n, f); }
static inline int    __fflush(FILE1 *f)                    { return fflush(f); }
static inline int    __fputc(int c, FILE1 *f)              { return fputc(c, f); }
static inline int    __putc(int c, FILE1 *f)               { return fputc(c, f); }
static inline int    __fputs(const char *s, FILE1 *f)      { return fputs(s, f); }
static inline int    __remove(const char *p)               { return remove(p); }
static inline int    __rename(const char *a, const char *b){ return rename(a, b); }
static inline void   __exit(int c)                         { exit(c); }

// _flsall(1) is MSVC's "flush every stream"; its argument is the commit flag,
// which glibc has no equivalent of and which BMF never varies.
static inline int __flsall(int) { return fflush(nullptr); }

#ifdef _WIN32
// All six are msvcrt's own, under the names it gives them.
static inline int  ___access(const char *p, int m)  { return _access(p, m); }
static inline int  ___fileno(FILE1 *f)              { return _fileno(f); }
static inline int  ___strcmpi(const char *a, const char *b) { return _stricmp(a, b); }
static inline long ___filelength(int fd)            { return _filelength(fd); }
static inline int  ___getch()                       { return _getch(); }
#else
// MSVC's _access takes 0/2/4/6 for exist/write/read/both, which are F_OK/W_OK/
// R_OK and their union — the same numbers POSIX uses.
static inline int  ___access(const char *p, int m)  { return access(p, m); }
static inline int  ___fileno(FILE1 *f)              { return fileno(f); }
static inline int  ___strcmpi(const char *a, const char *b) { return strcasecmp(a, b); }

static inline long ___filelength(int fd) {
  struct stat st;
  return fstat(fd, &st) == 0 ? (long)st.st_size : -1L;
}

// _getch reads one keystroke without waiting for Enter.  BMF uses it for the
// "overwrite? (y/n)" prompt, where line buffering only means the user has to
// press Return as well — not worth putting the terminal in raw mode for.
static inline int ___getch() { return getchar(); }
#endif

// Not `#define printf ::printf`: the bodies say `printf(...)` and the .inc
// says `#define printf __printf`, so the name that has to exist is __printf.
// gcc will not check the format string through a wrapper, hence the attribute.
BMF_FMT(printf, 1, 2)
static int __printf(const char *f, ...) {
  va_list a; va_start(a, f);
  int r = vprintf(f, a);
  va_end(a);
  return r;
}
BMF_FMT(printf, 2, 3)
static int __sprintf(char *s, const char *f, ...) {
  va_list a; va_start(a, f);
  int r = vsprintf(s, f, a);
  va_end(a);
  return r;
}
BMF_FMT(scanf, 2, 3)
static int __sscanf(const char *s, const char *f, ...) {
  va_list a; va_start(a, f);
  int r = vsscanf(s, f, a);
  va_end(a);
  return r;
}
BMF_FMT(printf, 2, 3)
static int __fprintf(FILE1 *s, const char *f, ...) {
  va_list a; va_start(a, f);
  int r = vfprintf(s, f, a);
  va_end(a);
  return r;
}
BMF_FMT(scanf, 2, 3)
static int __fscanf(FILE1 *s, const char *f, ...) {
  va_list a; va_start(a, f);
  int r = vfscanf(s, f, a);
  va_end(a);
  return r;
}

// exit_402E40 calls this as `vprintf(fmt, &ArgList)`, where ArgList is its own
// last named parameter — so the pointer is into the incoming argument block and
// the remaining arguments follow it.  On i386 SysV a va_list *is* that pointer
// (`typedef char *__builtin_va_list`), which is why the void* form works.
static int __vprintf(const char *f, void *ap) {
  return vprintf(f, (va_list)ap);
}

// MSVC's tmpnam returns a name in the current directory and does not create
// the file; the caller renames the real file onto it and back, so it has to
// land on the same filesystem.  L_tmpnam-style "/tmp/..." would not.
static char *__tmpnam(char *buf) {
  static unsigned seq = 0;
  static char own[64];
  char *out = buf ? buf : own;
  for (;;) {
    sprintf(out, "bmf%05u.tmp", seq++ & 0xFFFFF);
    if (___access(out, 0) != 0)   // 0 is "does it exist" on both hosts
      return out;
  }
}

// Intel's runtime error reporter, reached only from sub_4346D0's
// "this CPU has no SSE2" path — which cannot be taken, since the moved bodies
// are full of SSE2 and would have faulted long before.  Kept so that path
// still compiles and says something if it ever runs.
static char *__irc__get_msg(int a, int b, void *) {
  static char msg[64];
  sprintf(msg, "Intel runtime message %d/%d", a, b);
  return msg;
}
BMF_FMT(printf, 1, 2)
static int __irc__print(const char *f, ...) {
  va_list a; va_start(a, f);
  int r = vfprintf(stderr, f, a);
  va_end(a);
  return r;
}

// ---------------------------------------------------------------------------
// operator new / delete
//
// malloc/free rather than ::operator new: MSVC's returns null when it cannot
// allocate and BMF tests for that (`if ( void *p = operator new(8u) )`), while
// C++'s throws — and there is no handler here to catch it.
// ---------------------------------------------------------------------------
#define __PE_DECL___op_new
#define __PE_DECL___op_delete
static inline void *__op_new(unsigned int n) { return malloc(n ? n : 1); }
static inline void  __op_delete(void *p)     { free(p); }

// ---------------------------------------------------------------------------
// Intel's memcpy/memset dispatchers.
//
// __intel_fast_memcpy and __intel_fast_memset pick an implementation from the
// CPU features they cached at startup.  glibc's do the same thing through an
// IFUNC, so these are memcpy and memset — both return their destination, which
// is what the call sites expect.
// ---------------------------------------------------------------------------
#define __PE_DECL___sub_434980
#define __PE_DECL___sub_4349F0
static inline void *__sub_434980(void *d, const void *s, unsigned int n) { return memcpy(d, s, n); }
static inline void *__sub_4349F0(void *d, int c, unsigned int n)         { return memset(d, c, n); }

// sub_402E30 is `push 7; call exit_402E40` — the out-of-memory handler main
// hands to sub_42CBB0.  IDA's call analysis failed on it (hence "no decompiled
// body" in the generated declaration), but the two instructions are not in
// doubt.  Defined after the bodies, since exit_402E40 is one of them.
#define __PE_DECL___sub_402E30
void __sub_402E30();

// ---------------------------------------------------------------------------
// kernel32
// ---------------------------------------------------------------------------
#define __PE_DECL___VirtualAlloc
#define __PE_DECL___VirtualFree
#define __PE_DECL___CreateFileA
#define __PE_DECL___CloseHandle
#define __PE_DECL___SetFileTime
#define __PE_DECL___SetFileAttributesA
#define __PE_DECL___DosDateTimeToFileTime
#define __PE_DECL___FileTimeToDosDateTime
#define __PE_DECL___FindFirstFileA
#define __PE_DECL___FindNextFileA
#ifdef _WIN32
// On Windows there is nothing to reimplement: these are the ten imports BMF's
// IAT held, and the program is asking kernel32 for them again.  Declared by
// hand rather than through <windows.h>, for the reason at the top of the file,
// with the signatures extract.py's WINAPI_PROTO gave the call sites — every
// pointer parameter relaxed to void*, which is ABI-identical and saves
// dragging in the SDK's typedefs.  The head already has WIN32_FIND_DATAA at
// the layout FindFirstFileA writes.
//
// FindClose is missing because BMF never calls it: it enumerates once per
// command-line argument and lets the handle go.  That is the donor's
// behaviour, not an omission here.
#define BMF_WINAPI extern "C" __declspec(dllimport) __attribute__((stdcall))
BMF_WINAPI void *VirtualAlloc(void *, unsigned int, unsigned int, unsigned int);
BMF_WINAPI int   VirtualFree(void *, unsigned int, unsigned int);
BMF_WINAPI void *CreateFileA(const char *, unsigned int, unsigned int, void *,
                             unsigned int, unsigned int, void *);
BMF_WINAPI int   CloseHandle(void *);
BMF_WINAPI int   SetFileTime(void *, const void *, const void *, const void *);
BMF_WINAPI int   SetFileAttributesA(const char *, unsigned int);
BMF_WINAPI int   DosDateTimeToFileTime(unsigned short, unsigned short, void *);
BMF_WINAPI int   FileTimeToDosDateTime(const void *, unsigned short *, unsigned short *);
BMF_WINAPI void *FindFirstFileA(const char *, void *);
BMF_WINAPI int   FindNextFileA(void *, void *);
#else
// 100ns ticks between 1601-01-01 and the Unix epoch.
#define BMF_FILETIME_EPOCH 116444736000000000ULL

static inline unsigned long long bmf_ft_to_u64(const FILETIME &ft) {
  return ((unsigned long long)ft.dwHighDateTime << 32) | ft.dwLowDateTime;
}

// VirtualAlloc's block is zero-filled and page-aligned, which malloc's is not,
// and BMF asks for a megabyte at a time — so mmap, not calloc.  VirtualFree is
// given only MEM_RELEASE (size 0), so the size has to be remembered; there are
// never more than a couple of these alive at once.
static struct { void *p; size_t n; } bmf_vm[16];

static __attribute__((stdcall))
void *VirtualAlloc(void *addr, unsigned int size, unsigned int type, unsigned int prot) {
  (void)addr; (void)type; (void)prot;
  void *p = mmap(nullptr, size, PROT_READ | PROT_WRITE,
                 MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
  if (p == MAP_FAILED)
    return nullptr;
  for (auto &s : bmf_vm)
    if (!s.p) { s.p = p; s.n = size; return p; }
  munmap(p, size);   // table full: fail the allocation rather than leak it
  return nullptr;
}

static __attribute__((stdcall))
int VirtualFree(void *p, unsigned int size, unsigned int type) {
  (void)size; (void)type;
  for (auto &s : bmf_vm)
    if (s.p == p) { munmap(s.p, s.n); s.p = nullptr; return 1; }
  return 0;
}

// A HANDLE is fd+1, so that fd 0 is not mistaken for NULL and no valid handle
// collides with INVALID_HANDLE_VALUE.  Only CreateFileA/SetFileTime/
// CloseHandle use file handles, and BMF holds one at a time.
static __attribute__((stdcall))
void *CreateFileA(const char *name, unsigned int access, unsigned int share,
                  void *sa, unsigned int disp, unsigned int flags, void *tmpl) {
  (void)share; (void)sa; (void)flags; (void)tmpl;
  int oflags = (access & GENERIC_WRITE) ? ((access & GENERIC_READ) ? O_RDWR : O_WRONLY)
                                        : O_RDONLY;
  if (disp == CREATE_ALWAYS)
    oflags |= O_CREAT | O_TRUNC;
  int fd = open(name, oflags, 0666);
  return fd < 0 ? INVALID_HANDLE_VALUE : (void *)(intptr_t)(fd + 1);
}

static __attribute__((stdcall)) int CloseHandle(void *h) {
  intptr_t fd = (intptr_t)h - 1;
  return (h == INVALID_HANDLE_VALUE || fd < 0) ? 0 : close((int)fd) == 0;
}

static __attribute__((stdcall))
int SetFileTime(void *h, const void *ctime, const void *atime, const void *mtime) {
  (void)ctime;
  intptr_t fd = (intptr_t)h - 1;
  if (h == INVALID_HANDLE_VALUE || fd < 0)
    return 0;
  struct timespec ts[2];
  const FILETIME *in[2] = { (const FILETIME *)atime, (const FILETIME *)mtime };
  for (int i = 0; i < 2; i++) {
    if (!in[i]) { ts[i].tv_sec = 0; ts[i].tv_nsec = UTIME_OMIT; continue; }
    unsigned long long v = bmf_ft_to_u64(*in[i]);
    v = v < BMF_FILETIME_EPOCH ? 0 : v - BMF_FILETIME_EPOCH;
    ts[i].tv_sec  = (time_t)(v / 10000000ULL);
    ts[i].tv_nsec = (long)((v % 10000000ULL) * 100);
  }
  return futimens((int)fd, ts) == 0;
}

// The only attribute BMF sets is FILE_ATTRIBUTE_NORMAL, to clear the read-only
// bit it set earlier — so this is a chmod of the write bits and nothing else.
static __attribute__((stdcall))
int SetFileAttributesA(const char *path, unsigned int attrs) {
  struct stat st;
  if (stat(path, &st) != 0)
    return 0;
  mode_t m = st.st_mode;
  if (attrs & 0x01)   // FILE_ATTRIBUTE_READONLY
    m &= ~(mode_t)(S_IWUSR | S_IWGRP | S_IWOTH);
  else
    m |= S_IWUSR;
  return chmod(path, m) == 0;
}

// FAT date/time, which is what BMF stores in the archive header: date is
// (year-1980)<<9 | month<<5 | day, time is hour<<11 | minute<<5 | second/2.
// UTC on both sides, so the pair round-trips exactly.
static __attribute__((stdcall))
int FileTimeToDosDateTime(const void *pft, unsigned short *date, unsigned short *tm_) {
  if (!pft || !date || !tm_)
    return 0;
  unsigned long long v = bmf_ft_to_u64(*(const FILETIME *)pft);
  if (v < BMF_FILETIME_EPOCH) { *date = *tm_ = 0; return 0; }
  time_t t = (time_t)((v - BMF_FILETIME_EPOCH) / 10000000ULL);
  struct tm g;
  gmtime_r(&t, &g);
  if (g.tm_year < 80) { *date = *tm_ = 0; return 0; }
  *date = (unsigned short)(((g.tm_year - 80) << 9) | ((g.tm_mon + 1) << 5) | g.tm_mday);
  *tm_  = (unsigned short)((g.tm_hour << 11) | (g.tm_min << 5) | (g.tm_sec >> 1));
  return 1;
}

static __attribute__((stdcall))
int DosDateTimeToFileTime(unsigned short date, unsigned short tm_, void *pft) {
  if (!pft)
    return 0;
  struct tm g;
  memset(&g, 0, sizeof g);
  g.tm_year = ((date >> 9) & 0x7F) + 80;
  g.tm_mon  = ((date >> 5) & 0x0F) - 1;
  g.tm_mday = date & 0x1F;
  g.tm_hour = (tm_ >> 11) & 0x1F;
  g.tm_min  = (tm_ >> 5) & 0x3F;
  g.tm_sec  = (tm_ & 0x1F) << 1;
  unsigned long long v = (unsigned long long)timegm(&g) * 10000000ULL + BMF_FILETIME_EPOCH;
  ((FILETIME *)pft)->dwLowDateTime  = (DWORD)v;
  ((FILETIME *)pft)->dwHighDateTime = (DWORD)(v >> 32);
  return 1;
}

// FindFirstFileA/FindNextFileA over opendir + fnmatch.  main uses them for one
// enumeration at a time and never calls FindClose, so the context is a single
// static: closing it on exhaustion is what stops the descriptor leaking.
static struct BmfFind {
  DIR *dir;
  char dirpath[PATH_MAX];
  char glob[NAME_MAX + 1];
} bmf_find;

static void bmf_fill_find(WIN32_FIND_DATAA *fd, const char *dirpath, const char *name) {
  memset(fd, 0, sizeof *fd);
  char full[PATH_MAX];
  snprintf(full, sizeof full, "%s/%s", dirpath, name);
  struct stat st;
  if (stat(full, &st) != 0)
    return;
  fd->dwFileAttributes = S_ISDIR(st.st_mode) ? 0x10 /* DIRECTORY */
                                             : 0x20 /* ARCHIVE   */;
  unsigned long long v = (unsigned long long)st.st_mtime * 10000000ULL + BMF_FILETIME_EPOCH;
  fd->ftLastWriteTime.dwLowDateTime  = (DWORD)v;
  fd->ftLastWriteTime.dwHighDateTime = (DWORD)(v >> 32);
  fd->ftCreationTime = fd->ftLastAccessTime = fd->ftLastWriteTime;
  fd->nFileSizeLow  = (DWORD)((unsigned long long)st.st_size & 0xFFFFFFFFu);
  fd->nFileSizeHigh = (DWORD)((unsigned long long)st.st_size >> 32);
  snprintf(fd->cFileName, sizeof fd->cFileName, "%s", name);
}

static __attribute__((stdcall)) int FindNextFileA(void *h, void *pfd) {
  BmfFind *c = (BmfFind *)h;
  if (!c || !c->dir)
    return 0;
  for (struct dirent *e; (e = readdir(c->dir)) != nullptr; ) {
    if (e->d_name[0] == '.' && (!e->d_name[1] || (e->d_name[1] == '.' && !e->d_name[2])))
      continue;
    if (fnmatch(c->glob, e->d_name, FNM_NOESCAPE) != 0)
      continue;
    bmf_fill_find((WIN32_FIND_DATAA *)pfd, c->dirpath, e->d_name);
    return 1;
  }
  closedir(c->dir);
  c->dir = nullptr;
  return 0;
}

static __attribute__((stdcall)) void *FindFirstFileA(const char *pattern, void *pfd) {
  BmfFind *c = &bmf_find;
  if (c->dir)
    closedir(c->dir);
  char tmp[PATH_MAX];
  snprintf(tmp, sizeof tmp, "%s", pattern);
  char *slash = strrchr(tmp, '/');
  if (slash) {
    *slash = '\0';
    snprintf(c->dirpath, sizeof c->dirpath, "%s", tmp[0] ? tmp : "/");
    snprintf(c->glob, sizeof c->glob, "%s", slash + 1);
  } else {
    snprintf(c->dirpath, sizeof c->dirpath, ".");
    snprintf(c->glob, sizeof c->glob, "%s", tmp);
  }
  c->dir = opendir(c->dirpath);
  if (!c->dir)
    return INVALID_HANDLE_VALUE;
  if (!FindNextFileA(c, pfd))
    return INVALID_HANDLE_VALUE;
  return c;
}
#endif   // !_WIN32

#include "subs1.hpp"

