/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'PPMonstr.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

#define __udec
#define __off
#define __hex
#define __ptr32
#define __offset(x)
#define __bitmask

struct _CONTEXT;
struct _UNWIND_HISTORY_TABLE;
struct _IMAGE_RUNTIME_FUNCTION_ENTRY;
struct _EXCEPTION_RECORD;
struct _OVERLAPPED;
union _LARGE_INTEGER;
struct _KNONVOLATILE_CONTEXT_POINTERS;
struct _iobuf;
struct _s_ThrowInfo;

/* 1 */
struct RUNTIME_FUNCTION
{
  void *__ptr32 FunctionStart __offset(OFF64|RVAOFF);
  void *__ptr32 FunctionEnd __offset(OFF64|RVAOFF|PASTEND);
  void *__ptr32 UnwindInfo __offset(OFF64|RVAOFF);
};

/* 2 */
struct UNWIND_INFO_HDR
{
  unsigned __int8 Version : 3 __hex;
  unsigned __int8 Flags : 5 __hex;
  unsigned __int8 PrologSize __hex;
  unsigned __int8 CntUnwindCodes __hex;
  unsigned __int8 FrameRegister : 4 __hex;
  unsigned __int8 FrameOffset : 4 __hex;
};

/* 3 */
struct UNWIND_CODE
{
  char PrologOff;
  unsigned __int8 UnwindOp : 4 __udec;
  unsigned __int8 OpInfo : 4 __udec;
};

/* 4 */
enum __bitmask __TI_flags
{
  TI_IsConst = 0x1,
  TI_IsVolatile = 0x2,
  TI_IsUnaligned = 0x4,
  TI_IsPure = 0x8,
  TI_IsWinRT = 0x10,
};

/* 5 */
enum __bitmask __CT_flags
{
  CT_IsSimpleType = 0x1,
  CT_ByReferenceOnly = 0x2,
  CT_HasVirtualBase = 0x4,
  CT_IsWinRTHandle = 0x8,
  CT_IsStdBadAlloc = 0x10,
};

/* 7 */
typedef unsigned int DWORD;

/* 9 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 8 */
typedef struct _FILETIME FILETIME;

/* 10 */
typedef char CHAR;

/* 6 */
struct _WIN32_FIND_DATAA
{
  DWORD dwFileAttributes;
  FILETIME ftCreationTime;
  FILETIME ftLastAccessTime;
  FILETIME ftLastWriteTime;
  DWORD nFileSizeHigh;
  DWORD nFileSizeLow;
  DWORD dwReserved0;
  DWORD dwReserved1;
  CHAR cFileName[260];
  CHAR cAlternateFileName[14];
};

/* 11 */
typedef void *HANDLE;

/* 12 */
typedef struct _CONTEXT *PCONTEXT;

/* 14 */
typedef unsigned __int64 DWORD64;

/* 15 */
typedef unsigned __int16 WORD;

/* 20 */
typedef unsigned __int8 BYTE;

/* 23 */
typedef unsigned __int64 ULONGLONG;

/* 24 */
typedef __int64 LONGLONG;

/* 22 */
struct __declspec(align(16)) _M128A
{
  ULONGLONG Low;
  LONGLONG High;
};

/* 21 */
typedef struct _M128A M128A;

/* 19 */
struct __declspec(align(16)) _XSAVE_FORMAT
{
  WORD ControlWord;
  WORD StatusWord;
  BYTE TagWord;
  BYTE Reserved1;
  WORD ErrorOpcode;
  DWORD ErrorOffset;
  WORD ErrorSelector;
  WORD Reserved2;
  DWORD DataOffset;
  WORD DataSelector;
  WORD Reserved3;
  DWORD MxCsr;
  DWORD MxCsr_Mask;
  M128A FloatRegisters[8];
  M128A XmmRegisters[16];
  BYTE Reserved4[96];
};

/* 18 */
typedef struct _XSAVE_FORMAT XSAVE_FORMAT;

/* 17 */
typedef XSAVE_FORMAT XMM_SAVE_AREA32;

/* 13 */
struct __declspec(align(16)) _CONTEXT
{
  DWORD64 P1Home;
  DWORD64 P2Home;
  DWORD64 P3Home;
  DWORD64 P4Home;
  DWORD64 P5Home;
  DWORD64 P6Home;
  DWORD ContextFlags;
  DWORD MxCsr;
  WORD SegCs;
  WORD SegDs;
  WORD SegEs;
  WORD SegFs;
  WORD SegGs;
  WORD SegSs;
  DWORD EFlags;
  DWORD64 Dr0;
  DWORD64 Dr1;
  DWORD64 Dr2;
  DWORD64 Dr3;
  DWORD64 Dr6;
  DWORD64 Dr7;
  DWORD64 Rax;
  DWORD64 Rcx;
  DWORD64 Rdx;
  DWORD64 Rbx;
  DWORD64 Rsp;
  DWORD64 Rbp;
  DWORD64 Rsi;
  DWORD64 Rdi;
  DWORD64 R8;
  DWORD64 R9;
  DWORD64 R10;
  DWORD64 R11;
  DWORD64 R12;
  DWORD64 R13;
  DWORD64 R14;
  DWORD64 R15;
  DWORD64 Rip;
  union
  {
    XMM_SAVE_AREA32 FltSave;
    struct
    {
      M128A Header[2];
      M128A Legacy[8];
      M128A Xmm0;
      M128A Xmm1;
      M128A Xmm2;
      M128A Xmm3;
      M128A Xmm4;
      M128A Xmm5;
      M128A Xmm6;
      M128A Xmm7;
      M128A Xmm8;
      M128A Xmm9;
      M128A Xmm10;
      M128A Xmm11;
      M128A Xmm12;
      M128A Xmm13;
      M128A Xmm14;
      M128A Xmm15;
    };
  };
  M128A VectorRegister[26];
  DWORD64 VectorControl;
  DWORD64 DebugControl;
  DWORD64 LastBranchToRip;
  DWORD64 LastBranchFromRip;
  DWORD64 LastExceptionToRip;
  DWORD64 LastExceptionFromRip;
};

/* 26 */
typedef struct _UNWIND_HISTORY_TABLE *PUNWIND_HISTORY_TABLE;

/* 30 */
typedef struct _IMAGE_RUNTIME_FUNCTION_ENTRY *PRUNTIME_FUNCTION;

/* 29 */
struct _UNWIND_HISTORY_TABLE_ENTRY
{
  DWORD64 ImageBase;
  PRUNTIME_FUNCTION FunctionEntry;
};

/* 28 */
typedef struct _UNWIND_HISTORY_TABLE_ENTRY UNWIND_HISTORY_TABLE_ENTRY;

/* 27 */
struct _UNWIND_HISTORY_TABLE
{
  DWORD Count;
  BYTE LocalHint;
  BYTE GlobalHint;
  BYTE Search;
  BYTE Once;
  DWORD64 LowAddress;
  DWORD64 HighAddress;
  UNWIND_HISTORY_TABLE_ENTRY Entry[12];
};

/* 31 */
#pragma pack(push, 4)
struct _IMAGE_RUNTIME_FUNCTION_ENTRY
{
  DWORD BeginAddress;
  DWORD EndAddress;
  #pragma pack(push, 4)
  union
  {
    DWORD UnwindInfoAddress;
    DWORD UnwindData;
  };
  #pragma pack(pop)
};
#pragma pack(pop)

/* 33 */
typedef void *PVOID;

/* 34 */
typedef unsigned __int64 *PULONG64;

/* 37 */
typedef struct _EXCEPTION_RECORD EXCEPTION_RECORD;

/* 36 */
typedef EXCEPTION_RECORD *PEXCEPTION_RECORD;

/* 35 */
struct _EXCEPTION_POINTERS
{
  PEXCEPTION_RECORD ExceptionRecord;
  PCONTEXT ContextRecord;
};

/* 39 */
typedef unsigned __int64 ULONG_PTR;

/* 38 */
struct _EXCEPTION_RECORD
{
  DWORD ExceptionCode;
  DWORD ExceptionFlags;
  struct _EXCEPTION_RECORD *ExceptionRecord;
  PVOID ExceptionAddress;
  DWORD NumberParameters;
  ULONG_PTR ExceptionInformation[15];
};

/* 41 */
typedef unsigned int UINT;

/* 40 */
struct _cpinfo
{
  UINT MaxCharSize;
  BYTE DefaultChar[2];
  BYTE LeadByte[12];
};

/* 44 */
//typedef unsigned __int16 wchar_t;

/* 43 */
typedef wchar_t WCHAR;

/* 42 */
typedef WCHAR *LPWSTR;

/* 45 */
typedef const CHAR *LPCCH;

/* 46 */
typedef DWORD LCID;

/* 47 */
typedef CHAR *LPSTR;

/* 49 */
typedef int BOOL;

/* 48 */
typedef BOOL *LPBOOL;

/* 50 */
typedef struct _OVERLAPPED *LPOVERLAPPED;

/* 51 */
struct _OVERLAPPED
{
  ULONG_PTR Internal;
  ULONG_PTR InternalHigh;
  union
  {
    struct
    {
      DWORD Offset;
      DWORD OffsetHigh;
    };
    PVOID Pointer;
  };
  HANDLE hEvent;
};

/* 55 */
typedef BYTE *LPBYTE;

/* 54 */
struct _STARTUPINFOA
{
  DWORD cb;
  LPSTR lpReserved;
  LPSTR lpDesktop;
  LPSTR lpTitle;
  DWORD dwX;
  DWORD dwY;
  DWORD dwXSize;
  DWORD dwYSize;
  DWORD dwXCountChars;
  DWORD dwYCountChars;
  DWORD dwFillAttribute;
  DWORD dwFlags;
  WORD wShowWindow;
  WORD cbReserved2;
  LPBYTE lpReserved2;
  HANDLE hStdInput;
  HANDLE hStdOutput;
  HANDLE hStdError;
};

/* 56 */
typedef int LONG;

/* 57 */
typedef union _LARGE_INTEGER LARGE_INTEGER;

/* 58 */
union _LARGE_INTEGER
{
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  };
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  } u;
  LONGLONG QuadPart;
};

/* 60 */
typedef WORD *LPWORD;

/* 62 */
typedef void *LPVOID;

/* 61 */
struct _SECURITY_ATTRIBUTES
{
  DWORD nLength;
  LPVOID lpSecurityDescriptor;
  BOOL bInheritHandle;
};

/* 63 */
typedef const CHAR *LPCSTR;

/* 64 */
typedef unsigned __int64 ULONG64;

/* 65 */
typedef struct _KNONVOLATILE_CONTEXT_POINTERS *PKNONVOLATILE_CONTEXT_POINTERS;

/* 68 */
typedef struct _M128A *PM128A;

/* 71 */
typedef unsigned __int64 *PDWORD64;

/* 66 */
struct _KNONVOLATILE_CONTEXT_POINTERS
{
  union
  {
    PM128A FloatingContext[16];
    struct
    {
      PM128A Xmm0;
      PM128A Xmm1;
      PM128A Xmm2;
      PM128A Xmm3;
      PM128A Xmm4;
      PM128A Xmm5;
      PM128A Xmm6;
      PM128A Xmm7;
      PM128A Xmm8;
      PM128A Xmm9;
      PM128A Xmm10;
      PM128A Xmm11;
      PM128A Xmm12;
      PM128A Xmm13;
      PM128A Xmm14;
      PM128A Xmm15;
    };
  };
  union
  {
    PDWORD64 IntegerContext[16];
    struct
    {
      PDWORD64 Rax;
      PDWORD64 Rcx;
      PDWORD64 Rdx;
      PDWORD64 Rbx;
      PDWORD64 Rsp;
      PDWORD64 Rbp;
      PDWORD64 Rsi;
      PDWORD64 Rdi;
      PDWORD64 R8;
      PDWORD64 R9;
      PDWORD64 R10;
      PDWORD64 R11;
      PDWORD64 R12;
      PDWORD64 R13;
      PDWORD64 R14;
      PDWORD64 R15;
    };
  };
};

/* 76 */
struct _KEY_EVENT_RECORD
{
  BOOL bKeyDown;
  WORD wRepeatCount;
  WORD wVirtualKeyCode;
  WORD wVirtualScanCode;
  union
  {
    WCHAR UnicodeChar;
    CHAR AsciiChar;
  } uChar;
  DWORD dwControlKeyState;
};

/* 75 */
typedef struct _KEY_EVENT_RECORD KEY_EVENT_RECORD;

/* 82 */
typedef __int16 SHORT;

/* 81 */
struct _COORD
{
  SHORT X;
  SHORT Y;
};

/* 80 */
typedef struct _COORD COORD;

/* 79 */
struct _MOUSE_EVENT_RECORD
{
  COORD dwMousePosition;
  DWORD dwButtonState;
  DWORD dwControlKeyState;
  DWORD dwEventFlags;
};

/* 78 */
typedef struct _MOUSE_EVENT_RECORD MOUSE_EVENT_RECORD;

/* 84 */
struct _WINDOW_BUFFER_SIZE_RECORD
{
  COORD dwSize;
};

/* 83 */
typedef struct _WINDOW_BUFFER_SIZE_RECORD WINDOW_BUFFER_SIZE_RECORD;

/* 86 */
struct _MENU_EVENT_RECORD
{
  UINT dwCommandId;
};

/* 85 */
typedef struct _MENU_EVENT_RECORD MENU_EVENT_RECORD;

/* 88 */
struct _FOCUS_EVENT_RECORD
{
  BOOL bSetFocus;
};

/* 87 */
typedef struct _FOCUS_EVENT_RECORD FOCUS_EVENT_RECORD;

/* 73 */
struct _INPUT_RECORD
{
  WORD EventType;
  union
  {
    KEY_EVENT_RECORD KeyEvent;
    MOUSE_EVENT_RECORD MouseEvent;
    WINDOW_BUFFER_SIZE_RECORD WindowBufferSizeEvent;
    MENU_EVENT_RECORD MenuEvent;
    FOCUS_EVENT_RECORD FocusEvent;
  } Event;
};

#if 0
/* 89 */
typedef struct _iobuf FILE;

/* 90 */
struct _iobuf
{
  char *_ptr;
  int _cnt;
  char *_base;
  int _flag;
  int _file;
  int _charbuf;
  int _bufsiz;
  char *_tmpfname;
};
#endif

/* 91 */
//typedef unsigned __int64 uintptr_t;

#if 0
/* 92 */
#pragma pack(push, 8)
struct __crt_locale_pointers
{
  struct __crt_locale_data *locinfo;
  struct __crt_multibyte_data *mbcinfo;
};
#pragma pack(pop)
#endif

/* 94 */
typedef const struct _s_ThrowInfo ThrowInfo;

/* 93 */
typedef ThrowInfo _ThrowInfo;

/* 96 */
typedef int PMFN;

/* 95 */
#pragma pack(push, 4)
struct _s_ThrowInfo
{
  unsigned int attributes;
  PMFN pmfnUnwind;
  int pForwardCompat;
  int pCatchableTypeArray;
};
#pragma pack(pop)

/* 97 */
//typedef __crt_locale_pointers *_locale_t;

/* 98 */
struct C_SCOPE_TABLE
{
  void *__ptr32 Begin __offset(OFF64|RVAOFF);
  void *__ptr32 End __offset(OFF64|RVAOFF|PASTEND);
  void *__ptr32 Handler __offset(OFF64|RVAOFF);
  void *__ptr32 Target __offset(OFF64|RVAOFF);
};

/* 99 */
//struct std::exception;

/* 100 */
struct _LocaleUpdate;

/* 101 */
struct struct_101
{
  __int64 field_0 __udec;
  __int64 field_8 __off;
};

