#!/bin/sh
# Assembles the source package of the Windows build (run by "make source-package"): the sources
# that the Windows build compiles and every file they include (taken from the dependency files
# of the build), including the files the build generated; the parts of Boost that ROSE uses
# (selected with Boost's bcp tool); the run-time files of the binary package; and
# win32/source/Makefile, with which mingw32-make builds the translators on Windows from these
# files alone.
#
# usage: scripts/windows-source-package.sh <variables file written by the Makefile>
set -eu
. "$1"

# The Boost libraries whose compiled parts the translators link (the rest of Boost that ROSE
# uses is header-only), and the options that Boost's own build (b2 target-os=windows
# threadapi=win32 link=static) compiles them with
BOOST_LIBS="filesystem iostreams regex thread wave"
BOOST_SRCS_filesystem="codecvt_error_category directory exception operations path path_traits
  unique_path windows_file_codecvt"
BOOST_SRCS_iostreams="mapped_file"
BOOST_SRCS_regex="posix_api"
BOOST_SRCS_thread="win32/thread win32/tss_pe"
BOOST_SRCS_wave="instantiate_cpp_exprgrammar instantiate_cpp_grammar instantiate_cpp_literalgrs
  instantiate_defined_grammar instantiate_has_include_grammar instantiate_predef_macros
  instantiate_re2c_lexer_str token_ids cpplexer/re2clex/aq cpplexer/re2clex/cpp_re"
BOOST_FLAGS="-std=gnu++17 \$(OPT) -m64 -mthreads -finline-functions -fvisibility=hidden
  -fvisibility-inlines-hidden -w -DNDEBUG -DBOOST_ALL_NO_LIB=1 -Isrc/boost"
BOOST_FLAGS_filesystem="-DBOOST_ATOMIC_STATIC_LINK=1 -DBOOST_FILESYSTEM_HAS_BCRYPT
  -DBOOST_FILESYSTEM_HAS_INIT_PRIORITY -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF
  -DBOOST_FILESYSTEM_SOURCE -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_USE_WINDOWS_H -DNOMINMAX
  -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS
  -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -Isrc/boost/libs/filesystem/src"
BOOST_FLAGS_iostreams="-DBOOST_IOSTREAMS_USE_DEPRECATED"
BOOST_FLAGS_regex=""
BOOST_FLAGS_thread="-DBOOST_CHRONO_STATIC_LINK=1 -DBOOST_THREAD_BUILD_LIB=1
  -DBOOST_THREAD_USES_CHRONO -DBOOST_THREAD_WIN32 -DBOOST_USE_WINDOWS_H -DWIN32_LEAN_AND_MEAN"
BOOST_FLAGS_wave="-DBOOST_THREAD_USE_LIB=1"

[ -x "$BCP" ] || { echo "$BCP: not found (build it with ./b2 tools/bcp in $BOOST_SRC)" >&2; exit 1; }
rm -rf "$OUT" "$ARCHIVE"
mkdir -p "$OUT/src"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT INT TERM

# The run-time files of the binary package (all but the programs)
cp -R "$PKG_DIR/." "$OUT/"
rm -rf "$OUT/bin"

# Where a file used by the build goes in the package
dest_of() {
  case $1 in
    "$GEN"/*) echo "src/gen/${1#"$GEN"/}" ;;
    /*) echo "$1: outside the source tree and the build's generated files" >&2; echo "" ;;
    *) echo "src/$1" ;;
  esac
}

# The group of options an object is compiled with
group_of() {
  case " $LP64_OBJS " in *" $1 "*) echo rose_lp64; return ;; esac
  case " $API_OBJS " in *" $1 "*) echo rose_winapi; return ;; esac
  case $1 in
    */utility_functions.o) echo rose_boostpath ;;
    "$OBJ"/edg/*) echo edg ;;
    "$OBJ"/edg2sage/*) echo edg2sage ;;
    "$OBJ"/tools/*) echo tools ;;
    *) echo rose ;;
  esac
}

# The source of each object (the first prerequisite in its dependency file), by group
for o in $LIB_OBJS $TOOL_OBJS; do
  s=$(tr '\\\n' '  ' < "${o%.o}.d" | sed 's/^[^:]*: *//; s/ .*//')
  echo "$(dest_of "$s")" >> "$tmp/srcs.$(group_of "$o")"
done

# Every file the objects were compiled from (non-system headers included)
for o in $LIB_OBJS $TOOL_OBJS; do cat "${o%.o}.d"; done | tr ' \\' '\n\n' | sed -n 's/:$//; /./p' |
  grep -v '\.o$' | sort -u > "$tmp/files"
while read -r f; do
  d=$(dest_of "$f")
  [ -n "$d" ] || exit 1
  mkdir -p "$OUT/$(dirname "$d")"
  cp "$f" "$OUT/$d"
done < "$tmp/files"

# Boost: the headers that these files and the compiled Boost sources include, directly or not
mkdir -p "$tmp/bcp" "$OUT/src/boost/libs"
for lib in $BOOST_LIBS; do
  mkdir -p "$OUT/src/boost/libs/$lib"
  cp -R "$BOOST_SRC/libs/$lib/src" "$OUT/src/boost/libs/$lib/"
done
find "$OUT/src/boost/libs" -type f > "$tmp/boost-files"
"$BCP" --boost="$BOOST_SRC" --scan $(cat "$tmp/files" "$tmp/boost-files") "$tmp/bcp" > "$tmp/bcp.log"
cp -R "$tmp/bcp/boost" "$OUT/src/boost/"
cp "$BOOST_SRC/LICENSE_1_0.txt" "$OUT/src/boost/"

# src/sources.mk: the source files of each group and the options they are compiled with (the
# paths made relative to the package, with the optimization level as $(OPT))
rewrite() {
  printf ' %s ' "$1" | tr '\n' ' ' | sed -e "s| $OPT | \$(OPT) |" -e "s|$GEN|src/gen|g" \
    -e "s|-isystem $BOOST_INC |-isystem src/boost |g" \
    -e 's#\(-I\|-include \)\(rose\|edg\|edg2sage\|win32\|tools\)\([/ ]\)#\1src/\2\3#g' \
    -e 's/  */ /g; s/^ //; s/ $//'
}
ROSE=$(rewrite "$ROSE_FLAGS")
groups=
{
  echo "# Generated by \"make source-package\": the groups of source files, and the options each"
  echo "# group is compiled with (passed to the compiler in obj/<group>.rsp)"
  for g in rose rose_lp64 rose_winapi rose_boostpath edg edg2sage tools; do
    case $g in
      rose|tools) flags=$ROSE ;;
      rose_lp64) flags="$ROSE -fpermissive" ;;
      rose_winapi) flags="$ROSE -include src/win32/windows_api.h" ;;
      rose_boostpath) flags="$ROSE -DROSE_BOOST_PATH='\"\"'" ;;
      edg) flags=$(rewrite "$EDG_FLAGS") ;;
      edg2sage) flags=$(rewrite "$CONN_FLAGS") ;;
    esac
    groups="$groups $g"
    echo
    echo "SRCS_$g := \\"
    sort "$tmp/srcs.$g" | sed 's/^/  /; s/$/ \\/'
    echo
    echo "FLAGS_$g := $flags"
  done
  for lib in $BOOST_LIBS; do
    g=boost_$lib
    groups="$groups $g"
    eval "srcs=\$BOOST_SRCS_$lib flags=\$BOOST_FLAGS_$lib"
    echo
    echo "SRCS_$g := \\"
    for s in $srcs; do echo "  src/boost/libs/$lib/src/$s.cpp \\"; done
    echo
    echo "FLAGS_$g := $(echo $BOOST_FLAGS $flags)"
  done
  echo
  echo "GROUPS :=$groups"
} > "$OUT/src/sources.mk"

cp win32/source/Makefile "$OUT/"
sed 's/$/\r/' win32/source/BUILD.txt > "$OUT/BUILD.txt"

# A solid 7z archive (much smaller than a zip file: the sources are similar to each other)
if command -v 7z > /dev/null; then
  (cd "$(dirname "$OUT")" && 7z a -t7z -mx=9 -ms=on -mmt=1 "$ARCHIVE" "$(basename "$OUT")" > /dev/null)
else
  echo "7z not found: the package is in $OUT" >&2
fi
