/*
 * EDG front end configuration used by ROSE (included before every EDG header, both when
 * compiling the EDG sources and when compiling edg2sage).
 *
 * The base configuration (target/host/GNU-emulation settings for x86_64 Linux with GCC) is
 * cmake_defines.h, generated by EDG's own CMake build for the "linux-gcc-release" macro
 * configuration.  The settings below turn EDG into a library that hands its complete,
 * unlowered intermediate language (IL) to a non-EDG back end: edg2sage's back_end(),
 * which translates the IL into ROSE's Sage III AST.
 */
#ifndef EDG2SAGE_EDG_CONFIG_H
#define EDG2SAGE_EDG_CONFIG_H

/* Callable front end: edg::edg2sage_cfe_main(argc, argv) returns instead of exiting. */
#define EDG_MAIN edg2sage_cfe_main
#define MAKE_FRONT_END_CALLABLE 1

/* Neither EDG back end is used; EDG calls the global ::back_end() provided by edg2sage. */
#define BACK_END_IS_C_GEN_BE 0
#define BACK_END_IS_CP_GEN_BE 0
#define BACK_END_SHOULD_BE_CALLED 1

/* Keep the IL as written by the user: no lowering to C, IL kept in memory. */
#define DO_IL_LOWERING 0
#define DOING_SOURCE_ANALYSIS 1
#define IL_SHOULD_BE_WRITTEN_TO_FILE 0

/* Source sequence lists give the declarations/statements of each scope in source order. */
#define GENERATE_SOURCE_SEQUENCE_LISTS 1

/* asm operand constraints are kept as written (ROSE's SgAsmOp constraint strings). */
#define RECORD_RAW_ASM_OPERAND_DESCRIPTIONS 1

/* Allow the IL to be dumped (--display_il style) for debugging the translation. */
#define NEED_IL_DISPLAY 1

#endif
