/*
 * EDG front end configuration used by ROSE (included before every EDG header, both when
 * compiling the EDG sources and when compiling edg2sage).
 *
 * The base configuration (target/host/GNU-emulation settings for x86_64 Linux with GCC) is
 * cmake_defines.h, generated by EDG's own CMake build for the "linux-gcc-release" macro
 * configuration.  The settings below turn EDG into a library that hands its complete,
 * unlowered intermediate language (IL) to a non-EDG back end: edg2sage's back_end(),
 * which translates the IL into ROSE's Sage III AST.
 */
#ifndef EDG2SAGE_EDG_CONFIG_H
#define EDG2SAGE_EDG_CONFIG_H

/* Callable front end: edg::edg2sage_cfe_main(argc, argv) returns instead of exiting. */
#define EDG_MAIN edg2sage_cfe_main
#define MAKE_FRONT_END_CALLABLE 1

/* Neither EDG back end is used; EDG calls the global ::back_end() provided by edg2sage. */
#define BACK_END_IS_C_GEN_BE 0
#define BACK_END_IS_CP_GEN_BE 0
#define BACK_END_SHOULD_BE_CALLED 1

/* Keep the IL as written by the user: no lowering to C, IL kept in memory. */
#define DO_IL_LOWERING 0
#define DOING_SOURCE_ANALYSIS 1
#define IL_SHOULD_BE_WRITTEN_TO_FILE 0

/* Source sequence lists give the declarations/statements of each scope in source order. */
#define GENERATE_SOURCE_SEQUENCE_LISTS 1

/* No compiler-generated deallocation of variable length arrays (it would add
   temporaries for return values, for instance). */
#define VLA_DEALLOCATIONS_IN_IL 0

/* asm operand constraints are kept as written (ROSE's SgAsmOp constraint strings). */
#define RECORD_RAW_ASM_OPERAND_DESCRIPTIONS 1

/* The text of each template declaration is kept in the IL: ROSE prints
   template declarations from that text (SgTemplate*Declaration::get_string()). */
#define RECORD_TEMPLATE_STRINGS 1

/* The form of names as written is recorded (e.g. whether a member function
   was named with a qualifier), without the extra "lexical" typerefs. */
#define DEFAULT_RECORD_FORM_OF_NAME_REFERENCE 1
#define CREATE_LEXICAL_TYPEREFS 0

/* Allow the IL to be dumped (--display_il style) for debugging the translation. */
#define NEED_IL_DISPLAY 1

/* Code compiled by MinGW-w64 GCC (Windows) */
#ifdef EDG2SAGE_TARGET_MINGW
#include "mingw_x86_64.h"
#endif

/* EDG built with MinGW-w64 GCC (Windows host): source files are read as UTF-8, as on Linux and
   as GCC does, rather than in the encoding of the Windows locale (which EDG supports only when
   built with Visual C++). */
#if defined(_WIN32) && !defined(_MSC_VER)
#define NATIVE_MULTIBYTE_CHARS_SUPPORTED_WITH_UNICODE 0
/* C++/CLI support needs the .NET hosting API (<metahost.h>), which MinGW-w64 lacks (these are
   the settings of EDG's "cppcli/off" configuration). */
#define CPPCLI_ENABLING_POSSIBLE 0
#define CPPCX_ENABLING_POSSIBLE 0
#define ALLOW_CPPCLI_AND_CPPCX_WITH_LOWERING 0
#define READ_CPPCLI_PORTABLE_ASSEMBLIES 0
/* EDG's Windows code uses fabs without including <math.h> (Visual C++ declares it elsewhere). */
#include <math.h>
#endif

#endif
