// x86enc.hpp -- encode an x86insn_t back to bytes (the inverse of the decode FSM).
//
// Data-driven from x86_tables_enc.h (generated by gasm.py): per mnemonic, a list
// of candidate encodings. The encoder
//   1. enumerates the candidates whose operand signature matches the insn,
//   2. picks matching[in->enc] -- the `enc` witness records WHICH equal-cost
//      encoding the bytes used (e.g. inc via 40+r vs FF/0, add eax,imm via
//      05 vs 83 vs 81), so a decoded insn re-encodes to the very same bytes,
//   3. replays the prefix run from pfx[] (lossless for decoded input), then
//      emits opcode(+embedded reg/cc/digit), ModR/M-SIB-disp, and the immediate.
//
// The ModR/M/SIB/disp emitter is canonical (shortest disp, SIB only when forced).
// The decode demo is all-canonical, so the disp_w/sib/sscale witness fields are
// not consulted here; they are the hook for reproducing non-canonical addressing.

#ifndef X86ENC_HPP
#define X86ENC_HPP

#include "x86_tables.h"
#include "x86_tables_enc.h"
#include "x86insn.hpp"
#include <stdint.h>

// ---- operand classes ------------------------------------------------------
static inline int enc_op_class(const x86op_t* o) {
  switch (o->type) {
    case T_GPR:  return C_GREG;  case T_GPR8: return C_RGB;
    case T_GPRdq: return C_GREG;                          // r32/r64 GPR (mandatory-66 SSE ops)
    case T_GPRq:  return C_GREG;                          // r64 GPR (vmread/vmwrite)
    case T_GPRw:  return C_GREG;                          // r16 GPR (movzx/movsx word src)
    case T_XMM:  return C_XMM;   case T_MMX:  return C_MM;
    case T_SREG: return C_SREG;  case T_MEM:  return C_MEM;
    case T_BND:  return C_BND;
    case T_IMM:  return C_IMM;   case T_REL:  return C_REL;
    case T_IMM2: return C_IMM;                            // extrq/insertq 2nd imm8
    default:     return C_NONE;
  }
}
static inline int enc_file_class(int opf, int has66, int reptype) {
  switch (opf) {
    case OPF_RGB:    return C_RGB;  case OPF_XMM: return C_XMM;
    case OPF_MM:     return C_MM;   case OPF_SREG: return C_SREG;
    case OPF_SSE_OS: return (has66 || reptype) ? C_XMM : C_MM;   // bank by 66/F3/F2, not REX.W
    case OPF_MMG:    return reptype ? C_GREG : C_MM;      // cvt*: GPR at F3/F2, mm at NP/66
    case OPF_BND:    return C_BND;                        // MPX bound register
    default:         return C_GREG;                       // OPF_GREG
  }
}

// Does candidate c encode this insn's operand shape? If so, report which insn
// operand fills the reg-field slot, the r/m slot, and the immediate (-1 = none).
static inline bool enc_cand_roles(const struct EncCand* c, const x86insn_t* in,
                                  int* reg_oi, int* rm_oi, int* imm_oi) {
  *reg_oi = *rm_oi = *imm_oi = -1;
  int n = in->n_ops;
  int rept = 0, has66 = 0;                               // 66/F3/F2 select the xmm bank for SSE_OS
  for (int i = 0; i < in->n_pfx; ++i) {
    if (in->pfx[i] == 0xd5) { ++i; continue; }           // REX2: skip its payload (may be f2/f3)
    if (in->pfx[i] == 0xf3) rept = 1; else if (in->pfx[i] == 0xf2) rept = 2;
    else if (in->pfx[i] == 0x66) has66 = 1;
  }
  #define CLS(i) enc_op_class(&in->op[i])
  // r/m slot i accepts memory (if sup_mem) or a register of mfile (if sup_reg)
  #define RM_OK(i) ( (CLS(i) == C_MEM) ? c->sup_mem \
                     : (c->sup_reg && CLS(i) == enc_file_class(c->mfile, has66, rept)) )
  switch (c->form) {
    case FORM_NONE: return n == 0;
    case FORM_MODRM: {
      int nimm = (c->imk == IMK_IMM8X2) ? 2 : (c->imk != IMK_NONE ? 1 : 0);  // insertq: 2 imm8
      if (n != 2 + nimm) return false;
      int ri = c->dir ? 1 : 0, mi = c->dir ? 0 : 1;     // dir: 0=reg,r/m  1=r/m,reg
      if (CLS(ri) != enc_file_class(c->rfile, has66, rept)) return false;
      if (!RM_OK(mi)) return false;
      *reg_oi = ri; *rm_oi = mi;
      if (nimm) { if (CLS(2) != C_IMM) return false; *imm_oi = 2;
                  if (nimm == 2 && CLS(3) != C_IMM) return false; }
      return true;
    }
    case FORM_RM: {
      int nimm = (c->imk == IMK_IMM8X2) ? 2 : (c->imk != IMK_NONE ? 1 : 0);   // extrq: 2 imm8
      if (!RM_OK(0)) return false;
      *rm_oi = 0;
      if (n != 1 + nimm) return false;
      if (nimm) { if (CLS(1) != C_IMM) return false; *imm_oi = 1;
                  if (nimm == 2 && CLS(2) != C_IMM) return false; }
      return true;
    }
    case FORM_REG:
      if (n != 1 || CLS(0) != enc_file_class(c->rfile, has66, rept)) return false;
      *reg_oi = 0; return true;
    case FORM_ACC:                                       // implicit eAX/al + imm
    case FORM_REG_IMM:
      if (n != 2 || CLS(0) != enc_file_class(c->rfile, has66, rept) || CLS(1) != C_IMM)
        return false;
      if (c->reg0 && in->op[0].index != 0) return false; // implicit eAX/al
      *reg_oi = 0; *imm_oi = 1; return true;
    case FORM_IMM:
      if (n != 1 || CLS(0) != C_IMM) return false;
      *imm_oi = 0; return true;
    case FORM_REL:
      if (n != 1 || CLS(0) != C_REL) return false;
      *imm_oi = 0; return true;
    case FORM_GROUP: {
      int need = (c->imk != IMK_NONE) ? 2 : 1;
      if (n != need || !RM_OK(0)) return false;
      *rm_oi = 0;
      if (need == 2) { if (CLS(1) != C_IMM) return false; *imm_oi = 1; }
      return true;
    }
    case FORM_PTR:
      if (n != 1 || in->op[0].type != T_PTR) return false;
      *imm_oi = 0; return true;
    default: return false;                               // (none left)
  }
  #undef CLS
  #undef RM_OK
}

// Pick the matching candidate at rank `enc` (0 = first / canonical).
static inline const struct EncCand* enc_select(const x86insn_t* in,
                                               int* reg_oi, int* rm_oi, int* imm_oi) {
  uint16_t mnem = in->mnem;
  if (mnem == MNEM_WRSSQ) mnem = MNEM_WRSSD;   // wrssq shares wrssd's encoding (0F38 F6; REX.W in pfx)
  // movq mm/xmm<->r64 and movq mm/xmm,[m64] (0F 6E/7E under REX.W) share movd's byte encoding
  // (REX.W rides in pfx[]); decode reclassified movd -> the distinct MNEM_MOVQ_GPR, so this
  // aliases straight back to movd without disturbing 0F 6F's real movq.
  if (mnem == MNEM_MOVQ_GPR) mnem = MNEM_MOVD;
  if (mnem >= enc_nmnem) return 0;
  int start = enc_bucket_start[mnem], cnt = enc_bucket_count[mnem];
  const struct EncCand* first = 0; int fr = -1, fm = -1, fi = -1;
  int rank = 0;
  for (int i = 0; i < cnt; ++i) {
    const struct EncCand* c = &enc_cand[start + i];
    int r, m, im;
    if (!enc_cand_roles(c, in, &r, &m, &im)) continue;
    if (!first) { first = c; fr = r; fm = m; fi = im; }
    if (rank == in->enc) { *reg_oi = r; *rm_oi = m; *imm_oi = im; return c; }
    ++rank;
  }
  *reg_oi = fr; *rm_oi = fm; *imm_oi = fi;               // enc out of range -> canonical
  return first;
}

// Which matching candidate did these decoded opcode bytes use? -> in->enc.
static inline bool enc_cand_is_opcode(const struct EncCand* c, int tb,
                                      uint8_t opbyte, int digit, uint8_t modrm) {
  if (c->tb != tb) return false;
  uint8_t base = opbyte;
  if (c->emb == EMB_REG || c->emb == EMB_CC)
    base &= (uint8_t)~(((1u << c->emb_w) - 1u) << c->emb_pos);
  if (base != c->op) return false;
  if (c->fixmodrm) return c->fixmodrm == modrm;          // no-operand fixed-ModR/M op
  if (c->digit != 0xFF && c->digit != digit) return false;
  return true;
}
static inline void enc_stamp(x86insn_t* in, int tb, uint8_t opbyte, int digit, uint8_t modrm) {
  in->enc = 0;
  if (in->mnem >= enc_nmnem) return;
  int start = enc_bucket_start[in->mnem], cnt = enc_bucket_count[in->mnem];
  int rank = 0;
  for (int i = 0; i < cnt; ++i) {
    const struct EncCand* c = &enc_cand[start + i];
    int r, m, im;
    if (!enc_cand_roles(c, in, &r, &m, &im)) continue;
    if (enc_cand_is_opcode(c, tb, opbyte, digit, modrm)) { in->enc = rank; return; }
    ++rank;
  }
}

// ---- ModR/M / SIB / displacement -----------------------------------------
// Driven by the addressing witness (disp_w/sib/sscale): the decoder records the
// actual disp width, whether a SIB was present, and any dead scale bits, so a
// decoded operand re-emits byte-for-byte even when non-canonical (disp of zero
// written wide, gratuitous SIB, dead scale). For a freshly-built operand whose
// witness is left at zero, this collapses to the canonical shortest form.
static inline void enc_put32(uint8_t* o, size_t* p, int32_t v) {
  for (int i = 0; i < 4; ++i) o[(*p)++] = (uint8_t)(v >> (8 * i));
}
static inline void enc_mem32(uint8_t* o, size_t* p, int reg_field, const x86insn_t* in) {
  int base = in->mem_base, index = in->mem_index, scale = in->mem_scale;
  int32_t disp = in->disp;
  bool hb = base != GREG_NONE, hi = index != GREG_NONE;
  if (!hb && !hi) {                                      // [disp32]
    if (in->sib) {                                       // gratuitous SIB form (mod00 rm100)
      o[(*p)++] = (uint8_t)((reg_field << 3) | 4);
      o[(*p)++] = (uint8_t)((in->sscale << 6) | (4 << 3) | 5);
    } else {
      o[(*p)++] = (uint8_t)((reg_field << 3) | 5);       // canonical mod00 rm101
    }
    enc_put32(o, p, disp); return;
  }
  bool need_sib = in->sib || hi || base == GREG_ESP || !hb;
  int dw  = in->disp_w;                                  // 0=none 1=disp8 2=disp32
  // a base of EBP cannot use mod00 (that slot is [disp32]); force at least disp8
  if (hb && base == GREG_EBP && dw == 0) dw = 1;
  int mod = hb ? dw : 0;                                 // no base -> mod00 + disp32
  if (need_sib) {
    int idx = hi ? index : 4;                            // 4 = no index
    int bse = hb ? base : 5;                             // 5 + mod00 = no base (disp32)
    int sb  = hi ? scale : in->sscale;                   // dead scale bits when no index
    o[(*p)++] = (uint8_t)((mod << 6) | (reg_field << 3) | 4);
    o[(*p)++] = (uint8_t)((sb << 6) | (idx << 3) | bse);
  } else {
    o[(*p)++] = (uint8_t)((mod << 6) | (reg_field << 3) | base);
  }
  if (!hb)            enc_put32(o, p, disp);             // SIB no-base disp32
  else if (mod == 1)  o[(*p)++] = (uint8_t)disp;
  else if (mod == 2)  enc_put32(o, p, disp);
}
static inline void enc_mem16(uint8_t* o, size_t* p, int reg_field, const x86insn_t* in) {
  int base = in->mem_base, index = in->mem_index; int32_t disp = in->disp;
  bool hb = base != GREG_NONE, hi = index != GREG_NONE;
  if (!hb && !hi) {                                      // [disp16]  (mod00 rm110)
    o[(*p)++] = (uint8_t)((reg_field << 3) | 6);
    o[(*p)++] = (uint8_t)disp; o[(*p)++] = (uint8_t)(disp >> 8); return;
  }
  // (base,index) -> rm16 code: bx+si,bx+di,bp+si,bp+di,si,di,bp,bx  (16-bit reg #s)
  static const int B[8] = {3, 3, 5, 5, 6, 7, 5, 3};
  static const int I[8] = {6, 7, 6, 7, 15, 15, 15, 15};
  int want_i = hi ? index : 15, rm = 7;
  for (int k = 0; k < 8; ++k) if (B[k] == base && I[k] == want_i) { rm = k; break; }
  int dw = in->disp_w;
  if (rm == 6 && dw == 0) dw = 1;                        // [bp] needs at least disp8
  int mod = dw;                                          // 0/1/2
  o[(*p)++] = (uint8_t)((mod << 6) | (reg_field << 3) | rm);
  if (mod == 1)      o[(*p)++] = (uint8_t)disp;
  else if (mod == 2) { o[(*p)++] = (uint8_t)disp; o[(*p)++] = (uint8_t)(disp >> 8); }
}

// 64-bit ModR/M/SIB/disp: like enc_mem32 but RIP-relative ([rip+disp32]),
// absolute via the SIB no-base form, and base/index masked to 3 bits (the 4th
// bit is in the REX byte, which the encoder replays from pfx[]). The esp/r12
// (low 3 == 4) SIB-forcing and rbp/r13 (low 3 == 5) disp-forcing tests are on
// the low 3 bits, matching the hardware.
static inline void enc_mem64(uint8_t* o, size_t* p, int reg_field, const x86insn_t* in) {
  int base = in->mem_base, index = in->mem_index, scale = in->mem_scale;
  int32_t disp = in->disp;
  reg_field &= 7;
  if (in->rip) {                                         // [rip+disp32]: mod=00 rm=101
    o[(*p)++] = (uint8_t)((reg_field << 3) | 5);
    enc_put32(o, p, disp); return;
  }
  bool hb = base != GREG_NONE, hi = index != GREG_NONE;
  if (!hb && !hi) {                                      // absolute [disp32]: SIB no-base
    o[(*p)++] = (uint8_t)((reg_field << 3) | 4);
    o[(*p)++] = (uint8_t)((in->sscale << 6) | (4 << 3) | 5);
    enc_put32(o, p, disp); return;
  }
  bool need_sib = in->sib || hi || (hb && (base & 7) == 4) || !hb;
  int dw = in->disp_w;                                   // 0=none 1=disp8 2=disp32
  if (hb && (base & 7) == 5 && dw == 0) dw = 1;          // rbp/r13 base: no mod00 slot
  int mod = hb ? dw : 0;                                 // no base -> mod00 + disp32
  if (need_sib) {
    int idx = hi ? (index & 7) : 4;                      // 4 = no index
    int bse = hb ? (base & 7) : 5;                       // 5 + mod00 = no base
    int sb  = hi ? scale : in->sscale;
    o[(*p)++] = (uint8_t)((mod << 6) | (reg_field << 3) | 4);
    o[(*p)++] = (uint8_t)((sb << 6) | (idx << 3) | bse);
  } else {
    o[(*p)++] = (uint8_t)((mod << 6) | (reg_field << 3) | (base & 7));
  }
  if (!hb)            enc_put32(o, p, disp);             // SIB no-base disp32
  else if (mod == 1)  o[(*p)++] = (uint8_t)disp;
  else if (mod == 2)  enc_put32(o, p, disp);
}

// ---- immediate ------------------------------------------------------------
static inline void enc_imm(uint8_t* o, size_t* p, int imk, int opsize,
                           int64_t imm, int32_t sel) {
  int w;
  switch (imk) {
    case IMK_NONE: return;
    case IMK_IMM8: case IMK_IMM8SX: case IMK_REL8: w = 1; break;
    case IMK_IMM16: w = 2; break;
    case IMK_IMM32: w = 4; break;
    case IMK_IMMZ: case IMK_RELZ: w = (opsize == 1) ? 2 : 4; break;  // 16->2; 32/64->4
    case IMK_IMMV: w = (opsize == 1) ? 2 : (opsize == 2) ? 8 : 4; break;  // mov r,imm: 64 under REX.W
    case IMK_PTR:  enc_put32(o, p, imm);
                   o[(*p)++] = (uint8_t)sel; o[(*p)++] = (uint8_t)(sel >> 8); return;
    case IMK_ENTER: o[(*p)++] = (uint8_t)imm; o[(*p)++] = (uint8_t)(imm >> 8);
                    o[(*p)++] = (uint8_t)sel; return;     // imm16 frame : imm8 level
    case IMK_IMM8X2: o[(*p)++] = (uint8_t)imm; o[(*p)++] = (uint8_t)sel; return;  // extrq/insertq
    default: return;
  }
  for (int i = 0; i < w; ++i) o[(*p)++] = (uint8_t)(imm >> (8 * i));
}

// ---- the encoder ----------------------------------------------------------
// returns byte length, or 0 if the insn cannot be encoded (no candidate).
// VEX/EVEX/XOP/APX tail structure: does (map, opcode) carry a ModR/M, and how many
// immediate bytes follow. The prefix bytes are replayed verbatim, so only the tail
// layout matters here. This reads the generated `vextail` table (x86_tables.h),
// compiled from the corpus cells (has_modrm bit 7 | imm field: 0/1/2/4 bytes, 15 =
// immz). Queried for covered opcodes (must match what the FSM consumed) and for the
// structural fallback alike; a missing (map,opcode) keeps the table's seeded per-map
// default so the split stays deterministic and bijective. map: 1/2/3 = 0F/0F38/0F3A,
// 4 = APX, 8/9/10 = XOP.
static inline void vex_structure(int map, uint8_t op, int opsize, int* has_modrm, int* imm_len) {
  int idx;
  if      (map >= 1 && map <= 3)  idx = map - 1;     // 0F / 0F38 / 0F3A (VEX + EVEX)
  else if (map == 4)              idx = 6;           // APX EVEX-promoted legacy
  else if (map >= 8 && map <= 10) idx = map - 5;     // XOP 8 / 9 / 10
  else if (map == 7)            { *has_modrm = 1; *imm_len = 4; return; }  // VEX map7: urdmsr/uwrmsr r64,imm32
  else { *has_modrm = 1; *imm_len = 0; return; }     // reserved EVEX maps (0/5/6): modrm, no imm
  uint8_t e = vextail[idx][op];
  *has_modrm = (e >> 7) & 1;
  int imf = e & 0x7f;
  *imm_len = (imf == 15) ? ((opsize == 1) ? 2 : 4) : imf;          // 15 = immz (opsize)
}

// Re-emit a VEX instruction: [C4|C5] <vex bytes> <opcode> <modrm/addr> <imm?>.
static inline size_t vex_encode(const x86insn_t* in, uint8_t* out) {
  size_t p = 0;
  if (in->vex == 5) {                              // mov cr/dr: 0F + opcode + raw modrm
    out[p++] = 0x0F; out[p++] = in->vex_op; out[p++] = in->vex1;
    return p;
  }
  if (in->vex == 6) {                              // REX2 mov cr/dr: opcode + raw modrm
    out[p++] = in->vex_op; out[p++] = in->vex1;    // (the 0F is implied by REX2.M0, replayed)
    return p;
  }
  int map;
  if (in->vex == 3) {                              // EVEX: 62 P0 P1 P2
    out[p++] = 0x62; out[p++] = in->vex1; out[p++] = in->vex2; out[p++] = in->vex3;
    map = in->vex1 & 0x07;
  } else {                                         // VEX (C5/C4) or XOP (8F)
    out[p++] = (in->vex == 1) ? 0xC5 : (in->vex == 4) ? 0x8F : 0xC4;
    out[p++] = in->vex1;
    if (in->vex != 1) out[p++] = in->vex2;
    map = (in->vex == 1) ? 1 : (in->vex1 & 0x1f);
  }
  out[p++] = in->vex_op;
  int has_modrm, imm_len;
  vex_structure(map, in->vex_op, in->opsize, &has_modrm, &imm_len);
  // APX map-4 f6/f7 /0,/1 (ctest r/m,imm) ride the no-imm not/neg group cell, so
  // vex_structure reports no immediate; restore it by the replayed ModR/M /digit.
  // Gate on in->apx so this fires ONLY for a covered ctest decode (where the decoder
  // consumed the imm via the per-digit CAP_IMK override) and never for the structural
  // placeholder path (uncovered pp=F3/F2 f6/f7, which carries no imm) -- keeping the
  // decode-length and encode-length identical for a byte-exact round-trip.
  if (in->apx && (in->vex_op == 0xf6 || in->vex_op == 0xf7) &&
      ((in->vex_modrm >> 3) & 7) <= 1)
    imm_len = (in->vex_op == 0xf6) ? 1 : ((in->opsize == 1) ? 2 : 4);
  if (has_modrm) {
    // Replay the raw ModR/M byte captured at decode. For a memory r/m the SIB/disp
    // are rebuilt from the addressing witness (reg/base/index high bits ride in the
    // replayed VEX prefix); for a register r/m the byte is emitted verbatim. Using
    // vex_modrm (not op[]) keeps the byte-exact round-trip independent of how
    // vex_decode reorders the operands for display.
    int reg = (in->vex_modrm >> 3) & 7;
    if ((in->vex_modrm & 0xC0) != 0xC0) {          // memory r/m
#if ARCH_MODE == 64
      enc_mem64(out, &p, reg, in);
#else
      if (in->addr) enc_mem16(out, &p, reg, in);
      else          enc_mem32(out, &p, reg, in);
#endif
    } else out[p++] = in->vex_modrm;               // register-direct: verbatim
  }
  for (int i = 0; i < imm_len; ++i) out[p++] = (uint8_t)(in->imm >> (8 * i));
  return p;
}

static inline size_t encode_insn(const x86insn_t* in, uint8_t* out) {
  size_t p = 0;
  for (int i = 0; i < in->n_pfx; ++i) out[p++] = in->pfx[i];   // replay prefix run
  if (in->mnem == MNEM_PAUSE) { out[p++] = 0x90; return p; }   // PAUSE: F3 (in pfx[]) + 90
  if (in->vex) return p + vex_encode(in, out + p);             // VEX path
  if (in->moffs) {                            // mov acc<->[moffs]: opcode + absolute addr
    out[p++] = in->vex_op;
#if ARCH_MODE == 64
    int aw = in->addr ? 4 : 8;                // 64-bit address (8), or 32 under a 67
#else
    int aw = in->addr ? 2 : 4;                // 32-bit address (4), or 16 under a 67
#endif
    for (int i = 0; i < aw; ++i) out[p++] = (uint8_t)((uint64_t)in->imm >> (8 * i));
    return p;
  }

  int reg_oi, rm_oi, imm_oi;
  const struct EncCand* c = enc_select(in, &reg_oi, &rm_oi, &imm_oi);
  if (!c) return 0;

  // escape prefix: 0F, then 38/3A for the three-byte maps. A REX2 (D5) instruction
  // folds the 0F into its map bit M0 (replayed in the payload), so the 0F is not
  // emitted separately -- REX2 only reaches the 1-byte and 0F maps.
  if (c->tb && !in->rex2) {
    out[p++] = 0x0F;
    if (c->tb == 2)      out[p++] = 0x38;
    else if (c->tb == 3) out[p++] = 0x3A;
  }
  uint8_t op = c->op;
  if (c->emb == EMB_REG)
    op |= (uint8_t)((in->op[reg_oi].index & ((1u << c->emb_w) - 1u)) << c->emb_pos);
  else if (c->emb == EMB_CC)
    op |= (uint8_t)((in->cc & ((1u << c->emb_w) - 1u)) << c->emb_pos);
  out[p++] = op;

  if (c->fixmodrm) {                                       // fixed-ModR/M op: opcode + literal
    out[p++] = c->fixmodrm;                                // ModR/M, then any trailing imm/rel
    enc_imm(out, &p, c->imk, in->opsize, in->imm, in->disp);   // (xabort ib / xbegin rel; NONE=noop)
    return p;
  }

  if (c->form == FORM_MODRM || c->form == FORM_RM || c->form == FORM_GROUP) {
    int reg_field = (c->form == FORM_GROUP) ? c->digit
                  : (c->form == FORM_RM)    ? in->reg_w
                  : in->op[reg_oi].index;
    const x86op_t* rm = &in->op[rm_oi >= 0 ? rm_oi : 0];
    if (rm->type == T_MEM) {
#if ARCH_MODE == 64
      enc_mem64(out, &p, reg_field, in);                 // RIP/abs-SIB; 32-bit (67) too
#else
      if (in->addr) enc_mem16(out, &p, reg_field, in);
      else          enc_mem32(out, &p, reg_field, in);
#endif
    } else {                                             // reg-direct: low 3 bits (4th in REX)
      out[p++] = (uint8_t)(0xC0 | ((reg_field & 7) << 3) | (rm->index & 7));
    }
  }
  if (c->suffix3d) { out[p++] = c->suffix3d; return p; }  // 3DNow!: trailing opcode byte
  enc_imm(out, &p, c->imk, in->opsize, in->imm, in->disp);
  return p;
}

#endif // X86ENC_HPP
